### ISSUE TITLE
Failed at the supabase@1.13.0 preinstall script

### ISSUE THREAD

**Issue by N00nDay** [supabase/supabase#10341]
# Bug report

## Describe the bug

I am trying to install supabase but I am receiving the following error:
```
509 verbose stack Error: supabase@1.13.0 preinstall: `node scripts/preinstall.js`
509 verbose stack Exit status 1
509 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
509 verbose stack     at EventEmitter.emit (node:events:527:28)
509 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
509 verbose stack     at ChildProcess.emit (node:events:527:28)
509 verbose stack     at maybeClose (node:internal/child_process:1092:16)
509 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
510 verbose pkgid supabase@1.13.0
511 verbose cwd /Users/craighowell/Documents/projects/crm
512 verbose Darwin 21.6.0
513 verbose argv "/Users/craighowell/.nvm/versions/node/v16.15.0/bin/node" "/usr/local/bin/npm" "install"
514 verbose node v16.15.0
515 verbose npm  v6.14.4
516 error code ELIFECYCLE
517 error errno 1
518 error supabase@1.13.0 preinstall: `node scripts/preinstall.js`
518 error Exit status 1
519 error Failed at the supabase@1.13.0 preinstall script.
```

## To Reproduce

Run `npm install supabase`

## Expected behavior

Supabase installs

## System information

- OS: macOS
- Version of supabase-js: 2.1.0
- Version of Node.js: 16.15.0
- Version of supabase: 1.13.0

**Comment by N00nDay** [comment]
Here is the full log output

[2022-11-15T15_52_59_028Z-debug.log](https://github.com/supabase/supabase/files/10014194/2022-11-15T15_52_59_028Z-debug.log)
