### ISSUE TITLE
Nuxt 3 throw createError won't redirect Supabase error

### ISSUE THREAD

**Issue by IzakJackson** [supabase/supabase#10584]
I'm having an issue with Nuxt 3 where when I throw an error it won't redirect.

When visiting a page ```[id].vue```, I'm checking supabase to see if that id exists. If it does, it brings up the page, but if it doesn't exist it should throw an error and redirect to my error page.

Unfortunately, I can't seem to get it to redirect - it instead loads the page but without data.

throwError works until being used with the supabase module.

```
[id].vue
========

<script setup>
const client = useSupabaseClient();
const contact = ref([]);
const route = useRoute();

const getContact = async () => {
  try {
    const { data, error } = await client
      .from("contacts")
      .select()
      .eq("id", route.params.id);
    if (error) throw error;
    if (data) {
      contact.value = data[0];
    }
  } catch (error) {
    throw createError({
      statusCode: 404,
      statusMessage: "Contact not found.",
      fatal: true,
    });
  }
};
getContact();
</script>
```

If id path is a uuid, but not one in the table, I get this error in dev console:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'first_name')
```

Otherwise, dev console shows:

```
GET https://*.supabase.co/rest/v1/contacts?select=*&id=eq.645bfc84-dd93-455e-8b09-dbb20ceb 400
```

and

```
Uncaught (in promise) Error: Contact not found.
```

And if I console.log the error I get:

```
invalid input syntax for type uuid
```

I then get this error in the terminal:

```
[nitro] [dev] [unhandledRejection] H3Error: Contact not found.                                                                                                                             12:13:48
    at Module.createError (file:///Users/izakjackson/Documents/GitHub/CRM/node_modules/h3/dist/index.mjs:48:15)
    at Module.createError (/Users/izakjackson/Documents/GitHub/CRM/node_modules/nuxt/dist/app/composables/error.mjs:35:38)
    at getContact (/Users/izakjackson/Documents/GitHub/CRM/pages/contacts/[id].vue:40:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  statusCode: 404,
  fatal: true,
  unhandled: false,
  statusMessage: 'Contact not found.',
  __nuxt_error: true
}
```

**Comment by IzakJackson** [comment]
Seems to be an issue with Nuxt
