### ISSUE TITLE
"XMLHttpRequest is not defined" on sveletkit endpoints when deployed on Vercel

### ISSUE THREAD

**Issue by Pixselve** [supabase/supabase#1126]
# Bug report

## Describe the bug

Using the client for auth or for querying the database in a sveltekit endpoint throw an error :
`{
  data: null,
  error: ReferenceError: XMLHttpRequest is not defined
      at file:///var/task/server/app.mjs:2522:21
      at new Promise (<anonymous>)
      at fetch2 (file:///var/task/server/app.mjs:2517:16)
      at file:///var/task/server/app.mjs:2646:7
      at new Promise (<anonymous>)
      at file:///var/task/server/app.mjs:2645:12
      at Generator.next (<anonymous>)
      at file:///var/task/server/app.mjs:2619:67
      at new Promise (<anonymous>)
      at __awaiter$8 (file:///var/task/server/app.mjs:2601:10)
}`

## To Reproduce

I made a repository exposing the issue : https://github.com/Pixselve/supabase-sveltekit-endpoints
Click on a button to fetch the endpoint and observe the cloud functions logs on Vercel.

## Expected behavior

Requests should not fail and should give the appropriate data.

## System information

- OS: Vercel Node.js Runtime
- Version of supabase-js: 1.10.0
- Version of Node.js: 14

**Comment by kiwicopple** [comment]
Thanks for this one @Pixselve - i'll transfer it to the JS library repo
