### ISSUE TITLE
MacOS build app_links required a higher minimum deployment target.

### ISSUE THREAD

**Issue by OldMetalmind** [supabase/supabase#12492]
# Bug report

## Describe the bug

I cannot run a macOS Flutter app with `supabase_flutter` package added.

## To Reproduce

1. `flutter create test`
3. `flutter run -d macOS`  ✅ 
4. `flutter pub add supabase_flutter`
5. `flutter run -d macOS` :x: 
6. See error ⬇️ 
<details>
  <summary>Error output</summary>
  
  ```
Launching lib/main.dart on macOS in debug mode...
Running pod install...                                             431ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `FlutterMacOS` from `Flutter/ephemeral`
    -> Fetching podspec for `app_links` from
    `Flutter/ephemeral/.symlinks/plugins/app_links/macos`
    -> Fetching podspec for `path_provider_foundation` from
    `Flutter/ephemeral/.symlinks/plugins/path_provider_foundation/macos`
    -> Fetching podspec for `url_launcher_macos` from
    `Flutter/ephemeral/.symlinks/plugins/url_launcher_macos/macos`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local
      because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "app_links":
      In Podfile:
        app_links (from `Flutter/ephemeral/.symlinks/plugins/app_links/macos`)

    Specs satisfying the `app_links (from
    `Flutter/ephemeral/.symlinks/plugins/app_links/macos`)` dependency were
    found, but they required a higher minimum deployment target.

    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/molinillo-0.8.0/lib/mol
    inillo/resolution.rb:317:in `raise_error_unless_state'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/molinillo-0.8.0/lib/mol
    inillo/resolution.rb:299:in `block in unwind_for_conflict'
    <internal:kernel>:90:in `tap'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/molinillo-0.8.0/lib/mol
    inillo/resolution.rb:297:in `unwind_for_conflict'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/molinillo-0.8.0/lib/mol
    inillo/resolution.rb:682:in `attempt_to_activate'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/molinillo-0.8.0/lib/mol
    inillo/resolution.rb:254:in `process_topmost_state'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/molinillo-0.8.0/lib/mol
    inillo/resolution.rb:182:in `resolve'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/molinillo-0.8.0/lib/mol
    inillo/resolver.rb:43:in `resolve'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/co
    coapods/resolver.rb:94:in `resolve'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/co
    coapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/co
    coapods/user_interface.rb:64:in `section'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/co
    coapods/installer/analyzer.rb:1076:in `resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/co
    coapods/installer/analyzer.rb:124:in `analyze'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/co
    coapods/installer.rb:416:in `analyze'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/co
    coapods/installer.rb:241:in `block in resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/co
    coapods/user_interface.rb:64:in `section'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/co
    coapods/installer.rb:240:in `resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/co
    coapods/installer.rb:161:in `install!'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/co
    coapods/command/install.rb:52:in `run'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/claide-1.1.0/lib/claide
    /command.rb:334:in `run'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/co
    coapods/command.rb:52:in `run'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/bin/po
    d:55:in `<top (required)>'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/bin/pod:25:in `load'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/bin/pod:25:in `<main>'

Exception: Error running pod install
  ```
</details>

## Expected behavior

Be able to run the MacOS app counter app.

## System information

- OS: macOS 13.0.1 (22A400)

<details>
  <summary>flutter doctor</summary>

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.5, on macOS 13.0.1 22A400 darwin-arm, locale
    en-PT)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.75.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

</details>

## Additional context

Only when I add the package `supabase_flutter` I'm unable to run the app in MacOS.
I did tried to update my osx version at PodFile.

**Comment by OldMetalmind** [comment]
Wrong repository. My bad. Moving it to the supabase flutter package repository.
