### ISSUE TITLE
Auth bug: unable to getUser(jwt) on the back-end in latest supabase CLI version (1.47.2)

### ISSUE THREAD

**Issue by loekj** [supabase/supabase#13394]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I cannot retrieve a logged-in user on the back-end anymore. On the front-end a session is created, and on the back-end the auth token is used in `getUser(authToken)` to retrieve the user. This returns `null`. I'm using NodeJs and I upgraded to supabase 1.47.2 (through homebrew). Before this I was running supabase 1.11.0 and it was working fine.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run locally the latest version of supabase CLI (1.47.2) and use that for your local db environment, and the npm package `@supabase/supabase-js` on the latest version (2.13.1)
2. Create a session for a user that is registered `session = await supabase.auth.getSession();`
3. Use the access token `authToken = session.data.session.access_token` to `await supabase.auth.getUser(authToken)`
4. The `data.user` returned from `getUser` is `null` with the error message `AuthApiError: Invalid authentication credentials`

## Expected behavior

The user is authenticated as the JWT is a valid session token, so the back-end should just retrieve the user session like normal

## System information

- OS: macOS Venture 13.2.1
- Browser (if applies): Chrome 111.0.5563.110 (Official Build) (x86_64)
- Version of supabase CLI: 1.47.2
- Version of supabase-js: 2.13.1
- Version of Node.js: 19.8.1

**Comment by jakexconniff** [comment]
I am also receiving this error on Windows 11 in a very simple tutorial setup.

Error from Deno server:

```[Info] {
  data: { user: null },
  error: AuthApiError: invalid claim: missing sub claim
    at le (https://esm.sh/v135/@supabase/gotrue-js@2.57.0/esnext/gotrue-js.mjs:2:5282)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async Ie (https://esm.sh/v135/@supabase/gotrue-js@2.57.0/esnext/gotrue-js.mjs:2:6069)
    at async h (https://esm.sh/v135/@supabase/gotrue-js@2.57.0/esnext/gotrue-js.mjs:2:5806)
    at async https://esm.sh/v135/@supabase/gotrue-js@2.57.0/esnext/gotrue-js.mjs:2:26219
    at async g._useSession (https://esm.sh/v135/@supabase/gotrue-js@2.57.0/esnext/gotrue-js.mjs:2:25008)
    at async g._getUser (https://esm.sh/v135/@supabase/gotrue-js@2.57.0/esnext/gotrue-js.mjs:2:26136)
    at async https://esm.sh/v135/@supabase/gotrue-js@2.57.0/esnext/gotrue-js.mjs:2:25999
    at async https://esm.sh/v135/@supabase/gotrue-js@2.57.0/esnext/gotrue-js.mjs:2:24294 {
    __isAuthError: true,
    name: "AuthApiError",
    status: 401
  }
}```

I have tried removing supabase folder and re-installing from scratch, restarting Docker containers, etc. Just following the tutorial here: https://supabase.com/docs/guides/functions and https://supabase.com/docs/guides/functions/auth

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
