### ISSUE TITLE
running supabase functions serve fails. running supabase functions serve <name> causes postgres connection to fail

### ISSUE THREAD

**Issue by oldbettie** [supabase/supabase#15028]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
seems like there is an issue with a `deno` package when running ` supabase functions serve` I get this following error.

```
worker "/home/deno/functions/scraper" returned an error: Uncaught SyntaxError: The requested module '/v125/jszip@3.5.0/esnext/lib/readable-stream-browser.js' does not provide an export named 'default'
    at https://esm.sh/v125/jszip@3.5.0/esnext/jszip.mjs:2:291
InvalidWorkerCreation: worker boot error
    at async Function.create (ext:sb_user_workers/user_workers.js:80:21)
    at async Server.<anonymous> (file:///home/deno/main/index.ts:95:24)
    at async Server.#respond (https://deno.land/std@0.182.0/http/server.ts:220:24)
```

if I run `supabase functions serve <function-name> --env-file supabase/.env` then it will work once but needs to be restarted after every run.

I also have an issue with postgres not connecting using both the old URL method and the new pool params method
```
const uri = Deno.env.get("DATABASE_URL")
const pool = new Pool(uri, 3, true)
```
or
```
const pool = new Pool(
  {
    tls: { enabled: false },
    database: "postgres",
    hostname: Deno.env.get("DB_HOSTNAME"),
    user: "postgres",
    port: 5432,
    password: Deno.env.get("DB_PASSWORD"),
  },
  1
)
```
both fail to connect with this error
```
ConnectionRefused: Connection refused (os error 111)
at async Object.connect (internal:ext/net/01_net.js:384:57)
    at async Connection.#openConnection (https://deno.land/x/postgres@v0.17.0/connection/connection.ts:253:18)
    at async Connection.#startup (https://deno.land/x/postgres@v0.17.0/connection/connection.ts:338:7)
    at async Connection.startup (https://deno.land/x/postgres@v0.17.0/connection/connection.ts:491:11)
    at async PoolClient.connect (https://deno.land/x/postgres@v0.17.0/client.ts:220:7)
    at async DeferredAccessStack.pop (https://deno.land/x/postgres@v0.17.0/utils/deferred.ts:121:7)
    at async Server.<anonymous> (file:///home/deno/functions/scraper/index.ts:33:20)
    at async Server.#respond (https://deno.land/std@0.168.0/http/server.ts:301:18)
```

seems to only be when done locally. which makes it incrediby frustrating to have to deploy changes everytime we want to test a function.

## To Reproduce
start supabase and run `supabase functions serve`

## Expected behavior
the functions should work and postgres should connect

the function should execute and hot reload locally as expected. deno seems to be flawed 

## System information

- OS: Ventura 13.4
- Browser chrome
- Version of supabase-js: 1.68.6
- Version of Node.js: 20.3.0

## Additional context
seems like local lambda is still quite buggy.

**Comment by gregnr** [comment]
Thanks for reporting @oldbettie. That would definitely be frustrating having to deploy each time just to test - not at all the intended pattern.

I took a look into [jszip](https://github.com/Stuk/jszip) and it looks like they are doing some advanced [import logic](https://github.com/Stuk/jszip/blob/2ceb998e29d4171b4f3f2ecab1a2195c696543c0/package.json#L32) with `readable-stream` (where you are getting the error).

@supabase/edge-functions it's not clear to me why this would work on Deno Deploy but not `edge-runtime` - any chance the import logic is slightly different between the two (eg. `User-Agent` sent to esm.sh is uses to determine the build target)?

@oldbettie in the mean time I was able to solve this specific problem by adding `?bundle` to the esm.sh import:
```ts
import JSZip from 'https://esm.sh/v125/jszip@3.5.0?bundle';
```

which tells esm.sh to bundle all dependencies into a single JS file.

Let me know if this helps.
