### ISSUE TITLE
Application error: a client-side exception has occurred when changing schemas

### ISSUE THREAD

**Issue by FortyGazelle700** [supabase/supabase#15466]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

(the checkboxes should be checked)

## Describe the bug

When changing schemas from public to a protected schema it throws an error

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [supabase.com](https://supabase.com)
2. Sign In
3. Enter a project
4. Go to the Table Editor
5. Changing the schema to a protected (or possibly unprotected but idk) e.g. auth

## Expected behavior

I would expect the UI to show me a table editor instead of an error

## Screenshots

![image](https://github.com/supabase/supabase/assets/101235639/995b713a-ca66-4ce2-b3bd-d483e7c4e56c)
![image](https://github.com/supabase/supabase/assets/101235639/34812d96-6e09-4664-b44c-2080106095ab)
Console as a log
```
instrument.js:109  Error: Minified React error #311; visit https://reactjs.org/docs/error-decoder.html?invariant=311 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at co (react-dom.production.min.js:159:55)
    at Object.useState (react-dom.production.min.js:174:261)
    at t.useState (react.production.min.js:23:281)
    at S (useLocalStorage.ts:8:41)
    at EmptyState.tsx:20:18
    at observer.js:42:49
    at useObserver.js:115:25
    at Qe (mobx.esm.js:1679:18)
    at t.track (mobx.esm.js:2198:18)
    at v (useObserver.js:113:18)
    at u (observer.js:42:16)
    at oo (react-dom.production.min.js:157:137)
    at Bo (react-dom.production.min.js:180:154)
    at jo (react-dom.production.min.js:178:169)
    at Ki (react-dom.production.min.js:274:157)
    at Lu (react-dom.production.min.js:250:347)
    at Nu (react-dom.production.min.js:250:278)
    at Pu (react-dom.production.min.js:250:138)
    at bu (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ql (react-dom.production.min.js:122:325)
    at Yl (react-dom.production.min.js:123:61)
    at Kl (react-dom.production.min.js:122:428)
    at t.flushSync (react-dom.production.min.js:295:377)
    at c (index.mjs:87:17)
    at index.mjs:457:13
    at index.mjs:4:149
    at Object.$e (react-dom.production.min.js:52:317)
    at Ye (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at Nr (react-dom.production.min.js:100:68)
    at zr (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
    at De (react-dom.production.min.js:292:189)
    at react-dom.production.min.js:50:57
    at Ir (react-dom.production.min.js:105:469)
    at Jt (react-dom.production.min.js:75:265)
    at Zt (react-dom.production.min.js:74:124)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ql (react-dom.production.min.js:122:325)
    at Me (react-dom.production.min.js:292:48)
    at Xt (react-dom.production.min.js:73:352)
    at HTMLDivElement.i (helpers.js:74:23)
(anónimo) @ instrument.js:109
instrument.js:109  Error: Minified React error #311; visit https://reactjs.org/docs/error-decoder.html?invariant=311 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at co (react-dom.production.min.js:159:55)
    at Object.useState (react-dom.production.min.js:174:261)
    at t.useState (react.production.min.js:23:281)
    at S (useLocalStorage.ts:8:41)
    at EmptyState.tsx:20:18
    at observer.js:42:49
    at useObserver.js:115:25
    at Qe (mobx.esm.js:1679:18)
    at t.track (mobx.esm.js:2198:18)
    at v (useObserver.js:113:18)
    at u (observer.js:42:16)
    at oo (react-dom.production.min.js:157:137)
    at Bo (react-dom.production.min.js:180:154)
    at jo (react-dom.production.min.js:178:169)
    at Ki (react-dom.production.min.js:274:157)
    at Lu (react-dom.production.min.js:250:347)
    at Nu (react-dom.production.min.js:250:278)
    at Pu (react-dom.production.min.js:250:138)
    at bu (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ql (react-dom.production.min.js:122:325)
    at Yl (react-dom.production.min.js:123:61)
    at Kl (react-dom.production.min.js:122:428)
    at t.flushSync (react-dom.production.min.js:295:377)
    at c (index.mjs:87:17)
    at index.mjs:457:13
    at index.mjs:4:149
    at Object.$e (react-dom.production.min.js:52:317)
    at Ye (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at Nr (react-dom.production.min.js:100:68)
    at zr (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
    at De (react-dom.production.min.js:292:189)
    at react-dom.production.min.js:50:57
    at Ir (react-dom.production.min.js:105:469)
    at Jt (react-dom.production.min.js:75:265)
    at Zt (react-dom.production.min.js:74:124)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ql (react-dom.production.min.js:122:325)
    at Me (react-dom.production.min.js:292:48)
    at Xt (react-dom.production.min.js:73:352)
    at HTMLDivElement.i (helpers.js:74:23)
(anónimo) @ instrument.js:109
instrument.js:109  A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
(anónimo) @ instrument.js:109
```

## System information

- OS: Windows 11 (Windows 11 Insider Preview 25393.1 (zn_release))
- Browser: Edge 114.0.1823.58 and Chrome 114.0.5735.199

**Comment by rarcifa** [comment]
Same issue here yesterday. Today it started to work again. There has been some issues with github yesterday, not sure how and if it somehow impacts this issue?

**Comment by FortyGazelle700** [comment]
It worked when I first got to the site, and then decided not work, but then after creating this Bug Report it now seems to work, so I have no idea what is going on.

**Comment by saltcod** [comment]
Closing as out of date, but please feel free to reopen if this pops up again!
