### ISSUE TITLE
supabase-analytics container does not start

### ISSUE THREAD

**Issue by tomoyukiy** [supabase/supabase#16442]
# Bug report

When I run "docker-compose up" I get the following problem.

## To Reproduce

1. Go to docker directory
2. run 'docker-compose up'

supabase-analytics              | ** (Postgrex.Error) ERROR 3F000 (invalid_schema_name) no schema has been selected to create in
〜〜〜〜〜〜〜
supabase-analytics              | Crash dump is being written to: erl_crash.dump...
supabase-analytics              | done
supabase-analytics              | sh: 11:31:36.296: not found
supabase-analytics exited with code 127
dependency failed to start: container supabase-analytics is unhealthy

M2 Mac Book Air
Docker Desktop version: 4.22.0
branch: 297584a0dd175c41bb0cd17175b51600dc468e00

**Comment by m10rten** [comment]
having the same issue:

> in local when: `docker compose up -d`

```txt
container for service "analytics" is unhealthy
```

> Docker logs - supabase-analytics supabase/logflare:1:4:0
```txt
Crash dump is being written to: erl_crash.dump...done
sh: 10:20:17.202: not found
** (Postgrex.Error) ERROR 3F000 (invalid_schema_name) no schema has been selected to create in
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.10.1) lib/ecto/migrator.ex:738: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.10.1) lib/ecto/migrator.ex:552: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.10.1) lib/ecto/migrator.ex:428: Ecto.Migrator.run/4
    (ecto_sql 3.10.1) lib/ecto/migrator.ex:170: Ecto.Migrator.with_repo/3
    nofile:1: (file)
Kernel pid terminated (application_controller) ({application_start_failure,logflare,{{shutdown,{failed_to_start_child,'Elixir.Logflare.SystemMetricsSup',{shutdown,{failed_to_start_child,'Elixir.Logflare.SystemMetrics.AllLogsLogged',{#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 102,message => nil,postgres => #{code => undefined_table,file => <<"parse_relation.c">>,line => <<"1392">>,message => <<"relation \"system_metrics\" does not exist">>,pg_code => <<"42P01">>,position => <<"89">>,routine => <<"parserOpenTable">>,severity => <<"ERROR">>,unknown => <<"ERROR">>},query => <<"SELECT s0.\"id\", s0.\"all_logs_logged\", s0.\"node\", s0.\"inserted_at\", s0.\"updated_at\" FROM \"system_metrics\" AS s0 WHERE (s0.\"node\" = $1)">>},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,"lib/ecto/adapters/sql.ex"},{line,913},{error_info,#{module => 'Elixir.Exception'}}]},{'Elixir.Ecto.Adapters.SQL',execute,6,[{file,"lib/ecto/adapters/sql.ex"},{line,828}]},{'Elixir.Ecto.Repo.Q
```

**Comment by m10rten** [comment]
However when started via the supabase CLI (and having cleared all images and volumes in docker) with `supabase start` (not logged in) it all works like a charm.

**Comment by tomoyukiy** [comment]
@m10rten 
I tried the above method and it worked fine !
Thank you very much.

**Comment by snsnf** [comment]
Hi, how to start the docker using the Supabase CLI? I tried `supabase start` but another Supabase project starts not my main self-hosted project

I'm facing the same problem.

**Comment by tomoyukiy** [comment]
@snsnf 
In my case, I needed to connect to a docker container's DB in order to launch the Studio dashboard.
So I did the following steps.

1. Launched the docker container with `supabase start`.
2. Change the connection destination of the DB of the local project. 
    [ studio/.env](https://github.com/supabase/supabase/blob/70b5a9dea4f0d9e77c69852981fa81ba9612f73a/studio/.env#L1C1-L1C44)
    `STUDIO_PG_META_URL=http://localhost:8000/pg
 => STUDIO_PG_META_URL=http://localhost:54321/pg`
3. Launch a local project with `npm run dev`
4. Visited http://localhost:8082/

I hope it helps you.

**Comment by xleven** [comment]
I can confirm this issue still exists when you already have database files, i.e. in volumes/db/data, although a fresh docker compose works. Guess something wrong with db migration on the mentioned `system_metrics` schema?

Hi @tomoyukiy do you mind reopen it?

**Comment by tomoyukiy** [comment]
Hi @xleven 
Reopend it.

**Comment by vincelwt** [comment]
Happened to me last night when trying to update my existing self-hosted instance to latest updates. Temporary workaround has been to comment everything relating to `analytics` in the docker-compose

**Comment by filipecabaco** [comment]
If you were running self-hosted with analytics before this changes you might have some data on the schema where they are stored

One way to fix is to follow this steps:
```bash
### Destroy analytics to transition to postgres self hosted solution without other data loss

# Enter the container and use your .env POSTGRES_PASSWORD value to login
docker exec -it $(docker ps | grep supabase-db | awk '{print $1}') psql -U supabase_admin --password 
# Drop all the data in the _analytics schema
DROP PUBLICATION logflare_pub; DROP SCHEMA _analytics CASCADE; CREATE SCHEMA _analytics;\q
# Drop the analytics container
docker rm supabase-db
```

This will destroy all things analytics related in the database without touching the remainder of the data and allows everything to be restarted as intended.

**Comment by antonioabelgc** [comment]
> If you were running self-hosted with analytics before this changes you might have some data on the schema where they are stored
> 
> One way to fix is to follow this steps:
> 
> ```shell
> ### Destroy analytics to transition to postgres self hosted solution without other data loss
> 
> # Enter the container and use your .env POSTGRES_PASSWORD value to login
> docker exec -it $(docker ps | grep supabase-db | awk '{print $1}') psql -U supabase_admin --password 
> # Drop all the data in the _analytics schema
> DROP PUBLICATION logflare_pub; DROP SCHEMA _analytics CASCADE; CREATE SCHEMA _analytics;\q
> # Drop the analytics container
> docker rm supabase-db
> ```
> 
> This will destroy all things analytics related in the database without touching the remainder of the data and allows everything to be restarted as intended.

This worked for me. Thank you!

**Comment by Nunchakus888** [comment]
Reopend it please.  2025, the latest version

![Image](https://github.com/user-attachments/assets/6d831cd3-c374-4c3b-b28a-6895ab6e66c0)

![Image](https://github.com/user-attachments/assets/c9a8f42e-83f6-4d03-a99d-f6576fc5770c)

**Comment by hayderab** [comment]
getting the same issue 
if have tried this :
`docker exec -it $(docker ps | grep supabase-db | awk '{print $1}') psql -U supabase_admin --password
`  
but POSTGRES_PASSWORD is not being recognised . I have changed the password in .env file.  

OS: Window 11
