### ISSUE TITLE
Calling addEventListener in an Edge Function triggers Illegal invocation at Module.assertBranded

### ISSUE THREAD

**Issue by y0n3t4n1** [supabase/supabase#16875]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
The following piece of code triggers `TypeError: Illegal invocation at Module.assertBranded` if it's run as an Edge Function on Supabase cloud service, but not if it's run locally.
```
import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'

serve(() => {
  let response = 'OK'
  let status = 200
  try {
    addEventListener('close', () => console.debug('close'), false)
  } catch (e) {
    console.error(e)
    response = 'NG'
    status = 503
  }
  return new Response(response, {
    headers: { 'Content-Type': 'text/plain' },
    status,
  })
})
```

## To Reproduce

1. Create an Edge Function using Supabase CLI: `supabase functions new test`
2. Copy and paste above code to the created file supabase/functions/test/index.ts
3. Deploy it to Supabase: `supabase functions deploy test --no-verify-jwt`
4. Invoke the Edge Function: `curl https://YOUR-PROJECT.supabase.co/functions/v1/test`
5. Examine the error log in the console: https://supabase.com/dashboard/project/YOUR-PROJECT/functions/test/logs

## Expected behavior

No errors should be logged.

## Screenshots

```
TypeError: Illegal invocation
    at Module.assertBranded (ext:deno_webidl/00_webidl.js:897:11)
    at addEventListener (ext:deno_web/02_event.js:958:12)
    at Server.<anonymous> (file:///home/user_functions/YOUR-PROJECT_29f007b8-f883-486b-9cc4-71406a8782ed_65/code/C:/Users/techtouch/Documents/techtouch-inc/ai-platform/supabase/functions/test/index.ts:6:9)
    at Server.#respond (file:///home/user_functions/YOUR-PROJECT_29f007b8-f883-486b-9cc4-71406a8782ed_65/code/deno.land/std@0.168.0/http/server.ts:221:43)
    at Server.#serveHttp (file:///home/user_functions/YOUR-PROJECT_29f007b8-f883-486b-9cc4-71406a8782ed_65/code/deno.land/std@0.168.0/http/server.ts:258:26)
```

## System information

- OS: Windows 10, but it shouldn't matter
- Version of supabase-js: 2.26.0
- Version of Deno: 1.30.3
- Version of Supabase CLI: 1.88.0

**Comment by laktek** [comment]
@y0n3t4n1 `addEventListener` on response objects isn't supported on Edge Functions. You can try streaming the response body and handling client closing the connection with `cancel`, as described here https://docs.deno.com/runtime/manual/runtime/http_server_apis#responding-with-a-response

**Comment by y0n3t4n1** [comment]
I don't need to use it, but some third-party libraries apparently do, e.g., https://github.com/socketio/engine.io-client/blob/6.5.2/lib/socket.ts#L393
This Illegal invocation thing started bothering me exactly five months ago.  Before that day, the global `addEventListener` function either didn't exist, or it was defined as NO-OP.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
