### ISSUE TITLE
Server-side RPC throws `cookies() expects to have requestAsyncStorage`

### ISSUE THREAD

**Issue by kirkstrobeck** [supabase/supabase#18007]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When using an rpc on server-side in a react server components next js app with pnpm, I get this error even though it completes successfully 

```
Error: Invariant: cookies() expects to have requestAsyncStorage, none available.
    at Object.cookies (webpack-internal:///(rsc)/../../node_modules/.pnpm/next@13.5.3_@opentelemetry+api@1.6.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/headers.js:50:15)
    at NextServerComponentAuthStorageAdapter.getCookie (webpack-internal:///(rsc)/../../node_modules/.pnpm/@supabase+auth-helpers-nextjs@0.8.1_@supabase+supabase-js@2.36.0/node_modules/@supabase/auth-helpers-nextjs/dist/index.js:196:42)
    at NextServerComponentAuthStorageAdapter.getItem (webpack-internal:///(rsc)/../../node_modules/.pnpm/@supabase+auth-helpers-shared@0.5.0_@supabase+supabase-js@2.36.0/node_modules/@supabase/auth-helpers-shared/dist/index.js:266:28)
    at getItemAsync (webpack-internal:///(rsc)/../../node_modules/.pnpm/@supabase+gotrue-js@2.54.0/node_modules/@supabase/gotrue-js/dist/main/lib/helpers.js:133:33)
    at SupabaseAuthClient._recoverAndRefresh (webpack-internal:///(rsc)/../../node_modules/.pnpm/@supabase+gotrue-js@2.54.0/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:1468:69)
    at SupabaseAuthClient._initialize (webpack-internal:///(rsc)/../../node_modules/.pnpm/@supabase+gotrue-js@2.54.0/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:176:24)
    at eval (webpack-internal:///(rsc)/../../node_modules/.pnpm/@supabase+gotrue-js@2.54.0/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:136:35)
    at eval (webpack-internal:///(rsc)/../../node_modules/.pnpm/@supabase+gotrue-js@2.54.0/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:814:36)
    at SupabaseAuthClient.lockNoOp [as lock] (webpack-internal:///(rsc)/../../node_modules/.pnpm/@supabase+gotrue-js@2.54.0/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:34:18)
    at SupabaseAuthClient._acquireLock (webpack-internal:///(rsc)/../../node_modules/.pnpm/@supabase+gotrue-js@2.54.0/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:810:31)
webpack-internal:///(rsc)/../../node_modules/.pnpm/next@13.5.3_@opentelemetry+api@1.6.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/headers.js:50
        throw new Error("Invariant: cookies() expects to have requestAsyncStorage, none available.");
              ^

Error: Invariant: cookies() expects to have requestAsyncStorage, none available.
    at Object.cookies (webpack-internal:///(rsc)/../../node_modules/.pnpm/next@13.5.3_@opentelemetry+api@1.6.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/headers.js:50:15)
    at NextServerComponentAuthStorageAdapter.getCookie (webpack-internal:///(rsc)/../../node_modules/.pnpm/@supabase+auth-helpers-nextjs@0.8.1_@supabase+supabase-js@2.36.0/node_modules/@supabase/auth-helpers-nextjs/dist/index.js:196:42)
    at NextServerComponentAuthStorageAdapter.getItem (webpack-internal:///(rsc)/../../node_modules/.pnpm/@supabase+auth-helpers-shared@0.5.0_@supabase+supabase-js@2.36.0/node_modules/@supabase/auth-helpers-shared/dist/index.js:266:28)
    at getItemAsync (webpack-internal:///(rsc)/../../node_modules/.pnpm/@supabase+gotrue-js@2.54.0/node_modules/@supabase/gotrue-js/dist/main/lib/helpers.js:133:33)
    at SupabaseAuthClient.__loadSession (webpack-internal:///(rsc)/../../node_modules/.pnpm/@supabase+gotrue-js@2.54.0/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:867:67)
    at SupabaseAuthClient._useSession (webpack-internal:///(rsc)/../../node_modules/.pnpm/@supabase+gotrue-js@2.54.0/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:850:39)
    at SupabaseAuthClient._emitInitialSession (webpack-internal:///(rsc)/../../node_modules/.pnpm/@supabase+gotrue-js@2.54.0/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:1348:27)
    at eval (webpack-internal:///(rsc)/../../node_modules/.pnpm/@supabase+gotrue-js@2.54.0/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:1338:22)
    at eval (webpack-internal:///(rsc)/../../node_modules/.pnpm/@supabase+gotrue-js@2.54.0/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:814:36)
    at SupabaseAuthClient.lockNoOp [as lock] (webpack-internal:///(rsc)/../../node_modules/.pnpm/@supabase+gotrue-js@2.54.0/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:34:18)

Node.js v18.12.1
```

## To Reproduce

Run this on server-side in a react server components next js app with pnpm

```ts
const { data, error } = await supabase.rpc('hello_world')
```

## Expected behavior

No error message to show

## System information

- OS: Mac 14.0 (23A344)
- Version of supabase-js: @supabase/supabase-js 2.36.0
- Version of Node.js: v18.12.1

**Comment by kirkstrobeck** [comment]
Looks like using `"use server"` may help

**Comment by justin-gurtz** [comment]
Not sure if this is related but I'm getting a similar error using Next.js route handlers, specifically in the edge runtime. The default Node.js runtime works fine. No errors locally, only deployed on Vercel.

Psuedo-code:
```
import { cookies } from 'next/headers'

export const runtime = 'edge'

export const POST = async (request: Request) => {
  const supabase = createRouteHandlerClient(
    { cookies },
    { supabaseKey: process.env.SUPABASE_SERVICE_ROLE_KEY }
  )

  await supabase.from( ...
```

```
{
  message: 'Error: Invariant: cookies() expects to have requestAsyncStorage, none available.',
  details: 'Error: Invariant: cookies() expects to have requestAsyncStorage, none available.\n    at (node_modules/next/dist/esm/client/components/headers.js:28:14)\n    at (node_modules/@supabase/auth-helpers-nextjs/dist/index.js:267:37)\n    at (node_modules/@supabase/auth-helpers-shared/dist/index.mjs:245:23)\n    at (node_modules/@supabase/gotrue-js/dist/module/lib/helpers.js:99:32)\n    at (node_modules/@supabase/gotrue-js/dist/module/GoTrueClient.js:729:39)\n    at (node_modules/@supabase/gotrue-js/dist/module/GoTrueClient.js:710:38)\n    at (node_modules/@supabase/gotrue-js/dist/module/GoTrueClient.js:639:24)\n    at (node_modules/@supabase/gotrue-js/dist/module/GoTrueClient.js:656:33)',
  hint: '',
  code: ''
}
```

**Comment by kirkstrobeck** [comment]
I built a test app with `npx create-next-app -e with-supabase` and it does not have the issue.

I tracked it down to my import of the server client, which I created to keep the app DRY

### Bad

```tsx
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';

const client = createServerComponentClient({ cookies });

export default client;
```

### Good

```tsx
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';

export default function base() {
  return createServerComponentClient({ cookies });
}
```

I had a similar issue on the client version of this a while back too, so modified that as well. Only change is now `supabase.from` is `supabase().from`
