### ISSUE TITLE
Vercel Supabase Integration with Multiple Vercel Projects

### ISSUE THREAD

**Issue by MildTomato** [supabase/supabase#18163]
### Discussed in https://github.com/orgs/supabase/discussions/17940

<div type='discussions-op-text'>

<sup>Originally posted by **robpetty** October  4, 2023</sup>
Has anyone stood up multiple projects with the Supabase Integration on Vercel successfully?  The error:

```
Error: either NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY env variables or supabaseUrl and supabaseKey are required!
    at (node_modules/@supabase/auth-helpers-nextjs/dist/index.js:193:10)
    at (middleware.ts:10:42)
    at (node_modules/next/dist/esm/server/web/adapter.js:163:22)
    at (node_modules/next/dist/esm/server/async-storage/request-async-storage-wrapper.js:72:23)
    at (node_modules/next/dist/esm/server/web/adapter.js:150:52)
```

The setup:

- Single account on Vercel (two apps from Github)
- Single org on Supabase (two projects in same org)
- Vercel Project A + Supabase Integration to original project in Supabase, WORKS FINE.
- Vercel Project B + Supabase Integration, FAILS.

The integration itself is setup for "All Projects".

I have not been able to find in the documentation how do you setup a second project pair using this integration. 

Locally Project B, with .env.local is working fine against Supabase Project B.

Project B was created with:
npx create-next-app@latest -e with-supabase project-b-app .

So currently rocking 13.5.4 Next.js if that matters.</div>

**Comment by kamilogorek** [comment]
As a workaround for now, you can trigger resync of env variables manually, which will unblock you and make everything work as expected.

<img width="689" alt="Screenshot 2023-10-13 at 12 12 02" src="https://github.com/supabase/supabase/assets/1523305/e3ef65e1-99aa-45c5-af1e-42b78be53308">

**Comment by MildTomato** [comment]
@robpetty [See @kamilogorek's comment above](https://github.com/supabase/supabase/issues/18163#issuecomment-1761266613)

**Comment by kamilogorek** [comment]
The fix is already available in production. Let us know if you still have any issues.

**Comment by dk-flpra** [comment]
I am facing the exact same issue now, and now I don't see any button to resync the env variables in supabase.

I have 2 projects and vercel-supabase works fine in first project but not in second project.

However, When I create a PR from github the preview branch gets the env vars in vercel but it gets removed once the PR is merged. But there is no persistent variables for prod branch in vercel.
