### ISSUE TITLE
auth/callback doc improvement to solve the url bug

### ISSUE THREAD

**Issue by Crayon-ShinChan** [supabase/supabase#18730]
# Improve documentation

## Link 

https://supabase.com/docs/guides/auth/server-side/oauth-with-pkce-flow-for-ssr#create-api-endpoint-for-handling-the-code-exchange

## Describe the problem

The code has bug, we can't pass the relative url in middleware, it should be the absolute path

```
 ⨯ Error: URL is malformed "/". Please use only absolute URLs - https://nextjs.org/docs/messages/middleware-relative-urls
    at validateURL (webpack-internal:///(rsc)/./node_modules/.pnpm/next@14.0.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/web/utils.js:119:15)
    at NextResponse.redirect (webpack-internal:///(rsc)/./node_modules/.pnpm/next@14.0.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/web/spec-extension/response.js:76:56)
    ... 2 lines matching cause stack trace ...
    at async /Users/leonz/Github/pulrent/node_modules/.pnpm/next@14.0.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:61856 {
  [cause]: TypeError: Invalid URL
      at new URL (node:internal/url:775:36)
      at validateURL (webpack-internal:///(rsc)/./node_modules/.pnpm/next@14.0.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/web/utils.js:117:23)
      at NextResponse.redirect (webpack-internal:///(rsc)/./node_modules/.pnpm/next@14.0.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/web/spec-extension/response.js:76:56)
      at GET (webpack-internal:///(rsc)/./app/auth/callback/route.ts:41:103)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /Users/leonz/Github/pulrent/node_modules/.pnpm/next@14.0.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:61856 {
    code: 'ERR_INVALID_URL',
    input: '/'
  }
}
```

## Describe the improvement

Write the code this way:
```tsx
import { cookies } from "next/headers";
import { NextResponse } from "next/server";
import { type CookieOptions, createServerClient } from "@supabase/ssr";

export async function GET(request: Request) {
  const { searchParams, origin } = new URL(request.url);
  const code = searchParams.get("code");
  // if "next" is in param, use it as the redirect URL
  const next = searchParams.get("next") ?? "/";

  if (code) {
    const cookieStore = cookies();
    const supabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      {
        cookies: {
          get(name: string) {
            return cookieStore.get(name)?.value;
          },
          set(name: string, value: string, options: CookieOptions) {
            cookieStore.set({ name, value, ...options });
          },
          remove(name: string, options: CookieOptions) {
            cookieStore.delete({ name, ...options });
          },
        },
      },
    );
    const { error } = await supabase.auth.exchangeCodeForSession(code);
    if (!error) {
      return NextResponse.redirect(`${origin}${next}`);
    }
  }

  // return the user to an error page with instructions
  return NextResponse.redirect(`${origin}/auth/auth-code-error`);
}
```

## Additional context

Add any other context or screenshots that help clarify your question.

**Comment by vinayakhegde1** [comment]
@Crayon-ShinChan I would like to work on this issue

**Comment by vinayakhegde1** [comment]
@Crayon-ShinChan I've created the PR please do check

**Comment by desiboli** [comment]
And this is the code that fixes it for handling token_hash, thank you @Crayon-ShinChan !

Should be updated in the docs here: [https://supabase.com/docs/guides/auth/server-side/email-based-auth-with-pkce-flow-for-ssr?framework=nextjs#create-api-endpoint-for-handling-tokenhash](Email Auth with PKCE flow for SSR)

```
import { cookies } from "next/headers"
import { NextResponse } from "next/server"
import { createServerClient, type CookieOptions } from "@supabase/ssr"
import { type EmailOtpType } from "@supabase/supabase-js"

export async function GET(request: Request) {
  const { searchParams, origin } = new URL(request.url)
  const token_hash = searchParams.get("token_hash")
  const type = searchParams.get("type") as EmailOtpType | null
  const next = searchParams.get("next") ?? "/"

  if (token_hash && type) {
    const cookieStore = cookies()
    const supabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      {
        cookies: {
          get(name: string) {
            return cookieStore.get(name)?.value
          },
          set(name: string, value: string, options: CookieOptions) {
            cookieStore.set({ name, value, ...options })
          },
          remove(name: string, options: CookieOptions) {
            cookieStore.delete({ name, ...options })
          },
        },
      }
    )

    const { error } = await supabase.auth.verifyOtp({
      type,
      token_hash,
    })
    if (!error) {
      return NextResponse.redirect(`${origin}${next}`)
    }
  }

  // return the user to an error page with some instructions
  return NextResponse.redirect(`${origin}/auth/auth-code-error`)
} 
```

**Comment by caio-truewind** [comment]
I understand this was closed, but I'm just wondering if I'm missing something, considering this seems to be a recent change. I'm using NextJS but I don't get a `code` in the `callback` route. I do get a JWT in the cookies, but if that was correct it would mean the docs were not up to date, and that I would have to manually send the token, for the client to get the session/user, which seems odd considering the docs. Am I missing something on this logic?
