### ISSUE TITLE
Realtime failing in local environment

### ISSUE THREAD

**Issue by johnborillo** [supabase/supabase#19183]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I want to do local testing with our remote supabase db, so I followed the instructions in these [supabase docs](https://supabase.com/docs/guides/cli/local-development). Whenever I link my project to our remote db using `supabase link --project-ref [reference id]`, then attempt to `supabase start`, I run into the following errors during health check:

```
[error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table and/or repository for managing migrations:

    config :realtime, Realtime.Repo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations

The full error report is shown below.

** (Postgrex.Error) ERROR 3F000 (invalid_schema_name) no schema has been selected to create in
    (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:932: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.14.3) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:1024: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.8.3) lib/ecto/migrator.ex:696: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.8.3) lib/ecto/migrator.ex:510: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.8.3) lib/ecto/migrator.ex:422: Ecto.Migrator.run/4
    (ecto_sql 3.8.3) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
    nofile:1: (file)
```

Additionally, I get problems with the public.ecr.aws/supabase/realtime image in Docker.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Currently using Supabase CLI 1.113.2
2. `supabase init` to initialize
3. `supabase link --project-ref [reference id]` and enter db password
4. `supabase start` then proceeds to download required Docker images
5. During health check, Supabase fails with provided error

## Expected behavior

When working on this last week, I was not encountering any errors, not problems during health check. Everything worked correctly

## System information

- OS: macOS Ventura
- Browser: Chrome
- Supabase CLI: 1.113.2

**Comment by Angus-Moore-Dev** [comment]
Even if you get it up and running, you cannot turn Realtime on for specific tables (mentioned [https://github.com/supabase/cli/issues/1684](as well in this GitHub issue)

**Comment by saltcod** [comment]
Hey @johnborillo — does this work with the latest release?

**Comment by johnborillo** [comment]
@saltcod I also spun up a new remote db on Supabase that's blank, linked it with `supabase link --project-ref [ref id]` and password and it worked normally. But whenever I attempt to link with our actual staging supabase, i get the errors.

In addition, `supabase start --ignore-health-check` does get the local environment running, but the realtime.dev.supabase_realtime docker image status keeps changing from Restarting to Running, then Restarting, then Running, then stays on Restarting. And btw, the provided errors above are logged from the realtime.dev.supabase_realtime docker image

**Comment by encima** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping us if it is still relevant, and we will happily reopen and it.
Cheers!
