### ISSUE TITLE
Unable to run supabase start - Reason: role "anon" already exists

### ISSUE THREAD

**Issue by joshsutheran-habitude** [supabase/supabase#20708]
### Discussed in https://github.com/orgs/supabase/discussions/20705

<div type='discussions-op-text'>

<sup>Originally posted by **joshsutheran-habitude** January 24, 2024</sup>
Unable to run supabase start from the CLI, as the aforementioned error is thrown: Reason: role "anon" already exists. 

Without being 100% sure, issue seems to have arisen following a failed attempt at running supabase db diff --schema storage, following the addition of a new bucket to our local project. 

Any guidance would be much appreciated</div>

**Comment by jenspots** [comment]
I'm running into the same issue with a fresh project.

```shell
$ supabase start
/app/dist/database/migrate.js:104
            const error = new Error(`Migration failed. Reason: ${e.message}`);
                          ^

Error: Migration failed. Reason: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
    at /app/dist/database/migrate.js:104:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/dist/database/migrate.js:149:28
    ... 2 lines matching cause stack trace ...
    at async /app/dist/scripts/migrate-call.js:10:5 {
  cause: Error: An error occurred running 'storage-schema'. Rolled back this migration. No further migrations were run. Reason: role "anon" already exists
      at /app/node_modules/postgres-migrations/dist/run-migration.js:36:15
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/dist/database/migrate.js:98:32
      at async /app/dist/database/migrate.js:149:28
      at async connectAndMigrate (/app/dist/database/migrate.js:48:9)
      at async runMigrationsOnTenant (/app/dist/database/migrate.js:35:5)
      at async /app/dist/scripts/migrate-call.js:10:5
}

Node.js v18.19.0
error running container: exit 1
Try rerunning the command with --debug to troubleshoot the error.
```

**Comment by jenspots** [comment]
I fixed this issue by removing `supabase/.branches` and `supabase/.temp`. I noticed there may have been an issue with Postgres `15.1.1`, since it rolled back to `15.1.0`, although it could've been an other incompatibility as well.

**Comment by joshsutheran-habitude** [comment]
Can confirm that this worked for me too - thanks for the suggestion! 👍

**Comment by amerryma** [comment]
Just FYI, the postgres image seems fine. The issue is actually within the storage api. If you have anything greater than v0.43.12 in your `supabase services` output, you'd likely run into the issue.

I fixed it by updating the storage image.

```sh
echo -n "v0.43.12" > supabase/.temp/storage-version
```

**Comment by aleciavogel** [comment]
> Just FYI, the postgres image seems fine. The issue is actually within the storage api. If you have anything greater than v0.43.12 in your `supabase services` output, you'd likely run into the issue.
> 
> I fixed it by updating the storage image.
> 
> ```shell
> echo -n "v0.43.12" > supabase/.temp/storage-version
> ```
> 
> Note, if you run `supabase link`, and your hosted system has an updated storage-api it will overwrite it and break again.

@amerryma deleting `.temp` did nothing but your shell command worked! Thank you for this

**Comment by encima** [comment]
Thanks for reporting this and thanks community folks for the workarounds, will leave this open as it seems to be affecting latest versions of the Storage, locally and in cloud

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
