### ISSUE TITLE
Auth docs now out of sync with supabase auth PKCE flows (which throw errors instead of returning)

### ISSUE THREAD

**Issue by fnimick** [supabase/supabase#20703]
# Bug report

I'm not sure at what point this happened, but my implementation of the server side PKCE flows has started throwing errors instead of returning the error, as indicated in the docs. It used to work with the error return (as of ~2 months ago).

See docs here: https://supabase.com/docs/guides/auth/server-side/oauth-with-pkce-flow-for-ssr

When either the auth code or code verifier is missing, `const { error } = await supabase.auth.exchangeCodeForSession(code)` now throws an error instead of returning, which means the checks for the error return value as illustrated in the docs no longer work.

This is an example of an error that is now thrown instead of returned:
```
AuthApiError: invalid request: both auth code and code verifier should be non-empty
    at handleError (<repository>/node_modules/@supabase/gotrue-js/dist/main/lib/fetch.js:43:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _handleRequest (<repository>/node_modules/@supabase/gotrue-js/dist/main/lib/fetch.js:81:9)
    at async _request (<repository>/node_modules/@supabase/gotrue-js/dist/main/lib/fetch.js:65:18)
    at async SupabaseAuthClient._exchangeCodeForSession (<repository>/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:374:33)
```

**Comment by charislam** [comment]
Thanks for the report! As far as I'm aware, the intention is _not_ for it to throw. It must be happening in GoTrue, and there seems to be an [issue open](https://github.com/supabase/gotrue-js/issues/782) there, so I'm going to close this one as a duplicate
