### ISSUE TITLE
Problem with file uploads in Windows environment using Supabase storage

### ISSUE THREAD

**Issue by mlix8hoblc** [supabase/supabase#20778]
Hello,

I hope this message finds you well. I'm reaching out because I've run into a rather puzzling issue with file uploads in Supabase storage, specifically when working from a Windows environment.

In short, whenever I try to upload files – be it through my application that utilizes Supabase or directly via the Supabase dashboard – I encounter a database constraint violation error. This is happening exclusively on Windows, as the same process seems to work just fine on macOS.

The core of the error is a PostgreSQL database constraint violation, pointing out that there's a 'null value in column "url" of relation "http_request_queue" which violates the not-null constraint'. This leads me to believe that there might be an underlying issue with how file uploads are handled in the backend, particularly on Windows.

To reproduce the issue, I simply attempt to upload any file to Supabase storage, either through the dashboard or my application, while operating on a Windows system. The error then pops up in the database logs.

```
2024-01-26 13:10:31 172.19.0.10 2024-01-26 12:10:31.071 UTC [723] supabase_storage_admin@postgres ERROR:  null value in column "url" of relation "http_request_queue" violates not-null constraint
```

```
2024-01-26 13:10:31 172.19.0.10 2024-01-26 12:10:31.071 UTC [723] supabase_storage_admin@postgres DETAIL:  Failing row contains (4, POST, null, {"Content-Type": "application/json", "Authorization": "Bearer ey..., \x7b22646f63756d656e745f6964223a2031337d, 2000).
```

```
2024-01-26 14:20:48 {"level":30,"time":"2024-01-26T13:20:48.856Z","pid":1,"hostname":"67fb8208f858","reqId":"req-fe","tenantId":"stub","project":"stub","reqId":"req-fe","type":"request","req":{"traceId":"req-fe","method":"POST","url":"/object/files/d7cb63c9-caec-489d-9fe9-db29139988f6/user-guide-nokia-1-4-user-guide.pdf","headers":{"host":"supabase_storage_echobase:5000","x_forwarded_proto":"http","x_forwarded_host":"127.0.0.1","x_forwarded_port":"8000","x_real_ip":"172.19.0.1","content_length":"401103","x_client_info":"@supabase/auth-helpers-nextjs@0.8.7","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","x_upsert":"false","content_type":"multipart/form-data; boundary=----WebKitFormBoundary4XIQ5jlwnUpJ3xqS","accept":"*/*","referer":"http://localhost:3000/"},"hostname":"supabase_storage_echobase:5000","remoteAddress":"172.19.0.5","remotePort":34186},"res":{"statusCode":400,"headers":{"content_type":"application/json; charset=utf-8","content_length":"73"}},"responseTime":47.16412699967623,"error":{"raw":"{\"statusCode\":500,\"error\":\"internal\",\"originalError\":{\"length\":1164,\"name\":\"error\",\"severity\":\"ERROR\",\"code\":\"23502\",\"detail\":\"Failing row contains (8, POST, null, {\\\"Content-Type\\\": \\\"application/json\\\", \\\"Authorization\\\": \\\"Bearer ey..., \\\\x7b22646f63756d656e745f6964223a2032327d, 2000).\",\"where\":\"SQL statement \\\"insert into net.http_request_queue(method, url, headers, body, timeout_milliseconds)\\n    values (\\n        'POST',\\n        net._encode_url_with_params_array(url, params_array),\\n        headers,\\n        convert_to(body::text, 'UTF8'),\\n        timeout_milliseconds\\n    )\\n    returning id\\\"\\nPL/pgSQL function http_post(text,jsonb,jsonb,jsonb,integer) line 37 at SQL statement\\nSQL statement \\\"select\\r\\n    net.http_post(\\r\\n      url := supabase_url() || '/functions/v1/process',\\r\\n      headers := jsonb_build_object(\\r\\n        'Content-Type', 'application/json',\\r\\n        'Authorization', current_setting('request.headers')::json->>'authorization'\\r\\n      ),\\r\\n      body := jsonb_build_object(\\r\\n        'document_id', document_id\\r\\n      )\\r\\n    )\\\"\\nPL/pgSQL function private.handle_storage_update() line 10 at SQL statement\",\"schema\":\"net\",\"table\":\"http_request_queue\",\"column\":\"url\",\"file\":\"execMain.c\",\"line\":\"1968\",\"routine\":\"ExecConstraints\"}}","name":"Error","message":"Internal Server Error","stack":"Error: Internal Server Error\n    at DBError.fromDBError (/app/dist/storage/database/knex.js:443:16)\n    at Function.<anonymous> (/app/dist/storage/database/knex.js:25:39)\n    at Object.onceWrapper (node:events:632:26)\n    at Function.emit (node:events:517:28)\n    at Function.emit (node:domain:489:12)\n    at Client_PG.<anonymous> (/app/node_modules/knex/lib/knex-builder/make-knex.js:299:10)\n    at Client_PG.emit (node:events:529:35)\n    at Client_PG.emit (node:domain:489:12)\n    at /app/node_modules/knex/lib/execution/internal/query-executioner.js:46:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"owner":"d4b2c94c-2901-4fb4-883c-b652bff042ab","msg":"stub | POST | 400 | 172.19.0.5 | req-fe | /object/files/d7cb63c9-caec-489d-9fe9-db29139988f6/user-guide-nokia-1-4-user-guide.pdf | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}
```

Additionally, I've noticed specific error codes that might be crucial in diagnosing the problem. When attempting the file upload, the server responds with a status code of 400 (Bad Request), which is visible in the network logs. More intriguingly, within the details of this response, there's an indication of an internal server error, marked by an error code 500. This seems to occur in the backend processing of the upload request. The presence of these error codes, especially the 500, suggests that the issue might be more complex, involving internal server processes or configurations that differ between Windows and macOS environments.

I'd really appreciate any insights or guidance you could provide on this matter. It's a crucial part of our application, and this hiccup is especially challenging for our Windows-based users.

Thanks a lot for your time and help!

_Edit:_ Issue generated by ChatGPT.

**Comment by encima** [comment]
Thanks for this, it looks like the path is not included for some reason or the URL is not handled.

If you have a code snippet and/or any non-sensitive ENV vars you are using can you please add them here. 

To confirm, this does not happen in the hosted environment?

**Comment by kevinamick** [comment]
I'm experiencing the same issue on windows as well using wsl2. I've dialed the issue down to this stored procedure:

```
create function private.handle_storage_update() 
returns trigger 
language plpgsql
as $$
declare
  document_id bigint;
  result int;
begin
  insert into documents (name, storage_object_id, created_by)
    values (new.path_tokens[2], new.id, new.owner)
    returning id into document_id;
    
  select
    net.http_post(
      url := supabase_url() || '/functions/v1/process',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'Authorization', current_setting('request.headers')::json->>'authorization'
      ),
      body := jsonb_build_object(
        'document_id', document_id
      )
    )
  into result;

  return null;
end;
$$;
```

After removing this, the upload works fine. Seeing as @mlix8hoblc and I both are using pg_net, the issue may be around the use of this extension?

**Comment by kevinamick** [comment]
And literally right after posting the above I found my issue. Was missing a column with not null constraint. @mlix8hoblc check if you're inserting into your table properly in your stored procedure.

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.

**Comment by isley-griffith** [comment]
Having the same error. Mac M1 Max.

Cloned this repo and tried to run on the main branch:
https://github.com/supabase-community/chatgpt-your-files

I put in the necessary env variables and ran `npx supabase db push` as well after linking.

@kevinamick, did you happen to clone this same repo? I recognize that postgres function. Thank you in advance.
