### ISSUE TITLE
Unable to Connect Storage Container on Development

### ISSUE THREAD

**Issue by francistogram** [supabase/supabase#20873]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
This started happening only recently where I'm unable to connect to the Storage container and running `npx supabase start` gives this error
```
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
/app/node_modules/postgres-migrations/dist/migrate.js:100
            const error = new Error(`Migration failed. Reason: ${e.message}`);
                          ^

Error: Migration failed. Reason: Hashes don't match for migrations '0002-pathtoken-column.sql,0003-add-migrations-rls.sql,0004-add-size-functions.sql,0005-change-column-name-in-get-size.sql,0006-add-rls-to-buckets.sql,0007-add-public-to-buckets.sql,0008-fix-search-function.sql,0009-search-files-search-function.sql,0010-add-trigger-to-auto-update-updated_at-column.sql,0011-add-automatic-avif-detection-flag.sql,0012-add-bucket-custom-limits.sql,0013-use-bytes-for-max-size.sql,0014-add-can-insert-object-function.sql,0015-add-version.sql,0016-drop-owner-foreign-key.sql,0017-add_owner_id_column_deprecate_owner.sql'.
This means that the scripts have changed since it was applied.
    at /app/node_modules/postgres-migrations/dist/migrate.js:100:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    ... 3 lines matching cause stack trace ...
    at async /app/dist/server.js:22:9 {
```

## To Reproduce

My process for development is
1. `npx supabase start`, I'm currently on version 1.136.3
2. I pull the database locally `pg_dump -Fc postgresql://postgres:[PASSWORD]@db.[PROJECT_ID].supabase.co:5432/postgres > db.dump && pg_restore --clean --if-exists -d postgresql://postgres:postgres@localhost:54322/postgres db.dump`

Now what's been happening as of yesterday is after doing those two things I get some issues with the Storage container and it gets stuck in this restarting state
![image](https://github.com/supabase/supabase/assets/3721449/4faf6b00-6817-4f55-aa3a-fe42d825e69b)

until it finally errors after a few retries and gives this eror
<img width="584" alt="image" src="https://github.com/supabase/supabase/assets/3721449/ccb029fe-0f64-4241-a150-c86398050b01">

One thing I have noticed is that the migrations it's complaining about are within the `storage` schema within the `migrations` table and everything was created only recently on 1/24/24
<img width="1728" alt="image" src="https://github.com/supabase/supabase/assets/3721449/0053e81e-707c-4a5d-a07b-be1dcc67265f">

Seems like maybe there's a step I'm missing here to keep things in sync?

## System information

- OS: macOS
- Version of supabase-js: 2.1.1
- Version of Node.js: 21.4.0

**Comment by encima** [comment]
Hi @francistogram 

Thanks for opening. You pull the database using PG CLI tools (which is fine!), can you confirm if this happens when you use the Supabase CLI?

For example:
1. New local Supabase project
2. `supabase start`
3. `supabase link`
4. `supabase db pull`

See [here](https://supabase.com/docs/reference/cli/supabase-db-pull) for details on the commands.

**Comment by francistogram** [comment]
So I was playing around with `supabase db pull` and tried with `--dry-run` and noticed that there was `--exclude-table=storage.migrations` included and adding that to my `pg_dump` script ended up fixing my issue

**Comment by Phil9l** [comment]
For me it's failing with a similar error.
```
climbest-supabase-storage-1    | (node:1) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
climbest-supabase-storage-1    |
climbest-supabase-storage-1    | Please migrate your code to use AWS SDK for JavaScript (v3).
climbest-supabase-storage-1    | For more information, check the migration guide at https://a.co/7PzMCcy
climbest-supabase-storage-1    | (Use `node --trace-warnings ...` to show where the warning was created)
climbest-supabase-storage-1    | /app/node_modules/postgres-migrations/dist/migrate.js:100
climbest-supabase-storage-1    |             const error = new Error(`Migration failed. Reason: ${e.message}`);
climbest-supabase-storage-1    |                           ^
climbest-supabase-storage-1    |
climbest-supabase-storage-1    | Error: Migration failed. Reason: Hashes don't match for migrations '0002-pathtoken-column.sql,0003-add-migrations-rls.sql,0004-add-size-functions.sql,0005-change-column-name-in-get-size.sql,0006-add-rls-to-buckets.sql,0007-add-public-to-buckets.sql,0008-fix-search-function.sql,0009-search-files-search-function.sql,0010-add-trigger-to-auto-update-updated_at-column.sql,0011-add-automatic-avif-detection-flag.sql,0012-add-bucket-custom-limits.sql,0013-use-bytes-for-max-size.sql,0014-add-can-insert-object-function.sql,0015-add-version.sql,0016-drop-owner-foreign-key.sql,0017-add_owner_id_column_deprecate_owner.sql'.
climbest-supabase-storage-1    | This means that the scripts have changed since it was applied.
climbest-supabase-storage-1    |     at /app/node_modules/postgres-migrations/dist/migrate.js:100:27
climbest-supabase-storage-1    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
climbest-supabase-storage-1    |     ... 3 lines matching cause stack trace ...
climbest-supabase-storage-1    |     at async /app/dist/server.js:22:9 {
climbest-supabase-storage-1    |   cause: Error: Hashes don't match for migrations '0002-pathtoken-column.sql,0003-add-migrations-rls.sql,0004-add-size-functions.sql,0005-change-column-name-in-get-size.sql,0006-add-rls-to-buckets.sql,0007-add-public-to-buckets.sql,0008-fix-search-function.sql,0009-search-files-search-function.sql,0010-add-trigger-to-auto-update-updated_at-column.sql,0011-add-automatic-avif-detection-flag.sql,0012-add-bucket-custom-limits.sql,0013-use-bytes-for-max-size.sql,0014-add-can-insert-object-function.sql,0015-add-version.sql,0016-drop-owner-foreign-key.sql,0017-add_owner_id_column_deprecate_owner.sql'.
climbest-supabase-storage-1    |   This means that the scripts have changed since it was applied.
climbest-supabase-storage-1    |       at Object.validateMigrationHashes (/app/node_modules/postgres-migrations/dist/validation.js:24:15)
climbest-supabase-storage-1    |       at /app/node_modules/postgres-migrations/dist/migrate.js:86:26
climbest-supabase-storage-1    |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
climbest-supabase-storage-1    |       at async /app/node_modules/postgres-migrations/dist/with-lock.js:25:28
climbest-supabase-storage-1    |       at async connectAndMigrate (/app/dist/database/migrate.js:42:9)
climbest-supabase-storage-1    |       at async runMigrations (/app/dist/database/migrate.js:14:5)
climbest-supabase-storage-1    |       at async /app/dist/server.js:22:9
climbest-supabase-storage-1    | }
climbest-supabase-storage-1    |
climbest-supabase-storage-1    | Node.js v18.18.2
climbest-supabase-storage-1    | running migrations
climbest-supabase-storage-1    | (node:1) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
climbest-supabase-storage-1    |
climbest-supabase-storage-1    | Please migrate your code to use AWS SDK for JavaScript (v3).
climbest-supabase-storage-1    | For more information, check the migration guide at https://a.co/7PzMCcy
climbest-supabase-storage-1    | (Use `node --trace-warnings ...` to show where the warning was created)
climbest-supabase-storage-1    | /app/node_modules/postgres-migrations/dist/migrate.js:100
climbest-supabase-storage-1    |             const error = new Error(`Migration failed. Reason: ${e.message}`);
```

I'm running supabase with `docker compose down && docker compose -f docker-compose.yml -f docker-compose.s3.yml up --build -d`. How can I fix this issue?

**Comment by encima** [comment]
Will verify this locally.

**Comment by Phil9l** [comment]
@encima , thanks, I actually resolved it by bumping storage to the newest version (newer than the current one in master).

```
$ grep "supabase/storage-api" docker-compose.s3.yml
    image: supabase/storage-api:v0.48.1
```

Everything started working out of the box, no additional setup was needed.

**Comment by encima** [comment]
The storage container will be updated soon so will close this for now. Thanks for posting the resolution!
