### ISSUE TITLE
services cant write custom postges database in docker compose

### ISSUE THREAD

**Issue by LazerJesus** [supabase/supabase#20906]
### Discussed in https://github.com/orgs/supabase/discussions/20904

<div type='discussions-op-text'>

<sup>Originally posted by **LazerJesus** January 31, 2024</sup>
hey, i got a custom setup and am running into problems.

the setup goes like this.
there is a `docker-compose.yml` file that contains my app and a postgres container `postgres` with an existing database `app_com_spanish`
they are running & purring :cat2: 

now i want to add supabase.
for this i copied the `docker-compose.supabase.yml` & `.env.supabase` file from github.

i run
`docker compose --env-file .env.supabase -f docker-compose.supabase.yml up`

studio, meta, and kong are up and running. analytics, rest, auth, functions, realtime, storage, and imageproxy have issues.
the common theme is that they cant write postgres.  

`analytics`:
```
supabase-analytics  | LOGFLARE_NODE_HOST is: 127.0.0.1
supabase-analytics  |
supabase-analytics  | 18:01:05.967 [info] Starting migration
supabase-analytics  |
supabase-analytics  | 18:01:06.529 [error] Could not create schema migrations table. This error usually happens due to the following:
supabase-analytics  |
supabase-analytics  |   * The database does not exist
supabase-analytics  |   * The "schema_migrations" table, which Ecto uses for managing
supabase-analytics  |     migrations, was defined by another library
supabase-analytics  |   * There is a deadlock while migrating (such as using concurrent
supabase-analytics  |     indexes with a migration_lock)
supabase-analytics  |
supabase-analytics  | To fix the first issue, run "mix ecto.create" for the desired MIX_ENV.
supabase-analytics  |
supabase-analytics  | To address the second, you can run "mix ecto.drop" followed by
supabase-analytics  | "mix ecto.create", both for the desired MIX_ENV. Alternatively you may
supabase-analytics  | configure Ecto to use another table and/or repository for managing
supabase-analytics  | migrations:
supabase-analytics  |
supabase-analytics  |     config :logflare, Logflare.Repo,
supabase-analytics  |       migration_source: "some_other_table_for_schema_migrations",
supabase-analytics  |       migration_repo: AnotherRepoForSchemaMigrations
supabase-analytics  |
supabase-analytics  | The full error report is shown below.
supabase-analytics  |
supabase-analytics  | ** (Postgrex.Error) ERROR 3F000 (invalid_schema_name) no schema has been selected to create in
supabase-analytics  |     (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
supabase-analytics  |     (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
supabase-analytics  |     (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
supabase-analytics  |     (ecto_sql 3.10.1) lib/ecto/migrator.ex:738: Ecto.Migrator.verbose_schema_migration/3
supabase-analytics  |     (ecto_sql 3.10.1) lib/ecto/migrator.ex:552: Ecto.Migrator.lock_for_migrations/4
supabase-analytics  |     (ecto_sql 3.10.1) lib/ecto/migrator.ex:428: Ecto.Migrator.run/4
supabase-analytics  |     (ecto_sql 3.10.1) lib/ecto/migrator.ex:170: Ecto.Migrator.with_repo/3
supabase-analytics  |     nofile:1: (file)
supabase-analytics  |
supabase-analytics  | 18:01:12.542 [notice]     :alarm_handler: {:set, {:system_memory_high_watermark, []}}
supabase-analytics  |
supabase-analytics  | 18:01:12.658 [info] Elixir.Logflare.SigtermHandler is being initialized...
supabase-analytics  |
supabase-analytics  | 18:01:12.782 [info] Table counters started!
supabase-analytics  |
supabase-analytics  | 18:01:12.783 [info] Rate counter table started!
supabase-analytics  |
supabase-analytics  | 18:01:12.787 [info] Going Down - {%Postgrex.Error{message: nil, postgres: %{code: :undefined_table, file: "parse_relation.c", line: "1449", message: "relation \"sources\" does not exist", pg_code: "42P01", position: "480", routine: "parserOpenTable", severity: "ERROR", unknown: "ERROR"}, connection_id: 1900, query: "SELECT s0.\"id\", s0.\"name\", s0.\"token\", s0.\"public_token\", s0.\"favorite\", s0.\"bigquery_table_ttl\", s0.\"api_quota\", s0.\"webhook_notification_url\", s0.\"slack_hook_url\", s0.\"bq_table_partition_type\", s0.\"custom_event_message_keys\", s0.\"log_events_updated_at\", s0.\"notifications_every\", s0.\"lock_schema\", s0.\"validate_schema\", s0.\"drop_lql_filters\", s0.\"drop_lql_string\", s0.\"v2_pipeline\", s0.\"suggested_keys\", s0.\"user_id\", s0.\"notifications\", s0.\"inserted_at\", s0.\"updated_at\" FROM \"sources\" AS s0 WHERE (s0.\"log_events_updated_at\" > $1) ORDER BY s0.\"log_events_updated_at\""}, [{Ecto.Adapters.SQL, :raise_sql_call_error, 1, [file: 'lib/ecto/adapters/sql.ex', line: 913, error_info: %{module: Exception}]}, {Ecto.Adapters.SQL, :execute, 6, [file: 'lib/ecto/adapters/sql.ex', line: 828]}, {Ecto.Repo.Queryable, :execute, 4, [file: 'lib/ecto/repo/queryable.ex', line: 229]}, {Ecto.Repo.Queryable, :all, 3, [file: 'lib/ecto/repo/queryable.ex', line: 19]}, {Logflare.Source.Supervisor, :handle_continue, 2, [file: 'lib/logflare/source/supervisor.ex', line: 52]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 1123]}, {:gen_server, :loop, 7, [file: 'gen_server.erl', line: 865]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]} - Elixir.Logflare.Source.Supervisor
supabase-analytics  |
supabase-analytics  | 18:01:12.788 [error] GenServer Logflare.Source.Supervisor terminating
supabase-analytics  | ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "sources" does not exist
supabase-analytics  |
supabase-analytics  |     query: SELECT s0."id", s0."name", s0."token", s0."public_token", s0."favorite", s0."bigquery_table_ttl", s0."api_quota", s0."webhook_notification_url", s0."slack_hook_url", s0."bq_table_partition_type", s0."custom_event_message_keys", s0."log_events_updated_at", s0."notifications_every", s0."lock_schema", s0."validate_schema", s0."drop_lql_filters", s0."drop_lql_string", s0."v2_pipeline", s0."suggested_keys", s0."user_id", s0."notifications", s0."inserted_at", s0."updated_at" FROM "sources" AS s0 WHERE (s0."log_events_updated_at" > $1) ORDER BY s0."log_events_updated_at"
supabase-analytics  |     (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
supabase-analytics  |     (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:828: Ecto.Adapters.SQL.execute/6
supabase-analytics  |     (ecto 3.10.3) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
supabase-analytics  |     (ecto 3.10.3) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
supabase-analytics  |     (logflare 1.4.0) lib/logflare/source/supervisor.ex:52: Logflare.Source.Supervisor.handle_continue/2
supabase-analytics  |     (stdlib 4.3.1) gen_server.erl:1123: :gen_server.try_dispatch/4
supabase-analytics  |     (stdlib 4.3.1) gen_server.erl:865: :gen_server.loop/7
supabase-analytics  |     (stdlib 4.3.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
supabase-analytics  | Last message: {:continue, :boot}
supabase-analytics  |
supabase-analytics  | 18:01:12.790 [info] Running LogflareWeb.Endpoint with cowboy 2.10.0 at 0.0.0.0:4000 (http)
supabase-analytics  |
supabase-analytics  | 18:01:12.792 [info] Access LogflareWeb.Endpoint at http://localhost:4000
supabase-analytics  |
supabase-analytics  | 18:01:12.793 [info] Running LogflareGrpc.Endpoint with Cowboy using http://0.0.0.0:50051
supabase-analytics  |
supabase-analytics  | 18:01:12.804 [notice] Application logflare exited: Logflare.Application.start(:normal, []) returned an error: shutdown: failed to start child: Logflare.SystemMetricsSup
supabase-analytics  |     ** (EXIT) shutdown: failed to start child: Logflare.SystemMetrics.AllLogsLogged
supabase-analytics  |         ** (EXIT) an exception was raised:
supabase-analytics  |             ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "system_metrics" does not exist
supabase-analytics  |
supabase-analytics  |     query: SELECT s0."id", s0."all_logs_logged", s0."node", s0."inserted_at", s0."updated_at" FROM "system_metrics" AS s0 WHERE (s0."node" = $1)
supabase-analytics  |                 (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
supabase-analytics  |                 (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:828: Ecto.Adapters.SQL.execute/6
supabase-analytics  |                 (ecto 3.10.3) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
supabase-analytics  |                 (ecto 3.10.3) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
supabase-analytics  |                 (ecto 3.10.3) lib/ecto/repo/queryable.ex:151: Ecto.Repo.Queryable.one/3
supabase-analytics  |                 (logflare 1.4.0) lib/logflare/system_metrics/all_logs_logged/all_logs_logged.ex:20: Logflare.SystemMetrics.AllLogsLogged.init/1
supabase-analytics  |                 (stdlib 4.3.1) gen_server.erl:851: :gen_server.init_it/2
supabase-analytics  |                 (stdlib 4.3.1) gen_server.erl:814: :gen_server.init_it/6
supabase-analytics  |
supabase-analytics  | 18:01:12.849 [notice]     :alarm_handler: {:clear, :system_memory_high_watermark}
supabase-analytics  | {"Kernel pid terminated",application_controller,"{application_start_failure,logflare,{{shutdown,{failed_to_start_child,'Elixir.Logflare.SystemMetricsSup',{shutdown,{failed_to_start_child,'Elixir.Logflare.SystemMetrics.AllLogsLogged',{#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 1906,message => nil,postgres => #{code => undefined_table,file => <<\"parse_relation.c\">>,line => <<\"1449\">>,message => <<\"relation \\"system_metrics\\" does not exist\">>,pg_code => <<\"42P01\">>,position => <<\"89\">>,routine => <<\"parserOpenTable\">>,severity => <<\"ERROR\">>,unknown => <<\"ERROR\">>},query => <<\"SELECT s0.\\"id\\", s0.\\"all_logs_logged\\", s0.\\"node\\", s0.\\"inserted_at\\", s0.\\"updated_at\\" FROM \\"system_metrics\\" AS s0 WHERE (s0.\\"node\\" = $1)\">>},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,\"lib/ecto/adapters/sql.ex\"},{line,913},{error_info,#{module => 'Elixir.Exception'}}]},{'Elixir.Ecto.Adapters.SQL',execute,6,[{file,\"lib/ecto/adapters/sql.ex\"},{line,828}]},{'Elixir.Ecto.Repo.Queryable',execute,4,[{file,\"lib/ecto/repo/queryable.ex\"},{line,229}]},{'Elixir.Ecto.Repo.Queryable',all,3,[{file,\"lib/ecto/repo/queryable.ex\"},{line,19}]},{'Elixir.Ecto.Repo.Queryable',one,3,[{file,\"lib/ecto/repo/queryable.ex\"},{line,151}]},{'Elixir.Logflare.SystemMetrics.AllLogsLogged',init,1,[{file,\"lib/logflare/system_metrics/all_logs_logged/all_logs_logged.ex\"},{line,20}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,851}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,814}]}]}}}}},{'Elixir.Logflare.Application',start,[normal,[]]}}}"}
supabase-analytics  | Kernel pid terminated (application_controller) ({application_start_failure,logflare,{{shutdown,{failed_to_start_child,'Elixir.Logflare.SystemMetricsSup',{shutdown,{failed_to_start_child,'Elixir.Logflare.SystemMetrics.AllLogsLogged',{#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 1906,message => nil,postgres => #{code => undefined_table,file => <<"parse_relation.c">>,line => <<"1449">>,message => <<"relation \"system_metrics\" does not exist">>,pg_code => <<"42P01">>,position => <<"89">>,routine => <<"parserOpenTable">>,severity => <<"ERROR">>,unknown => <<"ERROR">>},query => <<"SELECT s0.\"id\", s0.\"all_logs_logged\", s0.\"node\", s0.\"inserted_at\", s0.\"updated_at\" FROM \"system_metrics\" AS s0 WHERE (s0.\"node\" = $1)">>},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,"lib/ecto/adapters/sql.ex"},{line,913},{error_info,#{module => 'Elixir.Exception'}}]},{'Elixir.Ecto.Adapters.SQL',execute,6,[{file,"lib/ecto/adapters/sql.ex"},{line,828}]},{'Elixir.Ecto.Repo.
supabase-analytics  |
supabase-analytics  | Crash dump is being written to: erl_crash.dump...done
```

`supabase-rest`:
```
supabase-rest  | 31/Jan/2024:17:59:38 +0000: Starting PostgREST 12.0.1...
supabase-rest  | 31/Jan/2024:17:59:38 +0000: Attempting to connect to the database...
supabase-rest  | 31/Jan/2024:17:59:43 +0000: {"code":"PGRST000","details":"could not translate host name \"postgres\" to address: Try again\n","hint":null,"message":"Database connection error. Retrying the connection."}
```

`auth`:
```
supabase-auth  | {"level":"info","msg":"Go runtime metrics collection started","time":"2024-01-31T18:02:18Z"}
supabase-auth  | {"args":[0.024475808],"component":"pop","level":"info","msg":"%.4f seconds","time":"2024-01-31T18:02:18Z"}
supabase-auth  | {"level":"fatal","msg":"running db migrations: error executing /usr/local/etc/auth/migrations/00_init_auth_schema.up.sql, sql: -- auth.users definition\n\nCREATE TABLE IF NOT EXISTS auth.users (\n\tinstance_id uuid NULL,\n\tid uuid NOT NULL UNIQUE,\n\taud varchar(255) NULL,\n\t\"role\" varchar(255) NULL,\n\temail varchar(255) NULL UNIQUE,\n\tencrypted_password varchar(255) NULL,\n\tconfirmed_at timestamptz NULL,\n\tinvited_at timestamptz NULL,\n\tconfirmation_token varchar(255) NULL,\n\tconfirmation_sent_at timestamptz NULL,\n\trecovery_token varchar(255) NULL,\n\trecovery_sent_at timestamptz NULL,\n\temail_change_token varchar(255) NULL,\n\temail_change varchar(255) NULL,\n\temail_change_sent_at timestamptz NULL,\n\tlast_sign_in_at timestamptz NULL,\n\traw_app_meta_data jsonb NULL,\n\traw_user_meta_data jsonb NULL,\n\tis_super_admin bool NULL,\n\tcreated_at timestamptz NULL,\n\tupdated_at timestamptz NULL,\n\tCONSTRAINT users_pkey PRIMARY KEY (id)\n);\nCREATE INDEX IF NOT EXISTS users_instance_id_email_idx ON auth.users USING btree (instance_id, email);\nCREATE INDEX IF NOT EXISTS users_instance_id_idx ON auth.users USING btree (instance_id);\ncomment on table auth.users is 'Auth: Stores user login data within a secure schema.';\n\n-- auth.refresh_tokens definition\n\nCREATE TABLE IF NOT EXISTS auth.refresh_tokens (\n\tinstance_id uuid NULL,\n\tid bigserial NOT NULL,\n\t\"token\" varchar(255) NULL,\n\tuser_id varchar(255) NULL,\n\trevoked bool NULL,\n\tcreated_at timestamptz NULL,\n\tupdated_at timestamptz NULL,\n\tCONSTRAINT refresh_tokens_pkey PRIMARY KEY (id)\n);\nCREATE INDEX IF NOT EXISTS refresh_tokens_instance_id_idx ON auth.refresh_tokens USING btree (instance_id);\nCREATE INDEX IF NOT EXISTS refresh_tokens_instance_id_user_id_idx ON auth.refresh_tokens USING btree (instance_id, user_id);\nCREATE INDEX IF NOT EXISTS refresh_tokens_token_idx ON auth.refresh_tokens USING btree (token);\ncomment on table auth.refresh_tokens is 'Auth: Store of tokens used to refresh JWT tokens once they expire.';\n\n-- auth.instances definition\n\nCREATE TABLE IF NOT EXISTS auth.instances (\n\tid uuid NOT NULL,\n\tuuid uuid NULL,\n\traw_base_config text NULL,\n\tcreated_at timestamptz NULL,\n\tupdated_at timestamptz NULL,\n\tCONSTRAINT instances_pkey PRIMARY KEY (id)\n);\ncomment on table auth.instances is 'Auth: Manages users across multiple sites.';\n\n-- auth.audit_log_entries definition\n\nCREATE TABLE IF NOT EXISTS auth.audit_log_entries (\n\tinstance_id uuid NULL,\n\tid uuid NOT NULL,\n\tpayload json NULL,\n\tcreated_at timestamptz NULL,\n\tCONSTRAINT audit_log_entries_pkey PRIMARY KEY (id)\n);\nCREATE INDEX IF NOT EXISTS audit_logs_instance_id_idx ON auth.audit_log_entries USING btree (instance_id);\ncomment on table auth.audit_log_entries is 'Auth: Audit trail for user actions.';\n\n-- auth.schema_migrations definition\n\nCREATE TABLE IF NOT EXISTS auth.schema_migrations (\n\t\"version\" varchar(255) NOT NULL,\n\tCONSTRAINT schema_migrations_pkey PRIMARY KEY (\"version\")\n);\ncomment on table auth.schema_migrations is 'Auth: Manages updates to the auth system.';\n\t\t\n-- Gets the User ID from the request cookie\ncreate or replace function auth.uid() returns uuid as $$\n  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid;\n$$ language sql stable;\n\n-- Gets the User ID from the request cookie\ncreate or replace function auth.role() returns text as $$\n  select nullif(current_setting('request.jwt.claim.role', true), '')::text;\n$$ language sql stable;\n: ERROR: schema \"auth\" does not exist (SQLSTATE 3F000)","time":"2024-01-31T18:02:18Z"}
```

`studio` is running and can acessible from the browser. but marked `unhealthy` by docker.
```
root@app:/opt/server# docker compose --env-file .env.supabase -f docker-compose.supabase.yml up studio
[+] Running 1/0
 ✔ Container supabase-studio  Created                                                                                                                       0.0s
Attaching to supabase-studio
supabase-studio  |  ⨯ Failed to load env from /app/apps/studio/.env TypeError: Cannot read properties of undefined (reading 'split')
supabase-studio  |     at /app/node_modules/@next/env/dist/index.js:1:311
supabase-studio  |     at Array.reduce (<anonymous>)
supabase-studio  |     at _interpolate (/app/node_modules/@next/env/dist/index.js:1:125)
supabase-studio  |     at expand (/app/node_modules/@next/env/dist/index.js:1:709)
supabase-studio  |     at processEnv (/app/node_modules/@next/env/dist/index.js:1:4057)
supabase-studio  |     at loadEnvConfig (/app/node_modules/@next/env/dist/index.js:1:5038)
supabase-studio  |     at NextNodeServer.loadEnvConfig (/app/node_modules/next/dist/server/next-server.js:221:32)
supabase-studio  |     at new Server (/app/node_modules/next/dist/server/base-server.js:137:14)
supabase-studio  |     at new NextNodeServer (/app/node_modules/next/dist/server/next-server.js:144:9)
supabase-studio  |     at NextServer.createServer (/app/node_modules/next/dist/server/next.js:174:24)
supabase-studio  |   ▲ Next.js 13.5.6
supabase-studio  |   - Local:        http://7f02fe5f5879:3000
supabase-studio  |   - Network:      http://172.18.0.8:3000
supabase-studio  |
supabase-studio  |  ✓ Ready in 607ms
```

`.env.supabase` contains:
```
############
# Database - You can change these to any PostgreSQL database that has logical replication enabled.
############

POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=app_com_spanish
POSTGRES_USER=admin_com_lj # super admin
POSTGRES_PASSWORD=XYZ
```
i replaced all postgres users with ${POSTGRES_USER}

why cant the services talk to postgres?
</div>

**Comment by encima** [comment]
This is likely because your initial database does not have the schema(s) to communicate with all of the other services in the Supabase stack. Supabase is `just Postgres` but not "plug and play" with existing PG.

What to do?

- Set up the whole Supabase stack (with a new PG included and NOT your existing PG)
- Keep your original PG running
- Use pg_dump (or anything else you like) to migrate the data from your existing to the Supabase stack (see [here](https://supabase.com/docs/guides/resources/migrating-to-supabase/postgres) for info)
- Success

**Comment by LazerJesus** [comment]
thank @encima, success sounds good. i'll do that today. 
so far my schema has been managed by prisma. 
how does that work, do i have to add any extra objects to prisma? are there any complications i should be aware of?

**Comment by encima** [comment]
@LazerJesus Let me know how it goes! Nothing special you should be aware of, just note the connection string when you connect. You can see any particular tips [here](https://supabase.com/partners/integrations/prisma)

**Comment by LazerJesus** [comment]
its a horrorshow. getting kong to work with ssl and having the various endpoints accessible has been a 3 day frustration so far and no end in sight.

**Comment by LazerJesus** [comment]
no supabase for me.

**Comment by encima** [comment]
This is excellent feedback, thank you (and thank you for reporting progress). What is your self hosting setup? 
Were you able to setup Supabase running? How did you import your current database schema?

**Comment by LazerJesus** [comment]
my setup is a docker compose file with traefik and a few other services

plus another docker compose straight from https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml
where i added service labels
```

services:
  studio:
    container_name: supabase-studio
    image: supabase/studio:20240101-8e4a094
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/api/profile', (r) => {if (r.statusCode !== 200) throw new Error(r.statusCode)})"
        ]
      timeout: 5s
      interval: 5s
      retries: 3
    depends_on:
      analytics:
        condition: service_healthy
    environment:
      STUDIO_PG_META_URL: http://meta:8080
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      DEFAULT_ORGANIZATION_NAME: ${STUDIO_DEFAULT_ORGANIZATION}
      DEFAULT_PROJECT_NAME: ${STUDIO_DEFAULT_PROJECT}

      API_EXTERNAL_URL: ${API_EXTERNAL_URL}
      SUPABASE_URL: http://kong:8000

      SUPABASE_PUBLIC_URL: ${SUPABASE_PUBLIC_URL}
      STUDIO_PORT: ${STUDIO_PORT}

      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SERVICE_ROLE_KEY}

      LOGFLARE_API_KEY: ${LOGFLARE_API_KEY}
      LOGFLARE_URL: http://analytics:4000
      NEXT_PUBLIC_ENABLE_LOGS: true
      # Comment to use Big Query backend for analytics
      NEXT_ANALYTICS_BACKEND_PROVIDER: postgres
      # Uncomment to use Big Query backend for analytics
      # NEXT_ANALYTICS_BACKEND_PROVIDER: bigquery
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.studio.rule=Host(`studio.supa.vivalence.com`)"
      - "traefik.http.routers.studio.entrypoints=websecure"
      - "traefik.http.routers.studio.tls.certresolver=letsencrypt"
    ports:
      - 3000:3000
    networks:
      - public
      - supabase
```

i have access to studio on `studio.supa.vivalence.com:3000`, can CRDU data, but no access to any of the other services like auth, functions, or the likes. 
i havent even tried to add my schema yet. i wount do that before i can confirm that all features work and that i can add plugins like electricSQL

**Comment by LazerJesus** [comment]
and now the url is no longer accessible.
ill go back to apollo

**Comment by encima** [comment]
Have you modified the .env file to ensure the URLs for each of the services are correct and the `SITE_URL` matches the dashboard URL you use (it looks like you have from the compose file you gave in the previous comment)?
Of course, there is always the hosted option but I totally understand the want/need to self-host and it should be simple out of the box.

**Comment by LazerJesus** [comment]
i've tried every combination of env vars that i could think up.
the biggest problem for me might the the opaqueness of the setup. its not clear and i couldnt find documentation on how the services work together, what they consume and why, and how they interact.

**Comment by wizseek** [comment]
Being trying to self host supabase using the docker-compose as well. 

One tips for others that are researching this is to have another set of docker containers started by `supabase CLI`, while you are starting up another set of docker containers using docker compose.

Then trying to match every aspects of the containers (environment variables, docker commands, docker entrypoint, etc). As troublesome as that sounds this is the method that got me the furthest while also help me understand how does each supabase containers interact with each other. 

Haven't got it to fully functioning yet, when I do will reveal the glory (ugly) workarounds in the form of a github repo 🌚

**Comment by migueldv90** [comment]
For the past three days, I have tried self-hosting with SQL Cloud (google) and hit walls at every step. I am abandoning this plan. There is a big lack of documentation when bringing on your database, just when I made a breakthrough I encountered a new problem.
