### ISSUE TITLE
Email Auth PKCE in SSR verifyOtp Failure in Vercel

### ISSUE THREAD

**Issue by robpetty** [supabase/supabase#20961]
# Bug report

Repo is here:
https://github.com/robpetty/nextjs-auth-test

Did add code in /auth/confirm to dump the verifyOtp error seen below.  Simply needs valid Supabase project to point once deployed locally or to Vercel (and updated sign up confirm email links in Supabase Auth Email Templates).

## Describe the bug

verifyOtp fails in Vercel with:

`[AuthApiError]: Database error finding user from email link`

Based upon:
https://supabase.com/docs/guides/auth/server-side/email-based-auth-with-pkce-flow-for-ssr

Locally, this works fine.  As in:
- Fire up your app in VS Code, say localhost:3000.
- Supabase Signup template confirm email as a proper link, ex:

```
Local Check
<a href="http://localhost:3000/auth/confirm?token_hash={{ .TokenHash }}&type=email"
  >Confirm your email</a>
```
- Open in email client in a second browser (fundamental issue here is attempting to sign up in one browser, and clicking the "confirm email" link in a second browser where your email client resides.
- User is logged in.  Later after sign off you can use your email/password as expected for /login.

The issue:
- Deploy code to Vercel
- Ensure Sign Up link in Supabase template is correct, ex:

```
Vercel Check
<a href="https://YOURAPPSUBDOMAIN.vercel.app/auth/confirm?token_hash={{ .TokenHash }}&type=email">Confirm your email</a>
```

- Sign up
- Click link
- verifyOtp fails with:

```
eI [AuthApiError]: Database error finding user from email link
    at eQ (/var/task/.next/server/chunks/348.js:1:111715)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async e0 (/var/task/.next/server/chunks/348.js:1:112657)
    at async e2 (/var/task/.next/server/chunks/348.js:1:112331)
    at async au.verifyOtp (/var/task/.next/server/chunks/348.js:1:129175)
    at async c (/var/task/.next/server/app/auth/confirm/route.js:1:1723)
    at async /var/task/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484
    at async eI.execute (/var/task/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:32486)
    at async eI.handle (/var/task/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:43737)
    at async Y (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:24556) {
  __isAuthError: true,
  status: 500
}
```

## To Reproduce

- Create app:
npx create-next-app@latest -e with-supabase YOURAPPNAME .
- Push to GitHub.
- Deploy to Vercel
- Configure ENV vars in Vercel.

## Expected behavior

Can log in.

## Additional context

You actually end up being logged in per Supabase.  Once you click the link, you will see "Last Sign In" for the user in Authentication -> Users showing the time you clicked.  However, verifyOtp fails to find the user so you end up sent to a dead-end.  However, the account is valid so you can now use email/password to log in.

Have a discussion here:
https://github.com/orgs/supabase/discussions/20922

Also asked in the discord server but no dice yet.

**Comment by robpetty** [comment]
Error message from here:

https://github.com/supabase/gotrue/blob/1f1aeead921d2a1d09151124f48a58029dbb3bc0/internal/api/verify.go#L527

**Comment by Hallidayo** [comment]
Hi @robpetty - Just checking in here, are you still having this issue?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
