### ISSUE TITLE
[Storage] Error: Migration failed. Reason: Hashes don't match for migrations

### ISSUE THREAD

**Issue by Phil9l** [supabase/supabase#21222]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When I start the service the storage fails with the following error:

```
climbest-supabase-storage-1    | (node:1) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
climbest-supabase-storage-1    |
climbest-supabase-storage-1    | Please migrate your code to use AWS SDK for JavaScript (v3).
climbest-supabase-storage-1    | For more information, check the migration guide at https://a.co/7PzMCcy
climbest-supabase-storage-1    | (Use `node --trace-warnings ...` to show where the warning was created)
climbest-supabase-storage-1    | /app/node_modules/postgres-migrations/dist/migrate.js:100
climbest-supabase-storage-1    |             const error = new Error(`Migration failed. Reason: ${e.message}`);
climbest-supabase-storage-1    |                           ^
climbest-supabase-storage-1    |
climbest-supabase-storage-1    | Error: Migration failed. Reason: Hashes don't match for migrations '0002-pathtoken-column.sql,0003-add-migrations-rls.sql,0004-add-size-functions.sql,0005-change-column-name-in-get-size.sql,0006-add-rls-to-buckets.sql,0007-add-public-to-buckets.sql,0008-fix-search-function.sql,0009-search-files-search-function.sql,0010-add-trigger-to-auto-update-updated_at-column.sql,0011-add-automatic-avif-detection-flag.sql,0012-add-bucket-custom-limits.sql,0013-use-bytes-for-max-size.sql,0014-add-can-insert-object-function.sql,0015-add-version.sql,0016-drop-owner-foreign-key.sql,0017-add_owner_id_column_deprecate_owner.sql'.
climbest-supabase-storage-1    | This means that the scripts have changed since it was applied.
climbest-supabase-storage-1    |     at /app/node_modules/postgres-migrations/dist/migrate.js:100:27
climbest-supabase-storage-1    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
climbest-supabase-storage-1    |     ... 3 lines matching cause stack trace ...
climbest-supabase-storage-1    |     at async /app/dist/server.js:22:9 {
climbest-supabase-storage-1    |   cause: Error: Hashes don't match for migrations '0002-pathtoken-column.sql,0003-add-migrations-rls.sql,0004-add-size-functions.sql,0005-change-column-name-in-get-size.sql,0006-add-rls-to-buckets.sql,0007-add-public-to-buckets.sql,0008-fix-search-function.sql,0009-search-files-search-function.sql,0010-add-trigger-to-auto-update-updated_at-column.sql,0011-add-automatic-avif-detection-flag.sql,0012-add-bucket-custom-limits.sql,0013-use-bytes-for-max-size.sql,0014-add-can-insert-object-function.sql,0015-add-version.sql,0016-drop-owner-foreign-key.sql,0017-add_owner_id_column_deprecate_owner.sql'.
climbest-supabase-storage-1    |   This means that the scripts have changed since it was applied.
climbest-supabase-storage-1    |       at Object.validateMigrationHashes (/app/node_modules/postgres-migrations/dist/validation.js:24:15)
climbest-supabase-storage-1    |       at /app/node_modules/postgres-migrations/dist/migrate.js:86:26
climbest-supabase-storage-1    |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
climbest-supabase-storage-1    |       at async /app/node_modules/postgres-migrations/dist/with-lock.js:25:28
climbest-supabase-storage-1    |       at async connectAndMigrate (/app/dist/database/migrate.js:42:9)
climbest-supabase-storage-1    |       at async runMigrations (/app/dist/database/migrate.js:14:5)
climbest-supabase-storage-1    |       at async /app/dist/server.js:22:9
climbest-supabase-storage-1    | }
climbest-supabase-storage-1    |
climbest-supabase-storage-1    | Node.js v18.18.2
climbest-supabase-storage-1    | running migrations
climbest-supabase-storage-1    | (node:1) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
climbest-supabase-storage-1    |
climbest-supabase-storage-1    | Please migrate your code to use AWS SDK for JavaScript (v3).
climbest-supabase-storage-1    | For more information, check the migration guide at https://a.co/7PzMCcy
climbest-supabase-storage-1    | (Use `node --trace-warnings ...` to show where the warning was created)
climbest-supabase-storage-1    | /app/node_modules/postgres-migrations/dist/migrate.js:100
climbest-supabase-storage-1    |             const error = new Error(`Migration failed. Reason: ${e.message}`);
```

I'm running supabase with `docker compose down && docker compose -f docker-compose.yml -f docker-compose.s3.yml up --build -d`. How can I fix this issue?

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Run supabase with `docker compose down && docker compose -f docker-compose.yml -f docker-compose.s3.yml up --build -d`.

## System information

- OS: Linux
- Version of Node.js:  Node.js v18.18.2

## Additional context

There is a similar issue: https://github.com/supabase/supabase/issues/20873

**Comment by encima** [comment]
Closing this issue as duplicate. @Phil9l thanks for reporting, you can comment on closed issues and we will re-open them.
