### ISSUE TITLE
Failed to execute 'invoke' on 'LockGrantedCallback' : Select from table

### ISSUE THREAD

**Issue by lucaspluchon** [supabase/supabase#21492]
Hello!

I have encountered a problem with a SELECT query. It happens randomly when I use the debugger with Chrome.

Here are the detailed errors :

The query.data is null 
And query.error contain this :
```javascript
{
  "message": "Error: Failed to execute 'invoke' on 'LockGrantedCallback': The provided callback is no longer runnable.",
  "details": "Error: Failed to execute 'invoke' on 'LockGrantedCallback': The provided callback is no longer runnable.\n    at fetchData (http://localhost:3000/static/js/bundle.js:6657:19)\n    at http://localhost:3000/static/js/bundle.js:6680:5\n    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:152954:30)\n    at commitPassiveMountOnFiber (http://localhost:3000/static/js/bundle.js:154447:17)\n    at commitPassiveMountEffects_complete (http://localhost:3000/static/js/bundle.js:154419:13)\n    at commitPassiveMountEffects_begin (http://localhost:3000/static/js/bundle.js:154409:11)\n    at commitPassiveMountEffects (http://localhost:3000/static/js/bundle.js:154399:7)\n    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:156282:7)\n    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:156235:18)\n    at http://localhost:3000/static/js/bundle.js:156050:13",
  "hint": "",
  "code": ""
}
``` 

With that code : 
```typescript
const fetchData = async () => {
    const query = await supabase
            .from('Session')
            .select('*')
            .eq('id', "407376eb-7344-4790-83c9-d85a7ec86b94");
}


useEffect(() => {
    fetchData();
}, [id]);
``` 

This issue occurs consistently on some React components and never on others.
The id exist in the table.

Context : 
- Mac OS Sonoma 14.1.1 (23B81) on ARM Chip
- Using with "react": "^18.2.0",
- Using "@supabase/supabase-js": "^2.39.7",
- Chrome 121.0.6167.184 (Official build) (arm64)

**Comment by safwanyp** [comment]
This is a common type of error when using breakpoints in Chrome. 

https://issues.chromium.org/issues/40721349
