### ISSUE TITLE
supabase_imgproxy "Source image resolution is too big" when images >= 16.8MP in local dev / self-hosted

### ISSUE THREAD

**Issue by argotechnica** [supabase/supabase#21645]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

[Storage Image Transformations § Limits](https://supabase.com/docs/guides/storage/serving/image-transformations#limits) states: "The image resolution cannot exceed 50MP." However, `docker-compose.yml` does not set the required value `IMGPROXY_MAX_SRC_RESOLUTION` to increase the default value of 16.8MP to 50MP for local development / self-hosted contexts. As a result, my local dev / self hosted experience differs in an undocumented way from production, and there doesn't seem to be an easy way to adjust this setting locally. The way it manifests locally is also a bit confusing/unclear because (at least for me in the context of building a Next.js app), the first way it manifests is as a 404 error when requesting an image transform URL for an image that is >= 16.8 MP.

From [upstream documentation $ Security](https://docs.imgproxy.net/configuration/options#security): 

> `IMGPROXY_MAX_SRC_RESOLUTION`: the maximum resolution of the source image, in megapixels. Images with larger actual size will be rejected. Default: `16.8`

The [Docker config for `supabase-imgproxy`](https://github.com/supabase/supabase/blob/d9dbd66a8204f5525e07812f851d8f12402257e7/docker/docker-compose.yml#L241) does not set this variable:

```yaml
  imgproxy:
    container_name: supabase-imgproxy
    image: darthsim/imgproxy:v3.8.0
    healthcheck:
      test: [ "CMD", "imgproxy", "health" ]
      timeout: 5s
      interval: 5s
      retries: 3
    environment:
      IMGPROXY_BIND: ":5001"
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /
      IMGPROXY_USE_ETAG: "true"
      IMGPROXY_ENABLE_WEBP_DETECTION: ${IMGPROXY_ENABLE_WEBP_DETECTION}
    volumes:
      - ./volumes/storage:/var/lib/storage:z
```

The trail I followed looked like this:

1. In my Next.js app, 404 errors in console when using the image transform URLs, even though I knew the image existed and other images of a roughly similar size (and same settings such as color depth) were working fine

2. 422 errors from Axios

3. `supabase_storage` log errors:

```json
  "error": {
    "raw": "{\"name\":\"ImageProcessingError\",\"httpStatusCode\":422,\"userStatusCode\":400,\"originalError\":{\"message\":\"Request failed with status code 422\",\"name\":\"AxiosError\",\"stack\":\"AxiosError: Request failed with status code 422\\n    at settle (/app/node_modules/axios/dist/node/axios.cjs:1967:12)\\n    at RedirectableRequest.handleResponse (/app/node_modules/axios/dist/node/axios.cjs:3010:9)\\n    at RedirectableRequest.emit (node:events:529:35)\\n    at RedirectableRequest._processResponse (/app/node_modules/follow-redirects/index.js:351:10)\\n    at RedirectableRequest._onNativeResponse (/app/node_modules/follow-redirects/index.js:57:10)\\n    at Object.onceWrapper (node:events:632:26)\\n    at ClientRequest.emit (node:events:517:28)\\n    at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)\\n    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)\\n    at Socket.socketOnData (node:_http_client:541:22)\",\"config\":{\"transitional\":{\"silentJSONParsing\":true,\"forcedJSONParsing\":true,\"clarifyTimeoutError\":false},\"adapter\":[\"xhr\",\"http\"],\"transformRequest\":[null],\"transformResponse\":[null],\"timeout\":15000,\"xsrfCookieName\":\"XSRF-TOKEN\",\"xsrfHeaderName\":\"X-XSRF-TOKEN\",\"maxContentLength\":-1,\"maxBodyLength\":-1,\"env\":{},\"headers\":{\"Accept\":\"application/json, text/plain, */*\",\"User-Agent\":\"axios/1.6.3\",\"Accept-Encoding\":\"gzip, compress, deflate, br\"},\"baseURL\":\"http://storage_imgproxy_cumulus-web-app:5001\",\"httpAgent\":{\"_events\":{\"free\":[null,null]},\"_eventsCount\":2,\"defaultPort\":80,\"protocol\":\"http:\",\"options\":{\"maxSockets\":5000,\"freeSocketTimeout\":2000,\"keepAlive\":true,\"timeout\":61000,\"socketActiveTTL\":0,\"noDelay\":true,\"path\":null},\"requests\":{},\"sockets\":{},\"freeSockets\":{\"storage_imgproxy_cumulus-web-app:5001:\":[{\"connecting\":false,\"_hadError\":false,\"_parent\":null,\"_host\":\"storage_imgproxy_cumulus-web-app\",\"_closeAfterHandlingError\":false,\"_readableState\":{\"state\":266328,\"highWaterMark\":16384,\"buffer\":{\"head\":null,\"tail\":null,\"length\":0},\"length\":0,\"pipes\":[],\"flowing\":true,\"errored\":null,\"defaultEncoding\":\"utf8\",\"awaitDrainWriters\":null,\"decoder\":null,\"encoding\":null},\"_events\":{\"free\":[null,null],\"close\":[null,null],\"timeout\":[null,null,null],\"error\":[null,null],\"agentRemove\":[null,null]},\"_eventsCount\":6,\"_writableState\":{\"objectMode\":false,\"highWaterMark\":16384,\"finalCalled\":false,\"needDrain\":false,\"ending\":false,\"ended\":false,\"finished\":false,\"destroyed\":false,\"decodeStrings\":false,\"defaultEncoding\":\"utf8\",\"length\":0,\"writing\":false,\"corked\":0,\"sync\":false,\"bufferProcessing\":false,\"writecb\":null,\"writelen\":0,\"afterWriteTickInfo\":null,\"buffered\":[],\"bufferedIndex\":0,\"allBuffers\":true,\"allNoop\":true,\"pendingcb\":0,\"constructed\":true,\"prefinished\":false,\"errorEmitted\":false,\"emitClose\":false,\"autoDestroy\":true,\"errored\":null,\"closed\":false,\"closeEmitted\":false},\"allowHalfOpen\":false,\"_sockname\":null,\"_pendingData\":null,\"_pendingEncoding\":\"\",\"server\":null,\"_server\":null,\"timeout\":2000,\"parser\":null,\"_httpMessage\":null}]},\"keepAliveMsecs\":1000,\"keepAlive\":true,\"maxSockets\":5000,\"maxFreeSockets\":256,\"scheduling\":\"lifo\",\"maxTotalSockets\":null,\"totalSocketCount\":1,\"createSocketCount\":138,\"createSocketCountLastCheck\":0,\"createSocketErrorCount\":0,\"createSocketErrorCountLastCheck\":0,\"closeSocketCount\":137,\"closeSocketCountLastCheck\":0,\"errorSocketCount\":0,\"errorSocketCountLastCheck\":0,\"requestCount\":805,\"requestCountLastCheck\":0,\"timeoutSocketCount\":137,\"timeoutSocketCountLastCheck\":0},\"responseType\":\"stream\",\"method\":\"get\",\"url\":\"/public/height:364/width:547/resizing_type:fit/plain/local:////mnt/stub/stub/medias/df7e6830-5e8f-4193-9e6e-26e4c1e89d30/0e8783b5-0bf7-48a2-9149-8ac94e4ead5d/04efa708-3c06-446a-b551-cf15e9222b0d\",\"axios-retry\":{\"retries\":5,\"shouldResetTimeout\":true,\"retryCount\":0,\"lastRequestTime\":1709146948608}},\"code\":\"ERR_BAD_REQUEST\",\"status\":422}}",
    "name": "ImageProcessingError",
    "message": "Invalid source image",
    "stack": "ImageProcessingError: Invalid source image\n    at ImageRenderer.handleRequestError (/app/dist/storage/renderer/image.js:206:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ImageRenderer.getAsset (/app/dist/storage/renderer/image.js:186:17)\n    at async ImageRenderer.render (/app/dist/storage/renderer/renderer.js:12:26)"
  }
```

5. `supabase_imgproxy` log warnings with the final culprit, "Source image resolution too big":

```
WARNING [2024-02-28T19:30:25Z] Completed in 180.963µs /public/plain/local:////mnt/stub/stub/medias/7f6edb55-d232-4b0e-a212-898970cf02ab/812edfb9-a41c-4971-a802-c40bb7f24dab/f27dc083-0214-4b11-8dee-f05261d3eda6  request_id=qcRwRWIVydig-VtcM9MdY method=GET status=422 client_ip=172.18.0.10 error="Can't download source image: Source image resolution is too big"
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Upload an image to Supabase storage bucket that is equal to or exceeds 16.8MP
2. Request an image transformation of it

Here are 3 test images at very slightly different resolutions to test the MP threshold. In my case it accepts the 16.79 MP but not the 16.8 MP. Since 16.8 MP is the default according to imgproxy, it seems clear that this default is not being overridden to the 50MP stated in docs. It isn't set in `docker-compose`

![4731x3549-16 79](https://github.com/supabase/supabase/assets/7676223/41d7d776-84a7-4c02-b6e7-597b344ba0ef)
![4733x3550-16 80](https://github.com/supabase/supabase/assets/7676223/8ae432a2-e7ce-4960-8aec-d946c8313bda)
![4734x3551-16 81](https://github.com/supabase/supabase/assets/7676223/332122f8-273b-4cba-9fde-4fc8d6b1479b)

## Expected behavior

Can use image transform on up to 50MP **or, ideally, an easily user-configurable value** in local dev / self hosted settings

## System information

- OS: Ubuntu 22.04 on WSL2 on Win11
- Version of supabase-js: 2.39.7
- Version of Node.js: v18.17.1

Container versions:

public.ecr.aws/supabase/edge-runtime:v1.33.5
public.ecr.aws/supabase/studio:20240101-8e4a094
public.ecr.aws/supabase/postgres-meta:v0.75.0
public.ecr.aws/supabase/imgproxy:v3.8.0
public.ecr.aws/supabase/storage-api:v0.46.4
public.ecr.aws/supabase/postgrest:v12.0.1
public.ecr.aws/supabase/realtime:v2.25.50
public.ecr.aws/supabase/inbucket:3.0.3
public.ecr.aws/supabase/gotrue:v2.132.3
public.ecr.aws/supabase/kong:2.8.1
public.ecr.aws/supabase/logflare:1.4.0
public.ecr.aws/supabase/postgres:15.1.0.147
public.ecr.aws/supabase/vector:0.28.1-alpine

## Additional context

This seems to work fine in hosted Supabase. It seems to only affect local development instances or self-hosted. I've tried uploading an image that is 50.1 MP and it worked OK.

**Comment by encima** [comment]
Thanks for opening! We welcome PRs to add the ENV variable to the docker deployment 😄

**Comment by jonathanlal** [comment]
This should be documented. I'm getting the "Can't download source image: Source image resolution is too big" error for images that are only 1MB in size... Will have to check the filesize now before applying transformations

**Comment by jonathanlal** [comment]
Ok actually it was giving an error because the dimensions were too large. Apparently these are the limitations for default supabase imgproxy:
"The maximum image dimensions are 2500x2500 pixels, and the file size must not exceed 25MB"
https://www.restack.io/docs/supabase-knowledge-supabase-image-transformations

**Comment by argotechnica** [comment]
FWIW, I just noticed that upstream imgproxy now sets `IMGPROXY_MAX_SRC_RESOLUTION` to 50 by default since [v3.23.0](https://github.com/imgproxy/imgproxy/releases/tag/v3.23.0), released March 11, 2024

[Supabase official `/docker/docker-compose.yml`](https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml) still hardcodes v3.8.0, which is from Oct 6, 2022

I may get around to testing imgproxy v3.23.0 in a self-hosted setup. If it works OK then Supabase may not need to manually define this in Docker Compose but could just update imgproxy instead. I will try to update here if I do test

**Comment by Hallidayo** [comment]
Hi @argotechnica - Just checking in here, are you still experiencing this issue?

**Comment by N1k0lay** [comment]
When will imgproxy be updated?

**Comment by aantti** [comment]
Will check! Cc @singh-inder

**Comment by aantti** [comment]
Updated via https://github.com/supabase/supabase/pull/42032
