### ISSUE TITLE
SupabaseVectorStore PGRST202 Could not find the function public.match_documents

### ISSUE THREAD

**Issue by wangzhiwei1888** [supabase/supabase#21687]
/** 向量查询 */
const store = new SupabaseVectorStore(embeddingModel, {
  client: supabaseClient,
  tableName: "documents",
  queryName: "match_documents",
});

const res = await store.similaritySearch("promise 的用法", 1);
console.log(res);

his will be mandatory after the next "langchain" minor version bump to 0.2.
(node:64911) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///Users/mac/test/langchain-test/node_modules/.pnpm/@langchain+community@0.0.34_nnjlcivkhc3bca7ybw47q5qp3a/node_modules/@langchain/community/dist/vectorstores/supabase.js:127
            throw new Error(`Error searching for documents: ${error.code} ${error.message} ${error.details}`);
                  ^

Error: Error searching for documents: PGRST202 Could not find the function public.match_documents(filter, match_count, query_embedding) in the schema cache Searched for the function public.match_documents with parameters filter, match_count, query_embedding or with a single unnamed json/jsonb parameter, but no matches were found in the schema cache.
    at SupabaseVectorStore._searchSupabase (file:///Users/mac/test/langchain-test/node_modules/.pnpm/@langchain+community@0.0.34_nnjlcivkhc3bca7ybw47q5qp3a/node_modules/@langchain/community/dist/vectorstores/supabase.js:127:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SupabaseVectorStore.similaritySearchVectorWithScore (file:///Users/mac/test/langchain-test/node_modules/.pnpm/@langchain+community@0.0.34_nnjlcivkhc3bca7ybw47q5qp3a/node_modules/@langchain/community/dist/vectorstores/supabase.js:139:26)
    at async SupabaseVectorStore.similaritySearch (file:///Users/mac/test/langchain-test/node_modules/.pnpm/@langchain+core@0.1.40/node_modules/@langchain/core/dist/vectorstores.js:104:25)
    at async file:///Users/mac/test/langchain-test/src/connection/store/supabase.mjs:26:13

Node.js v18.10.0

**Comment by encima** [comment]
Hi there, 

Thanks for opening. We will need more information than the error dump.
- Are you using hosted Supabase?
- Do you have `pgvector` installed?
- Do you have a `match_documents` function?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
