### ISSUE TITLE
Error on supabase-storage self hosted

### ISSUE THREAD

**Issue by hrqmonteiro** [supabase/supabase#21754]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

```
{"level":30,"time":"2024-03-04T20:02:11.040Z","pid":1,"hostname":"063310ca08ce","reqId":"req-14","tenantId":"stub","project":"stub","reqId":"req-14","type":"request","req":{"traceId":"req-14","method":"GET","url":"/bucket","headers":{"host":"storage:5000","x_forwarded_proto":"http","x_forwarded_host":"kong","x_forwarded_port":"8000","x_real_ip":"192.168.32.5","x_client_info":"supabase-js-node/2.39.3","accept":"*/*","user_agent":"node"},"hostname":"storage:5000","remoteAddress":"192.168.32.7","remotePort":41346},"res":{"statusCode":500,"headers":{"content_type":"application/json; charset=utf-8","content_length":"73"}},"responseTime":8.106200000271201,"error":{"raw":"{\"statusCode\":500,\"error\":\"internal\",\"originalError\":{\"length\":95,\"name\":\"error\",\"severity\":\"ERRO\",\"code\":\"22023\",\"file\":\"guc.c\",\"line\":\"6734\",\"routine\":\"call_string_check_hook\"},\"details\":\"\\n        SELECT\\n          set_config('role', $1, true),\\n          set_config('request.jwt.claim.role', $2, true),\\n          set_config('request.jwt', $3, true),\\n          set_config('request.jwt.claim.sub', $4, true),\\n          set_config('request.jwt.claims', $5, true),\\n          set_config('request.headers', $6, true),\\n          set_config('request.method', $7, true),\\n          set_config('request.path', $8, true);\\n     - role \\\"service_role\\\" não existe\",\"query\":\"\\n        SELECT\\n          set_config('role', $1, true),\\n          set_config('request.jwt.claim.role', $2, true),\\n          set_config('request.jwt', $3, true),\\n          set_config('request.jwt.claim.sub', $4, true),\\n          set_config('request.jwt.claims', $5, true),\\n          set_config('request.headers', $6, true),\\n          set_config('request.method', $7, true),\\n          set_config('request.path', $8, true);\\n    \"}","name":"Error","message":"Internal Server Error","stack":"Error: Internal Server Error\n    at DBError.fromDBError (/app/dist/storage/database/knex.js:445:16)\n    at Function.<anonymous> (/app/dist/storage/database/knex.js:372:31)\n    at Object.onceWrapper (node:events:632:26)\n    at Function.emit (node:events:517:28)\n    at Client_PG.<anonymous> (/app/node_modules/knex/lib/knex-builder/make-knex.js:299:10)\n    at Client_PG.emit (node:events:529:35)\n    at /app/node_modules/knex/lib/execution/internal/query-executioner.js:46:12\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:300:14)\n    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)"},"msg":"stub | GET | 500 | 192.168.32.7 | req-14 | /bucket | node"}
```

## To Reproduce

Just tryint to use supabase-storage with s3

## Expected behavior

To work

## Screenshots

![image](https://github.com/supabase/supabase/assets/17055027/87303cd0-06a1-4e39-8748-0e569eafdc12)

## System information

- OS: ubuntu 22.04
- Browser (if applies): none
- Version of supabase-js: none
- Version of Node.js: none

## Additional context

I am using self-host with docker.

**Comment by encima** [comment]
Thanks for reporting, we will need more information to help with this.
- What is your storage configuration?
- Have you modified the config in any other part of the Supabase stack?
- Are there other relevant Docker logs?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
