### ISSUE TITLE
AuthApiError: invalid request: both auth code and code verifier should be non-empty

### ISSUE THREAD

**Issue by kafle1** [supabase/supabase#22350]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Error: AuthApiError: invalid request: both auth code and code verifier should be non-empty

Checked everything on the internet, all the old issues, posted on supabase discord still nothing seems to work for me.
I am trying to implement authentication with supabase and sveltekit. Everything works fine locally, but when I deploy it I get the error. Error occurs when I am redirected to /auth/callback (from email link while signup, from google in oauth). `+server.ts` file is there to handle callback and i get code in the URL which is then extracted and passed to exchangeCodeForSession() function coming from supabase auth.
Am following exactly that's mentioned in this doc (not the UI part): https://supabase.com/docs/guides/getting-started/tutorials/with-sveltekit#building-the-app

The error is being thrown from here:
```ts
const { data } = await supabase.auth.exchangeCodeForSession(code);
```
## To Reproduce
When button is clicked this is hit:
```ts
	const { data } = await supabase.auth.signInWithOAuth({
					provider: provider as Provider,
					options: {
						redirectTo: `${url.origin}/auth/callback?provider=${provider}`
					}
				});
```
After auth is completed its redirected to this:
```ts
	const {
		url,
		locals: { supabase }
	} = event;
	const code = url.searchParams.get('code') as string;
	const provider = url.searchParams.get('provider') as string;

        if (!code) {
	        error(400, 'No code provided');
        }
        
        const { data } = await supabase.auth.exchangeCodeForSession(code);
```

## Expected behavior

Login without any error.

## System information

- OS: Zorin 17.1
- Version of supabase-js: ^2.39.8
- Version of Node.js: 20.12.0

**Comment by encima** [comment]
If you are experiencing this on a hosted project, it may be easier to open a support ticket so that the team can access logs and config to help debug

**Comment by kafle1** [comment]
Created post on discord server too but got no response :(
https://discord.com/channels/839993398554656828/1222519673782927502

this is the log:
```ts
AuthApiError: invalid request: both auth code and code verifier should be non-empty
0|app      |     at handleError (/root/FunApps.ai/node_modules/@supabase/auth-js/dist/main/lib/fetch.js:63:11)
0|app      |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|app      |     at async _handleRequest (/root/FunApps.ai/node_modules/@supabase/auth-js/dist/main/lib/fetch.js:111:9)
0|app      |     at async _request (/root/FunApps.ai/node_modules/@supabase/auth-js/dist/main/lib/fetch.js:89:18)
0|app      |     at async SupabaseAuthClient._exchangeCodeForSession (/root/FunApps.ai/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:409:33)
0|app      |     at async /root/FunApps.ai/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:736:28 {
0|app      |   __isAuthError: true,
0|app      |   status: 400,
0|app      |   code: undefined
0|app      | }
```
