### ISSUE TITLE
Second phantom subscription created on subscribe()

### ISSUE THREAD

**Issue by awalias** [supabase/supabase#24]
after running:
```javascript
    const mySubscription = await supabase
      .from('messages')
      .on('*', callbackAction)
      .subscribe()
```
if I inspect `supabase.subscriptions`, I can see two subscriptions, the second of which is mostly empty:
```
Supabase {
  tableName: 'messages',
  restUrl: 'http://localhost:8000/rest/v1',
  realtimeUrl: 'ws://localhost:8000/realtime/v1',
  schema: 'public',
  uuid: '516eab5e-5f4b-3fb6-d049-8b7eeb02b03a',
  apikey: 'examplekey',
  socket: null,
  channel: null,
  listeners: {},
  queryFilters: []
}
```

the problem is if I pass it to `supabase.removeSubscription` it throws an exception:

```
     TypeError: Cannot read property 'disconnect' of null
      at Supabase.unsubscribe (src/Supabase.js:133:17)
      at SupabaseClient.removeSubscription (src/index.js:44:20)
      at Context.<anonymous> (test/integration/testRealtime.js:16:16)
      at processImmediate (internal/timers.js:439:21)
```

**Comment by awalias** [comment]
Looked into this, it's because we create a new subscription every time 'from()' is invoked and store the resulting Supabase instance in `this.subscriptions`

```javascript
  from(tableName) {
    let identifier = uuid()

    this.subscriptions[identifier] = new Supabase(
      tableName,
      this.restUrl,
      this.realtimeUrl,
      this.defaultSchema,
      this.supabaseKey,
      identifier
    )
    return this.subscriptions[identifier]
  }```

We need to solve for the case where this is a CRUD operation instead of a realtime one, I'd say either:

1) we don't store new Supabase instances in a variable until the point we know it's a realtime subscription (in `on()`?) - and then we add it to `this.subscriptions`

2) we change the name of the variable (to `this.instances`?) and we clean up the CRUD ones once a request has been made. Although (I may be wrong) but I can't think of a reason to keep non-realtime instances around?

**Comment by awalias** [comment]
Also noting that we need to clean up non-subscription instances that get added, since the array will just continue to grow for long-running clients
