### ISSUE TITLE
AuthApiError: Session from session_id claim in JWT does not exist

### ISSUE THREAD

**Issue by Whitebytes** [supabase/supabase#25350]
# Bug report

## Describe the bug
Getting a  "AuthApiError: Session from session_id claim in JWT does not exist" when doing a 
client.auth.setSession({ access_token,    refresh_token   }) with  access_token,    refresh_token  retrieved from:

client.auth.admin.generateLink( {  type: 'recovery', email, redirectTo  })

Users are unable to recover password on production site.

Steps: 
1. client.auth.admin.generateLink( {  type: 'recovery', email, redirectTo  }), gives me: 
2. https://vzuflxgfykebwmisvssp.supabase.co/auth/v1/verify?token=df90ebfc4e344c0f3c60bf0b7123d738591a3bd454fce8c24db79618&type=recovery&redirect_to=http://localhost:3005. (<- sample url, slightly modified for security reasons, this is also not production site, but dev)
3. opened a new incognito window of chrome
4. pasted url, redirects me to:
5. http://localhost:3005/set-password?access_token=eyJhbGciOiJIUzI1NiIsImtpZCI6InpCeHllYzM2SStxZm5tNUMiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzE0OTgwMzEzLCJpYXQiOjE3MTQ5NzY3MTMsImlzcyI6Imh0dHBzOi8vdnp1Zmx4Z2Z5a2Vid21pc3Zzc3Auc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6IjE3YmQ5MTgzLWZjYzgtNGIwOC05YTY5LWYyNzRhNDRkMzAyYSIsImVtYWlsIjoiZ2pAcWVtbWUubmwiLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIiwiZ29vZ2xlIl19LCJ1c2VyX21ldGFkYXRhIjp7IkNvbXBhbnlJZCI6IjIzYzg1NDliLTdiNmEtNGZhOS04ZTQzLWY3MDNhZDJhNDkwMyIsImF2YXRhcl91cmwiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NJRV9lRk9vZVhlOTc2MlVheHZpSFJkUXFwaG9OLXhxa0dqRWlwdUNNbU9lNXVTc3c9czk2LWMiLCJiaXJ0aGRheSI6IjIwMDEtMDEtMDEiLCJjaXR5IjoiMTExIiwiY29uZmlybV9wYXNzd29yZCI6ImdqMjM5NyIsImNyZWF0ZWRfYXQiOiIyMDIzLTExLTMwVDEzOjUyOjM5Ljk5MTI2NiswMDowMCIsImN1c3RvbV9jbGFpbXMiOnsiaGQiOiJxZW1tZS5ubCJ9LCJlbWFpbCI6ImdqQHFlbW1lLm5sIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcnN0TmFtZSI6IkpvaG4iLCJmdWxsX25hbWUiOiJHZWVydEphbiBLwZw1tZSIsImlkIjoiYmUyMTY2MWMtNGE3OC00NDM0LTg4NGMtNjA3MDM4NDYyZjE2IiwiaXNzIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tIiwibGFzdE5hbWUiOiJEb2UiLCJuYW1lIjoiR2VlcnRKYW4gS2VtbWUiLCJwaG9uZSI6IjEyMzQ1Njc4OTAiLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NJRV9lRk9vZVhlOTc2MlVheHZpSFJkUXFwaG9OLXhxa0dqRWlwdUNNbU9lNXVTc3c9czk2LWMiLCJwcm92aWRlcl9pZCI6IjEwMDQ2MTY4NDc4MzczNTA1OTg5NyIsInN1YiI6IjEwMDQ2MTY4NDc4MzczNTA1OTg5NyIsInVwZGF0ZWRfYXQiOiIyMDIzLTExLTMwVDEzOjUyOjM5Ljk5MTI2NiswMDowMCJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6Im90cCIsInRpbWVzdGFtcCI6MTcxNDk3NjcxM31dLCJzZXNzaW9uX2lkIjoiOGE4OGY5ODEtNmMxYi00Mzc5LTg3NTItMzgzZWI1ZDA2OTg0IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.b4bMEWULNmh_QhZhHEzxxV3LWoyu30W0Ws7y4aKOHU4&refresh_token=tMCR-ELvILoTyov1-4g4ww&type=recovery (<-sample, token modified for sec. reasons, dev env)
6. using the access_token and refresh_token from this url to do a client.auth.setSession({ access_token,    refresh_token   }), gives the error

## Expected behavior
 session set and be able to set user/password

did found some related reports on discord, not sure if it is the exact same issue:

https://discord.com/channels/839993398554656828/1235896967754682478

**Comment by JOsacky** [comment]
I am also running into this issue and users are not able to logout using the iOS client and instead throws an error because the response is a 403.

Force log outs only happen for 404s and 401s on the iOS client, perhaps updating the response to a 401 would make more sense


Here is the a reference to the swift supabase client code that throws
https://github.com/supabase/supabase-swift/blob/f1e17ee7ceef4e9da56c57fdd299fa1cf1641381/Sources/Auth/AuthClient.swift#L714-L723
  
  
Here is a photo of the error in the xcode debugger:
"image" src="https://github.com/supabase/supabase/assets/1144450/ec53ced9-9ecd-4990-bbb9-bb5afb0108b7">

**Comment by otang** [comment]
I am experiencing the same issue

**Comment by erasmusa** [comment]
Hi there everyone,

I am currently having the same issue. I am developing a react-admin web application for internal usage. I use the 'ra-supabase' npm package. I host the app on Firebase but use the Supabase backend. I'm experiencing this error during the implementation of my "forgot password" workflow. The first step where I get the email with the link back to my app works 100%. 

This link contains the needed parameters i.e. access_token (JWT) and the refresh_token. I pass these to the function provided by the useSetPassword hook. Behind the scenes it calls the setPassword method in the authProvider which in turn calls setSession which checks if the token had expired and if not tries to fetch the user by calling _getUser giving it the access_token. 

It is this _getUser (/v1/user) call that eventually throws a 403 error and returning "AuthApiError: Session from session_id claim in JWT does not exist".

To me it looks like an issue on the Supabase API side. Any ideas?

**Comment by matart15** [comment]
`AuthApiError: Session from session_id claim in JWT does not exist` is happening on logout.

Supabase cloud platform. Please hix this. 

Our users can't `logout` even they delete cache.
Client can't switch accounts and having a big trouble.

**Comment by ibash-corpusant** [comment]
As a workaround you can invalidate the session manually if it errors:
```typescript
const result = await supabase.auth.signOut();

if (result.error) {
  await supabase.auth._removeSession()
  await supabase.auth._notifyAllSubscribers('SIGNED_OUT', null)
}
```

**Comment by Hallidayo** [comment]
Hi all, Just checking in here. Did you get this working or is it still an issue?

**Comment by bearbricknik** [comment]
> Hi all, Just checking in here. Did you get this working or is it still an issue? 

This is still an issue. We receive it in our app lately using magic link

**Comment by corrgrid** [comment]
Confirm the issue. 

`POST https:// ... .supabase.co/auth/v1/logout?scope=global 403 (Forbidden)`

```
(index):639 Error logging out: AuthApiError: Session from session_id claim in JWT does not exist
    at M (supabase.js:1:8779)
    at async J.c.headers (supabase.js:1:9527)
    at async J (supabase.js:1:9140)
    at async V.signOut (supabase.js:1:11103)
    at async supabase.js:1:32709
    at async supabase.js:1:27456
    at async Object.__stack_guard___useSession__ (supabase.js:1:6463)
    at async T (supabase.js:1:6517)
    at async supabase.js:1:27381
    at async supabase.js:1:26784

```
The session appears to be valid, yet the logout request does not succeed.

**Comment by Ankur1493** [comment]
Happening in logging out a user too, sometime the cookies get deleted but most of the time it redirects user to login screen and then back to home page

**Comment by bogdankhamelyuk** [comment]
Has happened to me as well and workaround from @ibash-corpusant  helped me a lot. However, `_removeSession()` is private method and cannot be called using normal service client. Inside of the private method following happens:

```typescript
  private async _removeSession() {
    this._debug('#_removeSession()')

    await removeItemAsync(this.storage, this.storageKey)
  }

// helper.ts
export const removeItemAsync = async (storage: SupportedStorage, key: string): Promise<void> => {
  await storage.removeItem(key)
}
```
So basically storage is freed. Therefore i came up with own solution:

```typescript

async signOut() {
        const { error } = await this.supabase.auth.signOut();
        if (error) {
            console.error('Logout failed:', error.message);
            console.error('Cleaning storage key manually and refreshing the page.');
            //    await removeItemAsync(this.storage, );
            // Default Supabase storage key: sb-<project-ref>-auth-token
            const projectRef = new URL(environment.supabaseUrl).hostname.split('.')[0]; // e.g. hvebeabchfm
            const storageKey = `sb-${projectRef}-auth-token`;

            // Best-effort: also clear a custom key if you ever set one, and remember_me flag
            const extras = ['vukha-auth', 'remember_me'];

            // Clear in-memory session (ignores server errors)
            this.supabase.auth.signOut({ scope: 'local' }).catch(() => { });

            // Remove from both storages
            [localStorage, sessionStorage].forEach(store => {
                try { store.removeItem(storageKey); } catch { }
                extras.forEach(k => { try { store.removeItem(k); } catch { } });
            });

            // Full reload to app root (resets Angular state)
            const base = document.querySelector('base')?.getAttribute('href') || '/';
            window.location.replace(base.startsWith('http') ? base : `${window.location.origin}${base}`);

        }
    }
```
This deletes the key and goes to the base page. Hope that helps
