### ISSUE TITLE
Update CLI docs to include `docker` permission group

### ISSUE THREAD

**Issue by nicholaschiang** [supabase/supabase#2551]
# Bug report

## Describe the bug

The command `supabase init` fails with the following error:

```commandline
nchiang@eevee ~/repos/tutorbook (supabase) $ supabase init
✔ Port for Supabase URL: · 8000
✔ Port for PostgreSQL database: · 5432
✔ Port for email testing interface: · 9000
✖ Error running docker-compose: [112955] Failed to execute script docker-compose
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Follow [these instructions](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository) to install the Docker Engine
2. Follow [these instructions](https://docs.docker.com/compose/install/#install-compose-on-linux-systems) to install Docker Compose
3. Install the Supabase CLI: `npm i -g supabase`
4. Try running: `supabase init`
5. See error

## Expected behavior

There should be no error; the Supabase CLI should finish initializing without trouble.

## System information

- OS: Ubuntu 20.04 LTS (PopOS 20.04)
- Version of supabase: 0.4.4 (output from `supabase -v`)
- Version of Node.js: 12.18.3

## Additional context

I'm working with [this repository](https://github.com/tutorbookapp/tutorbook) on the `supabase` branch.

**Comment by nicholaschiang** [comment]
To fix, you have to follow [these instructions](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user) to setup the `docker` permissions group and add your user to it. Only after you've done that can the Supabase CLI properly access Docker services. **You should mention this in [the CLI documentation](https://beta.supabase.io/docs/guides/local-development#prerequisites) please.**

**Comment by kiwicopple** [comment]
Thanks for debugging this for us @nicholaschiang :)

I've added the instructions - they're going live now
