### ISSUE TITLE
PostgresClient is not a constructor

### ISSUE THREAD

**Issue by RamyaChinnadurai** [supabase/supabase#26657]
Starting this morning, I began encountering the error `PostgresClient is not a constructor` despite not making any changes to my code.

I'm currently using `@supabase/supabase-js: 2.12.0`. 

I suspected that the issue might be related to a recent update in one of the dependencies. Turns out `supabase/postgres-js` updated in the last 24 hours

As a temporary workaround, I have forced the use of a previous version of the dependency by adding the following to my package.json:

```js
resolutions: {
 "@supabase/postgrest-js": "1.1.1",
}
```

Looking for a permanent solution for this case

**Comment by darrendawson** [comment]
I also ran into this today when deploying a new edge function. The deploy was successful, but calling the EF always results in an error code 546 and the message: 

```
event loop error: TypeError: ue.PostgrestClient is not a constructor
    at new j (https://esm.sh/v135/@supabase/supabase-js@2.43.3/deno/supabase-js.mjs:12:5741)
    at Oe (https://esm.sh/v135/@supabase/supabase-js@2.43.3/deno/supabase-js.mjs:12:9156)
```

**Comment by zguo123** [comment]
Same issue here. I solved by downgrading to the previous version.

**Comment by constant-work** [comment]
Starting receiving this error today as well:

`ue.PostgrestClient is not a constructor`

**Comment by kevinschaich** [comment]
similar error, I had the following:

```typescript
import { PostgrestError } from '@supabase/supabase-js'
```

was working fine, didn't make any changes, now I get:

```
Type error: Could not find a declaration file for module '@supabase/supabase-js'.
```
