### ISSUE TITLE
Edge function error: http2 error: stream error received: unspecific protocol error detected

### ISSUE THREAD

**Issue by Jonny1987** [supabase/supabase#27358]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I get the following error in my edge function:

```
Error: request to https://www.googleapis.com/oauth2/v4/token failed, reason: error sending request for url (https://www.googleapis.com/oauth2/v4/token): http2 error: stream error received: unspecific protocol error detected
    at Gaxios._request (file:///tmp/sb-compile-edge-runtime/node_modules/localhost/gaxios/6.5.0/build/src/gaxios.js:143:19)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async GoogleToken._GoogleToken_requestToken (file:///tmp/sb-compile-edge-runtime/node_modules/localhost/gtoken/7.1.0/build/src/index.js:241:19)
    at async GoogleToken._GoogleToken_getTokenAsync (file:///tmp/sb-compile-edge-runtime/node_modules/localhost/gtoken/7.1.0/build/src/index.js:160:16)
    at async JWT.refreshTokenNoCache (file:///tmp/sb-compile-edge-runtime/node_modules/localhost/google-auth-library/9.8.0/build/src/auth/jwtclient.js:173:23)
    at async JWT.authorizeAsync (file:///tmp/sb-compile-edge-runtime/node_modules/localhost/google-auth-library/9.8.0/build/src/auth/jwtclient.js:154:24) {
  config: {
    method: "POST",
    url: "https://www.googleapis.com/oauth2/v4/token",
    data: {
      grant_type: "<<REDACTED> - See `errorRedactor` option in `gaxios` for configuration>.",
      assertion: "<<REDACTED> - See `errorRedactor` option in `gaxios` for configuration>."
    },
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      "User-Agent": "google-api-nodejs-client/9.8.0",
      "x-goog-api-client": "gl-node/20.11.1",
      Accept: "application/json"
    },
    responseType: "json",
    retryConfig: {
      httpMethodsToRetry: [ "POST" ],
      currentRetryAttempt: 2,
      retry: 3,
      noResponseRetries: 2,
      statusCodesToRetry: [ [ 100, 199 ], [ 408, 408 ], [ 429, 429 ], [ 500, 599 ] ]
    },
    paramsSerializer: [Function: paramsSerializer],
    body: "<<REDACTED> - See `errorRedactor` option in `gaxios` for configuration>.",
    validateStatus: [Function: validateStatus],
    errorRedactor: [Function: defaultErrorRedactor]
  },
  response: undefined,
  error: FetchError: request to https://www.googleapis.com/oauth2/v4/token failed, reason: error sending request for url (https://www.googleapis.com/oauth2/v4/token): http2 error: stream error received: unspecific protocol error detected
    at HttpsClientRequest.<anonymous> (file:///tmp/sb-compile-edge-runtime/node_modules/localhost/node-fetch/2.7.0/lib/index.js:1501:11)
    at HttpsClientRequest.emit (ext:deno_node/_stream.mjs:1851:9)
    at node:http:467:16
    at eventLoopTick (ext:core/01_core.js:168:7) {
    message: "request to https://www.googleapis.com/oauth2/v4/token failed, reason: error sending request for url "... 116 more characters,
    type: "system",
    errno: undefined,
    code: undefined
  },
  [Symbol("gaxios-gaxios-error")]: "6.5.0"
}
```

## To Reproduce

Create an edge function which contains the following code (service-account.json which downloaded from firebase when creating a new private key):

```
import { JWT } from "npm:google-auth-library@9";

const getAccessToken = (
  { clientEmail, privateKey }: { clientEmail: string; privateKey: string },
): Promise<string> => {
  return new Promise((resolve, reject) => {
    const jwtClient = new JWT({
      email: clientEmail,
      key: privateKey,
      scopes: ["https://www.googleapis.com/auth/firebase.messaging"],
    });
    jwtClient.authorize((err, token) => {
      if (err) {
        reject(err);
        return;
      }
      resolve(token!.access_token!);
    });
  });
};

  const { default: serviceAccount } = await import("../service-account.json", {
    with: { type: "json" },
  });

  const accessToken = await getAccessToken({
    clientEmail: serviceAccount.client_email,
    privateKey: serviceAccount.private_key,
  });
```

## Expected behavior

No error

## Additional context

No change to my edge function has occured and the error started sometime between 10th June and 18th June (my edge function was not run between these dates)

I have tried downgrading google-auth-library (versions 9.10 down to 9.0) but error still occured.

I have also run this code locally using the latest version of deno (1.44.2) and deno version 1.43.0 (same as current supabase edge-runtime) and no error occurs

**Comment by Jonny1987** [comment]
In this old issue (https://github.com/denoland/deno/issues/16923) which looks the same, someone mentioned using axios to make a request causes the same error and I can confirm this happen when running in an edge function, but not when running a script directly with deno.

My edge function (which causes the error):

```
import axios from "npm:axios";
Deno.serve(async (req) => {
  await axios.get("https://google.com")
    .then(function (response) {
      // handle success
      console.log("success");
    }).catch((err) => {
      console.log("error", err.cause);
    });
  try {
    return new Response(
      JSON.stringify({}),
      {
        headers: { "Content-Type": "application/json" },
      },
    );
  } catch (error) {
    console.log(`error: ${error.message}`);
    return new Response(
      JSON.stringify({ error: "Server Error", details: error.message }),
      {
        headers: { "Content-Type": "application/json" },
        status: 500,
      },
    );
  }
});
```

But running this script with `deno run` works:

```
import axios from "npm:axios";
await axios.get("https://google.com")
.then(function (response) {
  // handle success
  console.log("success");
}).catch((err) => {
  console.log("error", err.cause);
});

```

**Comment by derekchan916** [comment]
Been getting the same issue. My code is literally exactly the same as yours so nothing to add. Thanks for reporting it!
