### ISSUE TITLE
Self-Host: Storage Resumable TUS Upload to S3 throws AccessDenied

### ISSUE THREAD

**Issue by Obeyed** [supabase/supabase#27409]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am using the docker self-deployment guide.

Fetching existing storage objects from S3 works fine. The Standard file upload also works fine.

When using the Resumable TUS upload then an AccessDenied error is thrown. I believe the access is denied by AWS S3 which makes me believe that some secrets are not set correctly in the storage container.

This issue seems to start from storage release [v0.44.1](https://github.com/supabase/storage/tree/v0.44.1) and exists with the latest v1.5.1 - I tried with [v0.43.12](https://github.com/supabase/storage/tree/v0.43.12) which seems to work as expected.

## To Reproduce

I must be missing some config, environment variable, or something. I cannot figure out what is the cause.

It seems there was an upgrade of the tus server after storage-api:v0.43.12 which may be the cause of some misconfiguration.

The requests seem to be forwarded fine through kong to the storage container.

I am not using realtime, imgproxy, functions, analytics, vector, nor minio. **These are all disabled.**

These are the environment variables that are set for the storage container to connect with AWS S3:

```
      ANON_KEY: ${ANON_KEY}
      SERVICE_KEY: ${SERVICE_ROLE_KEY}
      POSTGREST_URL: http://rest:3000
      PGRST_JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: postgres://supabase_storage_admin:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      FILE_SIZE_LIMIT: 5000000000000
      STORAGE_BACKEND: s3
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${S3_REGION}
      REGION: ${S3_REGION}
      # S3 urls will be {GLOBAL_BUCKET}/{TENANT_ID}/{DB_STORAGE_BUCKET_ID}/{CHOSEN_PATH_TO_FILE}
      GLOBAL_S3_BUCKET: ${S3_GLOBAL_S3_BUCKET}
      TENANT_ID: ${TENANT_ENVIRONMENT}
      IS_MULTITENANT: "false"
```

## Expected behavior

This is the storage api log for a successful POST request from storage-api:v0.43.12:

```
{
    "level": 30,
    "time": "2024-06-20T08:23:01.476Z",
    "pid": 1,
    "hostname": "b8fd9f9ff5ed",
    "reqId": "req-10",
    "tenantId": "local",
    "project": "local",
    "type": "request",
    "req": {
        "traceId": "req-10",
        "method": "POST",
        "url": "/upload/resumable",
        "headers": {
            "host": "storage:5000",
            "x_forwarded_proto": "http",
            "x_forwarded_host": "localhost",
            "x_forwarded_port": "8000",
            "x_real_ip": "172.22.0.1",
            "content_length": "6291456",
            "upload_length": "45955876",
            "user_agent": "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36",
            "x_upsert": "true",
            "content_type": "application/offset+octet-stream",
            "tus_resumable": "1.0.0",
            "upload_metadata": "bucketName bWF0Y2gtY2FtLWlucHV0,objectName YzI5YmUxYmUtODcwMy00YzBlLTliMGYtMGY4YmNhMDVjZTZkLzE3MTg4NzE3Nzc3MTQtaGtnY3VjNmlpby5tcDQ=,contentType dmlkZW8vbXA0,cacheControl ODY0MDA=",
            "accept": "*/*",
            "referer": "http://localhost:5173/"
        },
        "hostname": "storage:5000",
        "remoteAddress": "192.168.192.2",
        "remotePort": 39914
    },
    "res": {
        "statusCode": 201,
        "headers": {
            "tus_resumable": "1.0.0",
            "content_length": 0
        }
    },
    "responseTime": 3738.56052005291,
    "owner": "c29be1be-8703-4c0e-9b0f-0f8bca05ce6d",
    "msg": "local | POST | 201 | 192.168.192.2 | req-10 | /upload/resumable | Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36"
}

```

## Screenshots

This is the stack trace from the storage-api:v1.5.1 logs.

```
{
    "level": 50,
    "time": "2024-06-19T13:27:24.026Z",
    "pid": 1,
    "hostname": "ab38aff8e9fe",
    "reqId": "req-2q",
    "tenantId": "local",
    "project": "local",
    "type": "request",
    "req": {
        "region": "eu-west-1",
        "traceId": "req-2q",
        "method": "POST",
        "url": "/upload/resumable",
        "headers": {
            "host": "storage:5000",
            "x_forwarded_proto": "http",
            "x_forwarded_host": "localhost",
            "x_forwarded_port": "8000",
            "x_real_ip": "172.22.0.1",
            "content_length": "6291456",
            "upload_length": "545817496",
            "user_agent": "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36",
            "x_upsert": "true",
            "content_type": "application/offset+octet-stream",
            "tus_resumable": "1.0.0",
            "upload_metadata": "bucketName bWF0Y2gtY2FtLWlucHV0,objectName YzI5YmUxYmUtODcwMy00YzBlLTliMGYtMGY4YmNhMDVjZTZkLzE3MTg4MDM2NDI1NzgtNmZ1djN3bHhidS5tcDQ=,contentType dmlkZW8vbXA0,cacheControl ODY0MDA=",
            "accept": "*/*",
            "referer": "http://localhost:5173/"
        },
        "hostname": "storage:5000",
        "remoteAddress": "192.168.96.3",
        "remotePort": 36716
    },
    "res": {
        "statusCode": 500,
        "headers": {
            "tus_resumable": "1.0.0",
            "content_length": "53"
        }
    },
    "responseTime": 1391.9478950500488,
    "error": {
        "raw": "{\"name\":\"AccessDenied\",\"$fault\":\"client\",\"$metadata\":{\"httpStatusCode\":403,\"requestId\":\"2CXJCNYVC6AN16WR\",\"extendedRequestId\":\"H4yO8NDY4KoyZXv4DAbwgsq6xmCl5SVik3xy0dIfvWdiZIjymq7Kd1M0tSvyCI5w/Dc7sqxMTsI=\",\"attempts\":1,\"totalRetryDelay\":0},\"Code\":\"AccessDenied\",\"RequestId\":\"2CXJCNYVC6AN16WR\",\"HostId\":\"H4yO8NDY4KoyZXv4DAbwgsq6xmCl5SVik3xy0dIfvWdiZIjymq7Kd1M0tSvyCI5w/Dc7sqxMTsI=\",\"message\":\"Access Denied\"}",
        "name": "AccessDenied",
        "message": "Access Denied",
        "stack": "AccessDenied: Access Denied\n    at throwDefaultError (/app/node_modules/@smithy/smithy-client/dist-cjs/index.js:838:20)\n    at /app/node_modules/@smithy/smithy-client/dist-cjs/index.js:847:5\n    at de_CommandError (/app/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4756:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /app/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20\n    at async /app/node_modules/@aws-sdk/middleware-signing/dist-cjs/index.js:192:18\n    at async /app/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38\n    at async /app/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/index.js:173:18\n    at async /app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:97:20\n    at async /app/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:120:14"
    },
    "owner": "c29be1be-8703-4c0e-9b0f-0f8bca05ce6d",
    "resources": [],
    "operation": "storage.tus.upload.create",
    "msg": "local | POST | 500 | 192.168.96.3 | req-2q | /upload/resumable | Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36"
}
```

## System information

- OS: Linux Ubuntu
- Browser (if applies): brave
- Version of supabase-js: 2.43.4
- Version of Node.js:

**Comment by Obeyed** [comment]
I just got a breakthough. It seems the new aws-sdk packages require different permission and boundaries on AWS. Will post more details when I know specifics.
