### ISSUE TITLE
Vercel NextJS with-supabase example does not work with latest node20 runtime

### ISSUE THREAD

**Issue by chrisui** [supabase/supabase#28402]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Node fetch failure when trying to use `auth` api.

```
TypeError: fetch failed
    at node:internal/deps/undici/undici:12502:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ah (/var/task/apps/www/.next/server/chunks/125.js:1:75941)
    at async au (/var/task/apps/www/.next/server/chunks/125.js:1:75685)
    at async aP.signInAnonymously (/var/task/apps/www/.next/server/chunks/125.js:1:86849)
    at async P (/var/task/apps/www/.next/server/app/quiz/hair-type/page.js:1:5165)
    at async /var/task/node_modules/.pnpm/next@14.2.3_@babel+core@7.25.2_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:418
    at async rP (/var/task/node_modules/.pnpm/next@14.2.3_@babel+core@7.25.2_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:7978)
    at async r5 (/var/task/node_modules/.pnpm/next@14.2.3_@babel+core@7.25.2_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:1139)
    at async es (/var/task/node_modules/.pnpm/next@14.2.3_@babel+core@7.25.2_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:26320) {
  [cause]: Error: connect ECONNREFUSED 127.0.0.1:54321
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 54321
  }
}
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Following the guide to use the next boilerplate and create a project with supabase auth. only change I made was to use `supabase.auth.signInAnonymously` within a server action.

I deployed to vercel (where default runtime is the latest, node20) and encountered the error. Tore my hair out for a while wondering if I was missing env (particularly because I saw the `127.0.0.1` portion but I think a bit of a red herring in the end) and eventually tried to downgrade the runtime to node18 and redeploy. It worked.

https://vercel.com/templates/next.js/supabase

## Expected behavior

No error when using node 20.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [chrome
- Version of supabase-js: "@supabase/ssr": "^0.4.0", "@supabase/supabase-js": "^2.45.0",
- Version of Node.js: 20

## Additional context

The vercel template page says to report any issues here.

**Comment by encima** [comment]
Thanks for opening, can you confirm this is only occurring with node 20 and not node 22?

Also, fetch has changed a bit between 20 and 21 but you can use a custom fetch implementation (see [here](https://www.npmjs.com/package/@supabase/supabase-js)). Could you test using a different fetch implementation and report back?
