### ISSUE TITLE
Getting a `ConnectorError` issue from Prisma when connecting to Supabase DB in local development

### ISSUE THREAD

**Issue by kevinreber** [supabase/supabase#28566]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
Getting a `ConnectorError` issue from Prisma when connecting to Supabase DB in local development.

My tech stack is:
- Built with Remix
- Prisma for DB management
- DB hosted on Supabase

`package.json`
```json
{
  "private": true,
  "sideEffects": false,
  "type": "module",
  "scripts": {
    "build": "remix build",
    "dev": "yarn run check-env-file && remix dev --manual",
    "start": "remix-serve ./build/index.js",
    "typecheck": "tsc",
    "check-env-file": "node ./scripts/check-env-file.mjs",
    "postinstall": "prisma generate",
    "stripe:listen": "stripe listen --forward-to localhost:3000/webhook",
    "format": "prettier --write .",
    "lint": "eslint --cache --cache-location ./node_modules/.cache/eslint ."
  },
  "dependencies": {
    "@heroicons/react": "^2.0.18",
    "@prisma/client": "^5.18.0",
    "@remix-run/css-bundle": "^2.2.0",
    "@remix-run/express": "^2.2.0",
    "@remix-run/node": "2.2.0",
    "@remix-run/react": "2.2.0",
    "@types/bcryptjs": "^2.4.6",
    "cross-env": "^7.0.3",
    "dotenv": "^16.0.3",
    "lucide-react": "^0.312.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "remix-auth": "^3.6.0",
    "remix-auth-socials": "^2.0.5",
    "remix-utils": "^7.1.0",
    "sonner": "^1.2.3",
    "tailwind-merge": "^2.2.0",
     .....
  },
  "devDependencies": {
    "@remix-run/dev": "2.2.0",
    "@remix-run/serve": "2.2.0",
    "@types/react-dom": "^18.0.11",
    "prisma": "^5.18.0",
    "supabase": "1.187.10",
    "tailwindcss": "^3.3.3",
    "typescript": "^5.3.0",
    "zx": "7.0.8",
     .....
  },
  "engines": {
    "node": ">20.0.0"
  }
}

```

Issue only seems to happen during local development. Deployed things work fine, so I'm assuming it may be a Supabase issue, but verified there isn't any whitelisting setup in Supabase.
```sh
~ npx supabase network-restrictions --project-ref XXXXXXXXX get --experimental 
DB Allowed IPv4 CIDRs: <nil>
DB Allowed IPv6 CIDRs: <nil>
```

I'm getting an error for every query being made - errors below
```sh
 💿  remix dev

 info  building...
 info  built (2.1s)
[remix-serve] http://localhost:3000 (http://192.168.86.112:3000)
prisma:info Starting a postgresql pool with 25 connections.

prisma:query - 90ms - SELECT COUNT(*) FROM (SELECT "public"."Collection"."id" FROM "public"."Collection" WHERE "public"."Collection"."userId" = $1 OFFSET $2) AS "sub"
prisma:error 
Invalid `prisma.collection.count()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s0\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
prisma:query - 88ms - SELECT "public"."User"."id", "public"."User"."name", "public"."User"."username", "public"."User"."email", "public"."User"."image", "public"."User"."createdAt", "public"."User"."credits" FROM "public"."User" WHERE ("public"."User"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:error 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s1\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s1\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at _n.handleRequestError (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@prisma/client/runtime/library.js:121:7939)
    at _n.handleAndLogRequestError (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@prisma/client/runtime/library.js:121:7057)
    at _n.request (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@prisma/client/runtime/library.js:121:6741)
    at l (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@prisma/client/runtime/library.js:130:9355)
    at getLoggedInUserSSOData (file:///Users/kreber/Documents/code/personal/ai-icon-generator/build/index.js?t=1723450348975.0032:648:18)
    at loader (file:///Users/kreber/Documents/code/personal/ai-icon-generator/build/index.js?t=1723450348975.0032:4711:25)
    at Object.callRouteLoaderRR (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
    at callLoaderOrAction (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@remix-run/router/router.ts:3842:16)
    at async Promise.all (index 0)
    at loadRouteData (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@remix-run/router/router.ts:3153:19) {
  clientVersion: '5.18.0'
}
PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s1\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at _n.handleRequestError (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@prisma/client/runtime/library.js:121:7939)
    at _n.handleAndLogRequestError (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@prisma/client/runtime/library.js:121:7057)
    at _n.request (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@prisma/client/runtime/library.js:121:6741)
    at l (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@prisma/client/runtime/library.js:130:9355)
    at getLoggedInUserSSOData (file:///Users/kreber/Documents/code/personal/ai-icon-generator/build/index.js?t=1723450348975.0032:648:18)
    at loader (file:///Users/kreber/Documents/code/personal/ai-icon-generator/build/index.js?t=1723450348975.0032:4711:25)
    at Object.callRouteLoaderRR (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
    at callLoaderOrAction (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@remix-run/router/router.ts:3842:16)
    at async Promise.all (index 0)
    at loadRouteData (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@remix-run/router/router.ts:3153:19) {
  clientVersion: '5.18.0'
}
```

`prisma/schema.prisma`
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id           String        @id @default(cuid())
  name         String?
  username     String       @unique
  email        String       @unique
  password     Password?
  image        String?
  credits      Int           @default(5)
  accounts     Account[]
  sessions     Session[]
  images       Image[]
  createdAt    DateTime      @default(now())
  updatedAt    DateTime?     @updatedAt
  comments     Comment[]
  imageLikes   ImageLike[]
  commentLikes CommentLike[]
  collections  Collection[]
  roles        Role[]
}

model Collection {
  id          String               @id @default(cuid())
  createdAt   DateTime             @default(now())
  updatedAt   DateTime             @updatedAt
  title       String
  description String?
  user        User                 @relation(fields: [userId], references: [id], onDelete: Cascade)
  userId      String
  images      CollectionHasImage[]

  @@index([userId])
}

.....
```

Example of queries that are failing
```ts
export const getLoggedInUserSSOData = async (
  userGoogleData: UserGoogleData,
  request: Request,
) => {
  const userId = userGoogleData.id;
  let userData = await prisma.user.findUnique({
    where: { id: userId },
    select: {
      id: true,
      name: true,
      username: true,
      email: true,
      image: true,
      createdAt: true,
      credits: true,
      collections: {
        select: {
          id: true,
          title: true,
          description: true,
          images: {
            select: {
              imageId: true,
            },
          },
        },
      },
      roles: {
        select: {
          name: true,
          permissions: {
            select: {
              action: true,
              entity: true,
              access: true,
            },
          },
        },
      },
    },
  });

  if (!userData?.id) {
    const { name, email, picture } = userGoogleData._json;

    // If new user is created, no collections will exist
    // @ts-ignore
    userData = await prisma.user.create({
      data: {
        id: userId,
        name,
        username: userGoogleData.displayName,
        email,
        image: picture,
        roles: { connect: { name: "user" } },
      },
    });
  }

  return userData;
};


export const getUserCollections = async (
  userId: string,
  page = DEFAULT_CURRENT_PAGE,
  pageSize = DEFAULT_PAGE_SIZE,
) => {
  const count = await prisma.collection.count({
    where: {
      userId,
    },
  });
  const collections = await prisma.collection.findMany({
    take: pageSize,
    skip: (page - 1) * pageSize,
    where: {
      userId,
    },
    orderBy: {
      createdAt: "desc",
    },
    select: {
      id: true,
      title: true,
      description: true,
      user: {
        select: {
          id: true,
          username: true,
        },
      },
      createdAt: true,
      updatedAt: true,
      images: {
        select: {
          id: true,
        },
      },
    },
  });

  return { collections, count };
};

```

## To Reproduce

Attempt to connect to my Supabase DB locally (example below)

```sh
 💿  remix dev

 info  building...
 info  built (2.1s)
[remix-serve] http://localhost:3000 (http://192.168.86.112:3000)
prisma:info Starting a postgresql pool with 25 connections.

prisma:query - 90ms - SELECT COUNT(*) FROM (SELECT "public"."Collection"."id" FROM "public"."Collection" WHERE "public"."Collection"."userId" = $1 OFFSET $2) AS "sub"
prisma:error 
Invalid `prisma.collection.count()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s0\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
prisma:query - 88ms - SELECT "public"."User"."id", "public"."User"."name", "public"."User"."username", "public"."User"."email", "public"."User"."image", "public"."User"."createdAt", "public"."User"."credits" FROM "public"."User" WHERE ("public"."User"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:error 
Invalid `prisma.user.findUnique()` invocation:
```

## Expected behavior

Should be able to connect and make queries to Supabase DB with no issues.

## System information

- OS: macOS
- Browser (if applies): chrome
- Shell: zsh, bash
- Version of `supabase`: `1.187.10`
- Version of `Node`: `>20.0.0`

## Additional context
- Opened issue in `prisma`: https://github.com/prisma/prisma/issues/24798#issuecomment-2283409758

**Comment by encima** [comment]
Thanks for opening @kevinreber, can I confirm that this issue does not occur if you do not use Accelerate?

**Comment by kevinreber** [comment]
hey @encima 👋 
I am not using Prisma Accelerate in the examples/resources above ⬆️ 
I can try running with Accelerate if you think it may help. Will try setting it up and see if anything interesting happens 🤞

**Comment by encima** [comment]
@kevinreber can you provide your connection string (with sensitive info removed) for the local dev as well as the string you are using for hosted?

**Comment by kevinreber** [comment]
@encima 
Here is my DB URL: `postgres://postgres.<SUPABASE_PROJECT>:<DB_PASSWORD>@aws-0-us-east-1.pooler.supabase.com:6543/postgrese`

and here is a link to my repo if it helps: https://github.com/kevinreber/ai-icon-generator

**Comment by encima** [comment]
@kevinreber When you say "local development", do you mean running the project locally on your machine using `supabase start`?

**Comment by kevinreber** [comment]
@encima Accessing my Supabase DB from my local machine using the `prisma/client` to establish the connection.
I'm also using the same URL and setup in prod

`prisma/schema.prisma` file
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")  # <- 🟡 connects to Supabase DB URL here
}

model User {
  id           String        @id @default(cuid())
  name         String?
  username     String       @unique
  email        String       @unique
  password     Password?
  image        String?
  credits      Int           @default(5)
  accounts     Account[]
  sessions     Session[]
  images       Image[]
  createdAt    DateTime      @default(now())
  updatedAt    DateTime?     @updatedAt
  comments     Comment[]
  imageLikes   ImageLike[]
  commentLikes CommentLike[]
  collections  Collection[]
  roles        Role[]
}

model Collection {
  id          String               @id @default(cuid())
  createdAt   DateTime             @default(now())
  updatedAt   DateTime             @updatedAt
  title       String
  description String?
  user        User                 @relation(fields: [userId], references: [id], onDelete: Cascade)
  userId      String
  images      CollectionHasImage[]

  @@index([userId])
}

.....
```

**Comment by encima** [comment]
@kevinreber thought so, thanks for confirming! 
I would suggest modifying your string to use the same parameters recommended in the Prisma/Supabase [docs](https://supabase.com/partners/integrations/prisma)

Out of curiosity, if you use a direct connection, do you see the same error?

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
