### ISSUE TITLE
 error: AuthRetryableFetchError: fetch failed

### ISSUE THREAD

**Issue by rakhmonovbekzod** [supabase/supabase#29455]
I have  this error with Next.js 
![image](https://github.com/user-attachments/assets/7f01d0a4-04c6-41e8-bee5-53b745ff70d3)

**Comment by rakhmonovbekzod** [comment]
![image](https://github.com/user-attachments/assets/e3d11823-d8a8-4b63-a929-1c9fa7f8206d)

**Comment by apugoneappu** [comment]
+1 getting the same error, but only on localhost!

**Comment by trevorpfiz** [comment]
> +1 getting the same error, but only on localhost!

just started getting this as well? don't know what changed?

**Comment by apugoneappu** [comment]
(I use WSL2 on Windows 10)

I suddenly had a DNS error on WSL2 (ubuntu) but not on Windows.

`ping github.com` was working on PowerShell but not on Ubuntu.

So I followed the link below to change my nameserver to Google (8.8.8.8) and it worked! 

https://superuser.com/questions/1533291/how-do-i-change-the-dns-settings-for-wsl2

**Comment by themuslimswe** [comment]
Hi guys,

I am getting the same error and I'm not really sure what the reason could be. Did anyone find a fix?

**Comment by BinaryShrub** [comment]
I'm getting the same error: https://github.com/supabase/supabase/issues/32943

```
{
  data: { user: null },
  error: AuthRetryableFetchError: error sending request for url (http://localhost:54321/auth/v1/user)
    at _handleRequest (file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@supabase/auth-js/2.67.3/dist/main/lib/fetch.js:111:15)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async _request (file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@supabase/auth-js/2.67.3/dist/main/lib/fetch.js:95:18)
    at async SupabaseAuthClient._getUser (file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@supabase/auth-js/2.67.3/dist/main/GoTrueClient.js:881:24)
    at async SupabaseAuthClient.getUser (file:///var/tmp/sb-compile-edge-runtime/node_modules/localhost/@supabase/auth-js/2.67.3/dist/main/GoTrueClient.js:870:20)
    at async Object.handler (file:///home/justin/workspace/trade-yak/supabase/functions/importer/index.ts:61:16)
    at async respond (ext:sb_core_main_js/js/http.js:197:14) {
    __isAuthError: true,
    name: "AuthRetryableFetchError",
    status: 0,
    code: undefined
  }
}
```

**Comment by BinaryShrub** [comment]
https://github.com/supabase/supabase/pull/32946 was the solution for me

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.
