### ISSUE TITLE
"Error: FILE_STORAGE_BACKEND_PATH env variable not set" when installing the latest storage docker

### ISSUE THREAD

**Issue by yuvalkarmi** [supabase/supabase#29813]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

In the last 24 hours, running any command through the supabase cli that requires the supabase storage docker (latest version) yields:
```
Error: FILE_STORAGE_BACKEND_PATH env variable not set
    at new FileBackend (/app/dist/storage/backend/file.js:64:13)
    at createStorageBackend (/app/dist/storage/backend/index.js:35:22)
    at Object.<anonymous> (/app/dist/storage/events/base-event.js:36:64)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/app/dist/storage/events/webhook.js:34:25)

Node.js v20.18.0
error running container: exit 1
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Open a command line window
2. Type any command that attempts to use the storage docker (e.g. `supabase db diff --use-migra "some_migration" -f "some_migration" --linked --schema "public, storage"`)
3. Watch as supabase tries to fetch the latest docker image
4. Receive error above

## Expected behavior

Supabase storage docker should install normally

## System information

- OS: macOS 14.2.1 (M1 Mac)
- Version of Node.js: v20.18.0

## Additional context

This started happening in the last 24 hours. I haven't made any changes to my system (e.g. have not changed my path, terminal program, shell, etc).

**Comment by avallete** [comment]
I there, thank's for reporting. This should be fixed by: https://github.com/supabase/cli/issues/2738

The fix is e available in version `1.204.3` of the cli.
