### ISSUE TITLE
Nuxt 3 "web app demos" isn't working anymore

### ISSUE THREAD

**Issue by 6pri6** [supabase/supabase#29826]
Hi, 
I followed this whole supabase example :
[https://supabase.com/docs/guides/getting-started/tutorials/with-nuxt-3](url)

But I guess it's not working anymore, as I followed the whole tutos, and the app demo isn't working 🤒

The issue is the following one :
"500
useSupabaseUser is not defined
at _sfc_main.setup (C:\Users\cypri\OneDrive\Bureau\codes\nuxt-starter\test\app\pages\index.js:54:23)
at callWithErrorHandling (C:\Users\cypri\OneDrive\Bureau\codes\nuxt-starter\test\node_modules\vue\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:200:19)
at setupStatefulComponent (C:\Users\cypri\OneDrive\Bureau\codes\nuxt-starter\test\node_modules\vue\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7783:25)
at setupComponent (C:\Users\cypri\OneDrive\Bureau\codes\nuxt-starter\test\node_modules\vue\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7744:36)
at renderComponentVNode (C:\Users\cypri\OneDrive\Bureau\codes\nuxt-starter\test\node_modules\vue\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:645:15)
at renderVNode (C:\Users\cypri\OneDrive\Bureau\codes\nuxt-starter\test\node_modules\vue\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:779:14)
at renderComponentSubTree (C:\Users\cypri\OneDrive\Bureau\codes\nuxt-starter\test\node_modules\vue\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:730:7)
at renderComponentVNode (C:\Users\cypri\OneDrive\Bureau\codes\nuxt-starter\test\node_modules\vue\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:664:12)
at renderVNode (C:\Users\cypri\OneDrive\Bureau\codes\nuxt-starter\test\node_modules\vue\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:779:14)"

As I'm a beginner and still learning Nuxt and Supabase, I dont get why this isn't working. 
I didn't found how to import the useSupabaseUser function.

**Comment by 6pri6** [comment]
Resolved : the doc didnt mentionned to add the supabase module within the modules in the nuxt.config.ts file.
