### ISSUE TITLE
TypeError: cannot read headers: request closed

### ISSUE THREAD

**Issue by shivamklr** [supabase/supabase#30131]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When I run the edge function it runs fine locally, but gives an error on the deployment. I am deploying it on the supabase platform.
```
{
  "event_message": "TypeError: cannot read headers: request closed\n    at get headerList (ext:deno_fetch/23_request.js:125:17)\n    at request.<computed> (ext:deno_fetch/23_request.js:595:60)\n    at get [headers] (ext:deno_fetch/23_request.js:260:46)\n    at get headers (ext:deno_fetch/23_request.js:475:16)\n    at stdHttp (https://deno.land/x/grammy@v1.26.0/convenience/frameworks.ts:240:17)\n    at https://deno.land/x/grammy@v1.26.0/convenience/webhook.ts:24:75\n    at Object.handler (file:///Users/admin/Projects/upwork/NBA%20Telegram%20Project/supabase/functions/telegram-bot/index.ts:56:18)\n    at respond (ext:sb_core_main_js/js/http.js:163:38)\n    at handleHttp (ext:sb_core_main_js/js/http.js:123:5)\n    at eventLoopTick (ext:core/01_core.js:168:7)\n",
  "id": "972863b5-6776-4db4-b03b-04a0981e2101",
  "metadata": [
    {
      "boot_time": null,
      "cpu_time_used": null,
      "deployment_id": "vouhyzcyxtygaxsxqomj_64082488-b32b-498b-9fda-cd0251acb5be_3",
      "event_type": "Log",
      "execution_id": "e1068f20-0852-4977-bbbf-267526647479",
      "function_id": "64082488-b32b-498b-9fda-cd0251acb5be",
      "level": "error",
      "memory_used": [],
      "project_ref": "vouhyzcyxtygaxsxqomj",
      "reason": null,
      "region": "eu-central-1",
      "served_by": "supabase-edge-runtime-1.58.13 (compatible with Deno v1.45.2)",
      "timestamp": "2024-10-27T22:47:43.861Z",
      "version": "3"
    }
  ],
  "timestamp": 1730069264904872
}
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Ran this locally
```function.ts
// Use this to register and save user to the db
import {
  Bot,
  webhookCallback,
} from "https://deno.land/x/grammy@v1.26.0/mod.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

// Initialize Supabase client
const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
const supabaseAnonKey = Deno.env.get("SUPABASE_ANON_KEY")!;
const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Initialize bot
const token = Deno.env.get("BOT_TOKEN");  
if (!token) throw new Error("BOT_TOKEN is unset");
const bot = new Bot(token);

const supaBaseSecret = Deno.env.get("SECRET");
if(!supaBaseSecret) throw new Error("SECRET is unset");

// Handle /start command
bot.command("start", async (ctx) => {
  const user = ctx.from;
  const chatId = ctx.chat.id.toString();

  if (!user || user.is_bot) {
    await ctx.reply("Sorry, couldn't get your user information.");
    return;
  }

  try {
    // Check if user already exists
    const { data: existingUser } = await supabase
      .from("telegram_users")
      .select()
      .eq("telegram_id", user.username || user.id.toString())
      .single();

    if (existingUser) {
      await ctx.reply("Welcome back! You're already registered.");
      return;
    }

    // Insert new user
    const { data, error } = await supabase
      .from("telegram_users")
      .insert([
        {
          telegram_id: user.username || user.id.toString(),
          chat_id: chatId,
          first_name: user.first_name,
          last_name: user.last_name || null,
          is_approved: false, // Default to not approved
        },
      ])
      .select()
      .single();

    if (error) throw error;

    return await ctx.reply(
      "Thanks for registering! Your updates will begin once your account is approved.",
    );
  } catch (error) {
    console.error("Error registering user:", error);
    return await ctx.reply(
      "Sorry, there was an error registering you. Please try again later.",
    );
  }
});

bot.command("ping", (ctx) => ctx.reply(`Pong! ${new Date()}`));

const handleUpdate = webhookCallback(bot, "std/http");

Deno.serve(async (req) => {
  try {
    const url = new URL(req.url);
    if (url.searchParams.get("secret") !== supaBaseSecret) {
      return new Response("not allowed", { status: 405 });
    }
    return await handleUpdate(req);
  } catch (err) {
    console.error(err);
  }
  return new Response();
});

```
2. Deploy it to Supabase Platform
3. Try the "/start" command from the Telegram Bot.
4. Check Logs on Supabase Edge Functions page.

## Expected behavior

The function should execute and then return successfully, like it does in the docker container.

## System information

- OS: [Windows]
- Using ngrok 

## Additional context

I tried changing the version of grammy@v1.26.0 and grammy@v1.30.0 still the same result.

**Comment by shivamklr** [comment]
Closing as duplicate here.
https://github.com/supabase/edge-runtime/issues/435

**Comment by shivamklr** [comment]
Shifted to the right repo.
