### ISSUE TITLE
Selfhosted Supavisor Pooler Keeps Restarting

### ISSUE THREAD

**Issue by InvixGG** [supabase/supabase#30210]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The Supavisor pooler in my self-hosted Supabase setup keeps restarting. I'm not sure if that's due to this syntax error in the `pooler.exs` file. The error suggests an unexpected carriage return (U+000D) on line 30 of `pooler.exs`.

### Error Message

```plaintext
2024-10-31 18:00:20 ** (SyntaxError) nofile:30:4: unexpected token: carriage return (column 4, code point U+000D)
2024-10-31 18:00:20     |
2024-10-31 18:00:20  30 | end
2024-10-31 18:00:20     |    ^
2024-10-31 18:00:20     (elixir 1.14.3) lib/code.ex:424: Code.validated_eval_string/3
```

## To Reproduce

1. Go through the selfhost setup from Supabase.

## Expected behavior

The Supavisor pooler should start and run without encountering a syntax error in the `pooler.exs` file, as there are no apparent syntax issues in the file.

## Screenshots

![image](https://github.com/user-attachments/assets/3fcf9504-6084-4063-a671-6d503e0cc90c)

## System information

- **OS**: Windows 11
- **Supavisor Version**: 1.1.56
- **Elixir Version**: 1.14.3

## Additional context

Any help or guidance on troubleshooting this error further would be appreciated. Thank you!

**Comment by lherrman** [comment]
I got the same issue. Same OS and version. Is there a workaround?

**Comment by lherrman** [comment]
You're encountering a SyntaxError due to unexpected carriage return characters (\r, Unicode code point U+000D) in your configuration file. (docker/volumes/pooler/pooler.exs). You need to save the file with LF line ending. Easy way is to use VSCode.
In Visual Studio Code:
Click on the line ending indicator in the bottom-right corner of the window (it might display "CRLF").
Select "LF" to convert the file to Unix-style line endings.
Save the file.

**Comment by dhust** [comment]
Thanks @lherrman! That worked. Easy fix.

**Comment by nejcpetan** [comment]
> You're encountering a SyntaxError due to unexpected carriage return characters (\r, Unicode code point U+000D) in your configuration file. (docker/volumes/pooler/pooler.exs). You need to save the file with LF line ending. Easy way is to use VSCode. In Visual Studio Code: Click on the line ending indicator in the bottom-right corner of the window (it might display "CRLF"). Select "LF" to convert the file to Unix-style line endings. Save the file.

Dude.. Thanks!!! This fixed it immediately!

**Comment by ShiqiRao** [comment]
Thanks @lherrman !

**Comment by NagaiKaminoke** [comment]
Thanks that solved the issue for me

**Comment by wim-gdwi** [comment]
This solved the issue for me as well.

**Comment by taqqi1214** [comment]
by changing python script by adding --remove-orphan removed the Warning msg you talked abt in the video

here's the revised version

**

def start_supabase():
59     """Start the Supabase services (using its compose file)."""
60     print("Starting Supabase services...")
61     run_command([
62         "docker", "compose", "-p", "localai", "-f", "supabase/docker/docker-compose.yml", "up", "-d", "--remove-orphans"
63     ])
64
65 def start_local_ai(profile=None):
66     """Start the local AI services (using its compose file)."""
67     print("Starting local AI services...")
68     cmd = ["docker", "compose", "-p", "localai"]
69     if profile and profile != "none":
70         cmd.extend(["--profile", profile])
71     cmd.extend(["-f", "docker-compose.yml", "up", "-d", "--remove-orphans"])
72     run_command(cmd)

**Comment by taqqi1214** [comment]
getting below error

Waiting for Supabase to initialize...
Starting local AI services...
Running: docker compose -p localai --profile cpu -f docker-compose.yml up -d --remove-orphans
[+] Running 20/20
✔ Container realtime-dev.supabase-realtime Removed 1.2s
✔ Container supabase-vector Removed 10.2s
✔ Container supabase-kong Removed 0.6s
✔ Container supabase-rest Removed 0.5s
✔ Container supabase-storage Removed 0.6s
✔ Container supabase-imgproxy Removed 0.5s
✔ Container supabase-db Removed 0.6s
✔ Container supabase-auth Removed 0.3s
✔ Container supabase-studio Removed 0.4s
✔ Container supabase-analytics Removed 6.9s
✔ Container supabase-meta Removed 0.4s
✔ Container supabase-pooler Removed 0.6s
✔ Container supabase-edge-functions Removed 10.1s
✔ Container qdrant Started 0.3s
✔ Container ollama Started 0.3s
✔ Container flowise Started 0.3s
✘ Container n8n-import service "n8n-import" didn't complete successfully: exit 1 3.8s
✔ Container open-webui Started 0.3s
✔ Container ollama-pull-llama Started 0.4s
✔ Container n8n Created 0.0s
service "n8n-import" didn't complete successfully: exit 1
Traceback (most recent call last):
File "/root/ai-agents-masterclass/local-ai-packaged/start_services.py", line 95, in
main()
File "/root/ai-agents-masterclass/local-ai-packaged/start_services.py", line 92, in main
start_local_ai(args.profile)
File "/root/ai-agents-masterclass/local-ai-packaged/start_services.py", line 72, in start_local_ai
run_command(cmd)
File "/root/ai-agents-masterclass/local-ai-packaged/start_services.py", line 19, in run_command
subprocess.run(cmd, cwd=cwd, check=True)
File "/usr/lib/python3.12/subprocess.py", line 571, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'compose', '-p', 'localai', '--profile', 'cpu', '-f', 'docker-compose.yml', 'up', '-d', '--remove-orphans']' returned non-zero exit status 1.

**Comment by Croestalker** [comment]
I'm also receiving this error.

**Comment by Meshad0w** [comment]
I keep getting this error over and over from supabase-kong: 2025-03-06 20:37:14 exec /bin/bash: input/output error
and another one from supabase-storage: 2025-03-06 20:38:05 exec /usr/local/bin/docker-entrypoint.sh: exec format error

Both containers keeps restarting over and over.. ANY clue as to why this keeps happening? I've done nothing but follow the exact steps listed in the guide. I've removed and redownloaded everything a few times now and same error keeps happening.

**Comment by Meshad0w** [comment]
So, I managed to resolve it. I ended up fully reinstalling docker. I figured out that it was issues with how docker handled the container, and not issues with the container itself.

**Comment by HNKRGLMSR** [comment]
Pooler keeps opening and closing. My problem is different from the title of this topic. error message: 
**(ErlangError) Erlang error: {:badarg, {~c"aead.c", 90}, ~c"Unknown cipher or invalid key size"}:**
I am getting an error on line 90. Can anyone help with this? end of line LF. I am also sure that the file was saved as UTF-8.

**Comment by 0x-Avant-Garde** [comment]
@HNKRGLMSR this sounds like your vault key (or another key) is the wrong length

**Comment by lmeneses1977** [comment]
Sorry I am new in Docker, etc., but I followed the instructions step by step. I am using MacOS. It looks like I also have a problem with supabase. 

<img width="906" alt="Image" src="https://github.com/user-attachments/assets/0ae0bc82-5819-480a-a9a2-777b7aed7592" />

The pooler error is 
2025-03-21 07:36:30 ** (ErlangError) Erlang error: {:badarg, {~c"aead.c", 90}, ~c"Unknown cipher or invalid key size"}:
2025-03-21 07:36:30 
2025-03-21 07:36:30   * 1st argument: Unknown cipher or invalid key size
2025-03-21 07:36:30 
2025-03-21 07:36:30     (crypto 5.5.2) crypto.erl:1746: :crypto.crypto_one_time_aead(:aes_256_gcm, "your-encryption-key-32-chars-exactly", <<141, 248, 26, 161, 114, 109, 91, 158, 113, 129, 44, 170, 198, 127, 96, 173>>, "478273lkajrw%sadfj", "AES256GCM", 16, true)
2025-03-21 07:36:30     (cloak 1.1.4) lib/cloak/ciphers/aes_gcm.ex:47: Cloak.Ciphers.AES.GCM.encrypt/2
2025-03-21 07:36:30     (supavisor 2.4.12) deps/cloak_ecto/lib/cloak_ecto/type.ex:42: Supavisor.Encrypted.Binary.dump/1
2025-03-21 07:36:30     (ecto 3.12.5) lib/ecto/type.ex:1048: Ecto.Type.process_dumpers/3
2025-03-21 07:36:30     (ecto 3.12.5) lib/ecto/repo/schema.ex:1110: Ecto.Repo.Schema.dump_field!/6
2025-03-21 07:36:30     (ecto 3.12.5) lib/ecto/repo/schema.ex:1124: anonymous fn/6 in Ecto.Repo.Schema.dump_fields!/5
2025-03-21 07:36:30     (stdlib 6.2) maps.erl:860: :maps.fold_1/4
2025-03-21 07:36:30     nofile:29: (file)
2025-03-21 07:36:30 [os_mon] memory supervisor port (memsup): Erlang has closed
2025-03-21 07:36:30 [os_mon] cpu supervisor port (cpu_sup): Erlang has closed

While the authentication error is:
2025-03-21 07:36:36 goroutine 1 [running]:
2025-03-21 07:36:36 net/url.(*URL).Query(0x4000046017?)
2025-03-21 07:36:36     /usr/local/go/src/net/url/url.go:1159 +0x18
2025-03-21 07:36:36 github.com/supabase/auth/cmd.migrate(0x400020fb68?, {0x0?, 0x0?, 0x0?})
2025-03-21 07:36:36     /go/src/github.com/supabase/auth/cmd/migrate_cmd.go:58 +0x1d4
2025-03-21 07:36:36 github.com/supabase/auth/cmd.init.func3(0x17fab60, {0x183f040?, 0x4?, 0xdcb7aa?})
2025-03-21 07:36:36     /go/src/github.com/supabase/auth/cmd/root_cmd.go:20 +0x24
2025-03-21 07:36:36 github.com/spf13/cobra.(*Command).execute(0x17fab60, {0x400003a0a0, 0x0, 0x0})
2025-03-21 07:36:36     /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x630
2025-03-21 07:36:36 github.com/spf13/cobra.(*Command).ExecuteC(0x17fab60)
2025-03-21 07:36:36     /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
2025-03-21 07:36:36 github.com/spf13/cobra.(*Command).Execute(...)
2025-03-21 07:36:36     /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
2025-03-21 07:36:36 github.com/spf13/cobra.(*Command).ExecuteContext(0xfb58e0?, {0xfb5aa0?, 0x4000146ec0?})
2025-03-21 07:36:36     /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:985 +0x48
2025-03-21 07:36:36 main.main()
2025-03-21 07:36:36     /go/src/github.com/supabase/auth/main.go:36 +0x128
2025-03-21 07:37:36 {"level":"info","msg":"Go runtime metrics collection started","time":"2025-03-21T06:37:36Z"}
2025-03-21 07:37:36 {"level":"info","msg":"received graceful shutdown signal","time":"2025-03-21T06:37:36Z"}
2025-03-21 07:37:36 panic: runtime error: invalid memory address or nil pointer dereference
2025-03-21 07:37:36 [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x227088]
2025-03-21 07:37:36 
2025-03-21 07:37:36 goroutine 1 [running]:
2025-03-21 07:37:36 net/url.(*URL).Query(0x4000046017?)
2025-03-21 07:37:36     /usr/local/go/src/net/url/url.go:1159 +0x18
2025-03-21 07:37:36 github.com/supabase/auth/cmd.migrate(0x4000141b68?, {0x0?, 0x0?, 0x0?})
2025-03-21 07:37:36     /go/src/github.com/supabase/auth/cmd/migrate_cmd.go:58 +0x1d4
2025-03-21 07:37:36 github.com/supabase/auth/cmd.init.func3(0x17fab60, {0x183f040?, 0x4?, 0xdcb7aa?})
2025-03-21 07:37:36     /go/src/github.com/supabase/auth/cmd/root_cmd.go:20 +0x24
2025-03-21 07:37:36 github.com/spf13/cobra.(*Command).execute(0x17fab60, {0x400003a0a0, 0x0, 0x0})
2025-03-21 07:37:36     /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x630
2025-03-21 07:37:36 github.com/spf13/cobra.(*Command).ExecuteC(0x17fab60)
2025-03-21 07:37:36     /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
2025-03-21 07:37:36 github.com/spf13/cobra.(*Command).Execute(...)
2025-03-21 07:37:36     /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
2025-03-21 07:37:36 github.com/spf13/cobra.(*Command).ExecuteContext(0xfb58e0?, {0xfb5aa0?, 0x40003af200?})
2025-03-21 07:37:36     /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:985 +0x48
2025-03-21 07:37:36 main.main()
2025-03-21 07:37:36     /go/src/github.com/supabase/auth/main.go:36 +0x128

I will really appreciate if somebody can guide me on how to solve them. Thanks!

**Comment by pedrodpf333** [comment]
change your-encryption-key-32-chars-exactly in ur .env cuz thats 36 characters, set a 32 one and it should work

**Comment by lmeneses1977** [comment]
@pedrodpf333 I really appreciate your support. I changed the VAULT_ENC_KEY to 32 characters, but sadly, it didn't solve it. 

The supabase-auth log now is:

2025-03-25 21:20:42 goroutine 1 [running]:
2025-03-25 21:20:42 net/url.(*URL).Query(0x4000046017?)
2025-03-25 21:20:42     /usr/local/go/src/net/url/url.go:1159 +0x18
2025-03-25 21:20:42 github.com/supabase/auth/cmd.migrate(0x400016fb68?, {0x0?, 0x0?, 0x0?})
2025-03-25 21:20:42     /go/src/github.com/supabase/auth/cmd/migrate_cmd.go:58 +0x1d4
2025-03-25 21:20:42 github.com/supabase/auth/cmd.init.func3(0x17fab60, {0x183f040?, 0x4?, 0xdcb7aa?})
2025-03-25 21:20:42     /go/src/github.com/supabase/auth/cmd/root_cmd.go:20 +0x24
2025-03-25 21:20:42 github.com/spf13/cobra.(*Command).execute(0x17fab60, {0x400003a0a0, 0x0, 0x0})
2025-03-25 21:20:42     /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x630
2025-03-25 21:20:42 github.com/spf13/cobra.(*Command).ExecuteC(0x17fab60)
2025-03-25 21:20:42     /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
2025-03-25 21:20:42 github.com/spf13/cobra.(*Command).Execute(...)
2025-03-25 21:20:42     /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
2025-03-25 21:20:42 github.com/spf13/cobra.(*Command).ExecuteContext(0xfb58e0?, {0xfb5aa0?, 0x40004185c0?})
2025-03-25 21:20:42     /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:985 +0x48
2025-03-25 21:20:42 main.main()
2025-03-25 21:20:42     /go/src/github.com/supabase/auth/main.go:36 +0x128
2025-03-25 21:21:42 {"level":"info","msg":"Go runtime metrics collection started","time":"2025-03-25T20:21:42Z"}
2025-03-25 21:21:42 {"level":"info","msg":"received graceful shutdown signal","time":"2025-03-25T20:21:42Z"}
2025-03-25 21:21:42 panic: runtime error: invalid memory address or nil pointer dereference
2025-03-25 21:21:42 [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x227088]

**Comment by failed33** [comment]
The issue @lmeneses1977 is probably because you changed the .env of local-ai-packaged.

Supabase and the pooler have their own .env file, that gets copied from the .env of local-ai-packaged when you first initialize the db. You can just navigate to the .env file and change the key to match the one you set.

The relative path from your project:

supabase/docker/.env

**Comment by lmeneses1977** [comment]
@failed33 Many thanks for the response. You were right, I went to the settings and the other .env was not updated. However, I am sad to say that the error remains. Can you think of any other problem? Thanks in advance

**Comment by Cmerrill1713** [comment]
![Image](https://github.com/user-attachments/assets/2a0753ad-539d-4b9e-aae3-a354c479e8a5)

Yeah. I'm at a loss. I've tried everything everyone else has suggested.

**Comment by UdaraWanasinghe** [comment]
Check the logs to see the error message.
`docker compose logs supavisor`

My mistake was using a random string with 40 characters as the `VAULT_ENC_KEY`.  AES-256 expects a key with 256 bits (32 characters).

**Comment by HaydenTorg** [comment]
I don't know where you guys are hosting or if it has something to do.

I am on a VPS using Ubuntu, and I think the reason Supabase wasn't working and Kong kept restarting is something got messed up in the deployment regarding the .env file.

What I did is update the `jwt_secret`, `Anon` and `Service_Role` Keys through [here](https://supabase.com/docs/guides/self-hosting/docker#securing-your-services)

saved the .env

then ran the deployment script again 
`python3 start_services.py --profile=cpu --environment=public`

In the deployment script, it doesn't matter if you already ran it before, it will remove everything then bring it back up again.

I was looking to deep into the problem of Kong restarting and Supabase not working, but it was just that for me.

Hopefully this helps someone.

**Comment by Zetanova** [comment]
After once restart wit a self-hosted deployment under ubuntu/docker without any edits beside .env

The file `docker/volumes/pooler/pooler.exs` contains a empty last line, removing it resolves the restart issue.

and after it fails again. something is generating the file?

**Comment by janpio** [comment]
This is still happening for `supabase/supavisor:2.5.1`:

```
21:22:32.693 [info] Migrations already up
** (SyntaxError) invalid syntax found on nofile:30:4:
    error: unexpected token: carriage return (column 4, code point U+000D)
    │
 30 │ end
    │    ^
    │
    └─ nofile:30:4
    (elixir 1.18.2) lib/code.ex:571: Code.validated_eval_string/3
Setting RLIMIT_NOFILE to 100000
```

In Docker Desktop you have a tab "Bind mounts" - it contains a link to the files that has to be converted from CRLF to LF.

**Comment by aantti** [comment]
Hey @janpio :) Curious, why still supavisor 2.5.1? Latest in docker-compose.yml is 2.7.4 ... Can you by any chance test it with the latest state of [self-hosted Supabase](https://github.com/supabase/supabase/tree/master/docker)? Also - [CHANGELOG](https://github.com/supabase/supabase/blob/master/docker/CHANGELOG.md).

**Comment by janpio** [comment]
Good callout @aantti. Docker containers are very easy to overlook on dependency updates - will fix. 
Anyway, all the others that are also out of date and google will now have a better chance to find this thread :)
