### ISSUE TITLE
dependency failed to start: container supabase-db is unhealthy

### ISSUE THREAD

**Issue by gursimran-icode** [supabase/supabase#30834]
2024-12-03 13:08:31 cat: /etc/postgresql-custom/pgsodium_root.key: Permission denied
2024-12-03 13:08:31  2024-12-03 07:38:31.195 UTC [1] FATAL:  invalid secret key
2024-12-03 13:09:23 cat: /etc/postgresql-custom/pgsodium_root.key: Permission denied
2024-12-03 13:09:23  2024-12-03 07:39:23.524 UTC [1] FATAL:  invalid secret key
2024-12-03 13:10:24 cat: /etc/postgresql-custom/pgsodium_root.key: Permission denied
2024-12-03 13:10:24  2024-12-03 07:40:24.170 UTC [1] FATAL:  invalid secret key
2024-12-03 13:09:23 
2024-12-03 13:10:24 
2024-12-03 13:10:24 PostgreSQL Database directory appears to contain a database; Skipping initialization

**Comment by vincentfretin** [comment]
I also had that error when updating my self-hosted instance.
I just removed the db-config volume with `docker volume rm supabase_db-config` so it recreated it. I don't use any pgsodium stuff so recreating the key wasn't an issue for me.

**Comment by gursimran-icode** [comment]
@vincentfretin I was able to run it but gave me an error while creating a new schema stating that "Failed to create schema: ERROR: 42704: role "postgres" does not exist"

**Comment by vincentfretin** [comment]
I didn't have that one, sorry. Remove the db `rm -rf volumes/db/data` (you lose all data) and reset the db maybe? This is what I actually ended up doing last time.
Below is my update procedure I used last time, if that helps.

From my laptop in my project folder, do a dump of the prod:
```sh
supabase db dump --db-url "postgres://postgres:password@ip:5432/postgres" --data-only > supabase/seed.sql
```

On the prod server:
```sh
docker compose down
sudo rm -rf volumes/db/data
docker volume rm supabase_db-config
# update supabase like this:
# mkdir -p old
# cp .env docker-compose.* old/
# git pull
# compare .env and .env.example to update the .env file
# fix the docker-compose.yml file if needed
# I kept the 5432 port on supabase-db, removed it from supabase-pooler
docker compose up -d
# stop supabase-pooler (supavisor) that was not working (it won't restart automatically because of restart: unless-stopped)
docker stop supabase-pooler
```

From my laptop, restore the db with the prod dump

```sh
supabase db reset --db-url "postgres://postgres:password@ip:5432/postgres"
# revert the changes to not commit it by mistake
git checkout supabase/seed.sql
```

**Comment by deathg0d** [comment]
Stuck on this issue as well! My error log:

```
supabase-db                     | 
supabase-db                     | PostgreSQL Database directory appears to contain a database; Skipping initialization
supabase-db                     | 
supabase-db                     |  2024-12-05 13:32:52.293 UTC [1] FATAL:  invalid secret key
supabase-vector                 | 2024-12-05T13:32:52.338828Z  INFO source{component_kind="source" component_id=docker_host component_type=docker_logs component_name=docker_host}: vector::internal_events::docker_logs: Stopped watching for container logs. container_id=40f89f8e778282fcf637b5bd3cc8c1dbbc7d4a1eeefcda4df7bf02b67c40b372
supabase-vector                 | 2024-12-05T13:32:52.338957Z  INFO source{component_kind="source" component_id=docker_host component_type=docker_logs component_name=docker_host}: vector::internal_events::docker_logs: Started watching for container logs. container_id=40f89f8e778282fcf637b5bd3cc8c1dbbc7d4a1eeefcda4df7bf02b67c40b372
supabase-vector                 | 2024-12-05T13:32:52.478765Z  INFO source{component_kind="source" component_id=docker_host component_type=docker_logs component_name=docker_host}: vector::internal_events::docker_logs: Stopped watching for container logs. container_id=40f89f8e778282fcf637b5bd3cc8c1dbbc7d4a1eeefcda4df7bf02b67c40b372
Gracefully stopping... (press Ctrl+C again to force)
dependency failed to start: container supabase-db is unhealthy
```

Db initialization always fails with `FATAL:  invalid secret key`.
I have tried these:
```
sudo rm -rf volumes/db/data
docker volume rm supabase_db-config
```

Still getting the same error.

**Comment by gursimran-icode** [comment]
@deathg0d 
comment out below mentioned lines from your code and try again. Worked for me!
`volumes:
  db-config:`
  `- db-config:/etc/postgresql-custom`

**Comment by joeBlockchain** [comment]
> @deathg0d comment out below mentioned lines from your yml file and try again. Worked for me! `volumes: db-config:` `- db-config:/etc/postgresql-custom`

if you look at the comment above the `- db-config:/etc/postgresql-custom` you'll notice this is related to pgsodium

I had also found this 

https://github.com/supabase/supabase/blob/ad4de15b9e9a466b65b980a25d9ca3f9451ebdf4/apps/docs/content/guides/database/extensions/pgsodium.mdx#L2

Its fair to say just comment out    `- db-config:/etc/postgresql-custom` 

it was line 417 on the docker-compose.yml

and also comment out the last line 485 for `volumes: db-config:`

If you see the volume after running `docker volumes ls`... I deleted it `docker volume rm supabase_db-config`

everything booted up just fine after that.

**Comment by deathg0d** [comment]
Thanks @gursimran-icode and @joeBlockchain Yes the error goes away. But not I am getting error on analytics `dependency failed to start: container supabase-analytics is unhealthy`. Looks like postgres somehow still hasn't started:

```
supabase-db                     | 172.18.0.6 2024-12-08 20:18:03.290 UTC [20300] supabase_admin@_supabase FATAL:  database "_supabase" does not exist
supabase-analytics              | 
supabase-analytics              | 20:18:03.293 [error] Postgrex.Protocol (#PID<0.162.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "_supabase" does not exist
supabase-imgproxy               | INFO    [2024-12-08T20:18:03Z] Started /health  request_id=DwpIiCmKqhTACWnaOiFm6 method=GET client_ip=127.0.0.1
supabase-imgproxy               | INFO    [2024-12-08T20:18:03Z] Completed in 112.279µs /health  request_id=DwpIiCmKqhTACWnaOiFm6 method=GET status=200 client_ip=127.0.0.1
supabase-db                     | 172.18.0.6 2024-12-08 20:18:06.521 UTC [20310] supabase_admin@_supabase FATAL:  database "_supabase" does not exist
supabase-analytics              | 
supabase-analytics              | 20:18:06.523 [error] Postgrex.Protocol (#PID<0.163.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "_supabase" does not exist
supabase-analytics              | 
supabase-analytics              | 20:18:08.000 [error] Could not create schema migrations table. This error usually happens due to the following:    
supabase-analytics              | 
supabase-analytics              |   * The database does not exist
supabase-analytics              |   * The "schema_migrations" table, which Ecto uses for managing
supabase-analytics              |     migrations, was defined by another library
supabase-analytics              |   * There is a deadlock while migrating (such as using concurrent
supabase-analytics              |     indexes with a migration_lock)
supabase-analytics              | 
supabase-analytics              | To fix the first issue, run "mix ecto.create" for the desired MIX_ENV.
supabase-analytics              | 
supabase-analytics              | To address the second, you can run "mix ecto.drop" followed by
supabase-analytics              | "mix ecto.create", both for the desired MIX_ENV. Alternatively you may
supabase-analytics              | configure Ecto to use another table and/or repository for managing
supabase-analytics              | migrations:
supabase-analytics              | 
supabase-analytics              |     config :logflare, Logflare.Repo,
supabase-analytics              |       migration_source: "some_other_table_for_schema_migrations",
supabase-analytics              |       migration_repo: AnotherRepoForSchemaMigrations
supabase-analytics              | 
supabase-analytics              | The full error report is shown below.
supabase-analytics              | 
supabase-analytics              | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 10956ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
supabase-analytics              | 
supabase-analytics              |   1. Ensuring your database is available and that you can connect to it
supabase-analytics              |   2. Tracking down slow queries and making sure they are running fast enough
supabase-analytics              |   3. Increasing the pool_size (although this increases resource consumption)
supabase-analytics              |   4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
supabase-analytics              | 
supabase-analytics              | See DBConnection.start_link/2 for more information
supabase-analytics              | 
supabase-analytics              |     (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
supabase-analytics              |     (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
supabase-analytics              |     (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
supabase-analytics              |     (ecto_sql 3.10.1) lib/ecto/migrator.ex:738: Ecto.Migrator.verbose_schema_migration/3
supabase-analytics              |     (ecto_sql 3.10.1) lib/ecto/migrator.ex:552: Ecto.Migrator.lock_for_migrations/4
supabase-analytics              |     (ecto_sql 3.10.1) lib/ecto/migrator.ex:428: Ecto.Migrator.run/4
supabase-analytics              |     (ecto_sql 3.10.1) lib/ecto/migrator.ex:170: Ecto.Migrator.with_repo/3
supabase-analytics              |     nofile:1: (file)
supabase-imgproxy               | INFO    [2024-12-08T20:18:08Z] Started /health  request_id=jYP72qg1BYJJb9yeLQ91g method=GET client_ip=127.0.0.1
supabase-imgproxy               | INFO    [2024-12-08T20:18:08Z] Completed in 543.445µs /health  request_id=jYP72qg1BYJJb9yeLQ91g method=GET status=200 client_ip=127.0.0.1
supabase-analytics              | 
supabase-analytics              | 20:18:13.817 [info] Elixir.Logflare.SigtermHandler is being initialized...
supabase-imgproxy               | INFO    [2024-12-08T20:18:13Z] Started /health  request_id=5x4qpv_phu3mYSFahDily method=GET client_ip=127.0.0.1
supabase-imgproxy               | INFO    [2024-12-08T20:18:13Z] Completed in 101.948µs /health  request_id=5x4qpv_phu3mYSFahDily method=GET status=200 client_ip=127.0.0.1
supabase-db                     | 172.18.0.6 2024-12-08 20:18:13.884 UTC [20321] supabase_admin@_supabase FATAL:  database "_supabase" does not existsupabase-db                     | 172.18.0.6 2024-12-08 20:18:13.887 UTC [20329] supabase_admin@_supabase FATAL:  database "_supabase" does not existsupabase-db                     | 172.18.0.6 2024-12-08 20:18:13.888 UTC [20323] supabase_admin@_supabase FATAL:  database "_supabase" does not existsupabase-db                     | 172.18.0.6 2024-12-08 20:18:13.890 UTC [20328] supabase_admin@_supabase FATAL:  database "_supabase" does not existsupabase-db                     | 172.18.0.6 2024-12-08 20:18:13.892 UTC [20325] supabase_admin@_supabase FATAL:  database "_supabase" does not existsupabase-db                     | 172.18.0.6 2024-12-08 20:18:13.893 UTC [20324] supabase_admin@_supabase FATAL:  database "_supabase" does not existsupabase-db                     | 172.18.0.6 2024-12-08 20:18:13.900 UTC [20326] supabase_admin@_supabase FATAL:  database "_supabase" does not existsupabase-db                     | 172.18.0.6 2024-12-08 20:18:13.902 UTC [20327] supabase_admin@_supabase FATAL:  database "_supabase" does not existsupabase-db                     | 172.18.0.6 2024-12-08 20:18:13.903 UTC [20330] supabase_admin@_supabase FATAL:  database "_supabase" does not existsupabase-analytics              | 
supabase-analytics              | 20:18:13.902 [error] Postgrex.Protocol (#PID<0.4728.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "_supabase" does not exist
supabase-analytics              | 
supabase-analytics              | 20:18:13.902 [error] Postgrex.Protocol (#PID<0.4730.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "_supabase" does not exist
supabase-analytics              | 
supabase-analytics              | 20:18:13.903 [error] Postgrex.Protocol (#PID<0.4724.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "_supabase" does not exist
supabase-analytics              | 
supabase-analytics              | 20:18:13.903 [error] Postgrex.Protocol (#PID<0.4725.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "_supabase" does not exist
supabase-analytics              | 
supabase-analytics              | 20:18:13.904 [error] Postgrex.Protocol (#PID<0.4719.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "_supabase" does not exist
supabase-analytics              | 
supabase-analytics              | 20:18:13.904 [error] Postgrex.Protocol (#PID<0.4720.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "_supabase" does not exist
supabase-analytics              | 
supabase-analytics              | 20:18:13.904 [error] Postgrex.Protocol (#PID<0.4723.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "_supabase" does not exist
supabase-analytics              | 
supabase-analytics              | 20:18:13.906 [error] Postgrex.Protocol (#PID<0.4726.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "_supabase" does not exist
supabase-analytics              | 
supabase-analytics              | 20:18:13.906 [error] Postgrex.Protocol (#PID<0.4727.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "_supabase" does not exist
supabase-db                     | 172.18.0.6 2024-12-08 20:18:13.909 UTC [20322] supabase_admin@_supabase FATAL:  database "_supabase" does not existsupabase-analytics              | 
supabase-analytics              | 20:18:13.910 [error] Postgrex.Protocol (#PID<0.4729.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name) database "_supabase" does not exist
supabase-db                     | 172.18.0.6 2024-12-08 20:18:13.924 UTC [20331] supabase_admin@_supabase FATAL:  database "_supabase" does not existsupabase-analytics              | 
supabase-analytics              | 20:18:13.927 [notice] Application logflare exited: Logflare.Application.start(:normal, []) returned an error: shutdown: failed to start child: Cainophile.Adapters.Postgres
supabase-analytics              |     ** (EXIT) {:error, :fatal, "3D000", :invalid_catalog_name, "database \"_supabase\" does not exist", [file: "postinit.c", line: "945", routine: "InitPostgres", severity: "FATAL"]}
....
```

**Comment by 12138zhen** [comment]
Hi, I encountered the same issue as @deathg0d. Does anyone have suggestions for further debugging or resolving this issue?

**Comment by thearperson** [comment]
> I also had that error when updating my self-hosted instance. I just removed the db-config volume with `docker volume rm supabase_db-config` so it recreated it. I don't use any pgsodium stuff so recreating the key wasn't an issue for me.

this sounds like a nice workaround. Can someone confirm the use case `pgsodium`? Is that only used for `supabase-vault`?

<img width="321" alt="image" src="https://github.com/user-attachments/assets/a08260fd-c045-4402-accb-5f4ed83a6ea3" />

**Comment by mmoderwell** [comment]
Careful everyone. I lost prod data here. Completely my fault, but please make sure you backup before trying to update.

**Comment by kjanusz** [comment]
Hi, I’m facing a similar issue as @deathg0d. Does anyone have any advice for additional debugging or ways to resolve this?

**Comment by pongraczi** [comment]
I just run into this issue, when I tried to upgrade my self-hosted supabase (via coolify.io, updating image settings, not directly in the yaml file).  

My log is:

```
2024-12-24T21:55:39.329168434Z PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-12-24T21:55:39.329175994Z 
2024-12-24T21:55:39.359569519Z cat: /etc/postgresql-custom/pgsodium_root.key: Permission denied
2024-12-24T21:55:39.360234560Z  2024-12-24 21:55:39.359 UTC [1] FATAL:  invalid secret key
```

I logged into the virtual server and figured out, where is that file (docker inspect ...).  
I did: `chmod 0644 /var/lib/docker/volumes/looocks8k0scsgwc8so8k8wk_supabase-db-config/_data/pgsodium_root.key` and it started well.  
Without loosing any data.

Anyway, the owner was messagebus:messagebus and originally -rw------- .  
I do not know the details, the security issues.  

I hope it helps.

**Comment by acherifi** [comment]
> Got the same problem. Mac m1. My solution:
> 
> * delete volume in docker
> * delete ./docker/volumes/db/data
> * docker compose up db
> * wait init
> * docker compose up

This worked like a charm thank you

**Comment by pongraczi** [comment]
> > Got the same problem. Mac m1. My solution:
> > 
> > * delete volume in docker
> > * delete ./docker/volumes/db/data
> > * docker compose up db
> > * wait init
> > * docker compose up
> 
> This worked like a charm thank you

Please note, this is a working btut destructive solution.  
Choose wisely :)

**Comment by lordvins226** [comment]
> I just run into this issue, when I tried to upgrade my self-hosted supabase (via coolify.io, updating image settings, not directly in the yaml file).
> 
> My log is:
> 
> ```
> 2024-12-24T21:55:39.329168434Z PostgreSQL Database directory appears to contain a database; Skipping initialization
> 2024-12-24T21:55:39.329175994Z 
> 2024-12-24T21:55:39.359569519Z cat: /etc/postgresql-custom/pgsodium_root.key: Permission denied
> 2024-12-24T21:55:39.360234560Z  2024-12-24 21:55:39.359 UTC [1] FATAL:  invalid secret key
> ```
> 
> I logged into the virtual server and figured out, where is that file (docker inspect ...). I did: `chmod 0644 /var/lib/docker/volumes/looocks8k0scsgwc8so8k8wk_supabase-db-config/_data/pgsodium_root.key` and it started well. Without loosing any data.
> 
> Anyway, the owner was messagebus:messagebus and originally -rw------- . I do not know the details, the security issues.
> 
> I hope it helps.

Thanks for sharing

**Comment by armandomm09** [comment]
@deathg0d did you manage to solve the DBConnection.ConnectionError error? I've had this error for about 3 weeks now without even start supabase 1 time. I've tried everything, even restoring my whole computer and still got the same error.

Thankss

**Comment by deathg0d** [comment]
> [@deathg0d](https://github.com/deathg0d) did you manage to solve the DBConnection.ConnectionError error? I've had this error for about 3 weeks now without even start supabase 1 time. I've tried everything said in this issue and more, even restoring my whole computer and still got the same error.
> 
> Thankss

Nah, I couldn't fix it. I deleted everything, cloned the Supabase repo again, and started from scratch. It finally worked—there were probably some updates. It was okay for me because I was starting a new project anyway, so I didn't mind deleting the old files. But I can see how resetting could be undesirable to many.

**Comment by edyhourany** [comment]
> Nah, I couldn't fix it. I deleted everything, cloned the Supabase repo again, and started from scratch. It finally worked—there were probably some updates. It was okay for me because I was starting a new project anyway, so I didn't mind deleting the old files. But I can see how resetting could be undesirable to many.

@deathg0d can you elaborate more how you did this? I am facing the same issue. When you say clone the supabase repo, do you mean not using coolify? or is it on coolify?

**Comment by Tabza90** [comment]
I experienced the same problem and solved it by running 'docker rm -f supabase-db' and then running 'docker compose up -d', it will simply re-fetch the supabase-db container and restart the containers that had already been downloaded and were healthy. The assumption here is that you running this in terminal while in the docker directory

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.

**Comment by adamfarmer0** [comment]
Ok so here is the fix for windows installation of docker desktop with hyper-v:
1- Go to Settings/File Sharing then add Synchronized file share (not sure if this is needed, but I did it anyways)
2- Scroll down to Virtual file shares, add AutoGPT folder

go back to AutoGPT/autogpt_platform then run docker compose up -d
