### ISSUE TITLE
GraphiQL: Error fetching schema when values in enumerated types contain whitespaces

### ISSUE THREAD

**Issue by borolepratik** [supabase/supabase#31068]
## Describe the bug

GraphiQL: Error fetching schema when values in enumerated types contain whitespaces

## To Reproduce

1. Follow the [Supabase self-host with docker guide](https://supabase.com/docs/guides/self-hosting/docker) and run the services
2. Access Supabase Studio
3. Check GraphQL schema (schema is available)
4. Create an enum with the following values - `a`, `b`, `c and d`
5. Check GraphQL schema again

## Expected behavior

GraphQL schema should be available

## Actual behavior

Error fetching schema

## Screenshots

![image](https://github.com/user-attachments/assets/e9abd7f8-7d74-4af3-8b19-d26ea6255978)
![image](https://github.com/user-attachments/assets/be570f31-4faf-4f2d-8e2d-aa51c8f4f2e5)

## System information

Supabase self-host with docker 4950783ae8768d89457cf811ce1b14c32548b823

## Additional context

```json
{
  "errors": [
    {
      "message": "Names must only contain [_a-zA-Z0-9] but \"c and d\" does not.",
      "extensions": {},
      "stack": "GraphQLError: Names must only contain [_a-zA-Z0-9] but \"c and d\" does not.\n    at a (http://localhost:8000/_next/static/chunks/3323.b268740302d92793.js:56:9729)\n    at s (http://localhost:8000/_next/static/chunks/3323.b268740302d92793.js:56:10021)\n    at http://localhost:8000/_next/static/chunks/3323.b268740302d92793.js:56:21176\n    at Array.map (<anonymous>)\n    at new eg (http://localhost:8000/_next/static/chunks/3323.b268740302d92793.js:56:21020)\n    at http://localhost:8000/_next/static/chunks/3323.b268740302d92793.js:56:59289\n    at http://localhost:8000/_next/static/chunks/3323.b268740302d92793.js:56:59449\n    at http://localhost:8000/_next/static/chunks/3323.b268740302d92793.js:56:59848\n    at r (http://localhost:8000/_next/static/chunks/3323.b268740302d92793.js:55:704)\n    at h (http://localhost:8000/_next/static/chunks/3323.b268740302d92793.js:56:58501)\n    at http://localhost:8000/_next/static/chunks/3323.b268740302d92793.js:11:4856"
    }
  ]
}
```

**Comment by NiharP31** [comment]
I have a potential solution for this. Can I be assigned to this? So I can submit a PR

**Comment by mvincentong** [comment]
I’m taking a look at this. The current plan is a small Studio-side guard so GraphiQL can still load introspection results when pg_graphql returns enum values that GraphQL.js rejects.
