### ISSUE TITLE
Supabase not working in gradio python space

### ISSUE THREAD

**Issue by UNNAMMEDUSER** [supabase/supabase#31172]
Supabase not working in gradio python space
Error log:
```
Exit code: 1. Reason: Traceback (most recent call last):
  File "/home/user/app/app.py", line 9, in <module>
    create_client(supabase_key=key, supabase_url=url)
  File "/usr/local/lib/python3.10/site-packages/supabase/_sync/client.py", line 335, in create_client
    return SyncClient.create(
  File "/usr/local/lib/python3.10/site-packages/supabase/_sync/client.py", line 102, in create
    client = cls(supabase_url, supabase_key, options)
  File "/usr/local/lib/python3.10/site-packages/supabase/_sync/client.py", line 58, in __init__
    raise SupabaseException("Invalid URL")
supabase._sync.client.SupabaseException: Invalid URL
```
```
===== Application Startup at 2024-12-16 17:28:42 =====

Traceback (most recent call last):
  File "/home/user/app/app.py", line 9, in <module>
    create_client(supabase_key=key, supabase_url=url)
  File "/usr/local/lib/python3.10/site-packages/supabase/_sync/client.py", line 335, in create_client
    return SyncClient.create(
  File "/usr/local/lib/python3.10/site-packages/supabase/_sync/client.py", line 102, in create
    client = cls(supabase_url, supabase_key, options)
  File "/usr/local/lib/python3.10/site-packages/supabase/_sync/client.py", line 58, in __init__
    raise SupabaseException("Invalid URL")
supabase._sync.client.SupabaseException: Invalid URL
Traceback (most recent call last):
  File "/home/user/app/app.py", line 9, in <module>
    create_client(supabase_key=key, supabase_url=url)
  File "/usr/local/lib/python3.10/site-packages/supabase/_sync/client.py", line 335, in create_client
    return SyncClient.create(
  File "/usr/local/lib/python3.10/site-packages/supabase/_sync/client.py", line 102, in create
    client = cls(supabase_url, supabase_key, options)
  File "/usr/local/lib/python3.10/site-packages/supabase/_sync/client.py", line 58, in __init__
    raise SupabaseException("Invalid URL")
supabase._sync.client.SupabaseException: Invalid URL
```

**Comment by loganpearce17** [comment]
Hi, I'm having the same issue and I would really like it to be resolved! According to the docs, Gradio supports Supabase (https://www.gradio.app/guides/creating-a-dashboard-from-supabase-data), so I used Supabase for my backend and I really need it to work. Thanks in advance!
