### ISSUE TITLE
supabase-pooler keeps restarting indefinitely.

### ISSUE THREAD

**Issue by suvrat29** [supabase/supabase#31282]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After following the starting guide for [self hosting](https://supabase.com/docs/guides/self-hosting/docker), once I changed the password and API keys/tokens/secrets, the pooler keeps restarting.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Follow setup guide.
2. Start the docker container.
3. Observe continuous restarts.

## Expected behavior

The pooler service should not be in a restart loop.

## Screenshots

![image](https://github.com/user-attachments/assets/8001fca7-fa06-457e-b04f-e65a554fa478)

## System information

- OS: Windows
- Version of Node.js: 22.11.0

## Additional context

Here is the log:-
```
(elixir 1.14.3) lib/code.ex:424: Code.validated_eval_string/3
2024-12-21 13:39:49 ** (SyntaxError) nofile:30:4: unexpected token: carriage return (column 4, code point U+000D)
2024-12-21 13:39:49     |
2024-12-21 13:39:49  30 | end
2024-12-21 13:39:49     |    ^
2024-12-21 13:39:49     (elixir 1.14.3) lib/code.ex:424: Code.validated_eval_string/3
2024-12-21 13:40:16 ** (SyntaxError) nofile:30:4: unexpected token: carriage return (column 4, code point U+000D)
2024-12-21 13:40:16     |
2024-12-21 13:40:16  30 | end
2024-12-21 13:40:16     |    ^
2024-12-21 13:40:16     (elixir 1.14.3) lib/code.ex:424: Code.validated_eval_string/3
2024-12-21 13:41:08 ** (SyntaxError) nofile:30:4: unexpected token: carriage return (column 4, code point U+000D)
2024-12-21 13:41:08     |
2024-12-21 13:41:08  30 | end
2024-12-21 13:41:08     |    ^
2024-12-21 13:41:08     (elixir 1.14.3) lib/code.ex:424: Code.validated_eval_string/3
2024-12-21 13:42:09 ** (SyntaxError) nofile:30:4: unexpected token: carriage return (column 4, code point U+000D)
2024-12-21 13:42:09     |
2024-12-21 13:42:09  30 | end
2024-12-21 13:42:09     |    ^
2024-12-21 13:42:09     (elixir 1.14.3) lib/code.ex:424: Code.validated_eval_string/3
2024-12-21 13:43:10 ** (SyntaxError) nofile:30:4: unexpected token: carriage return (column 4, code point U+000D)
2024-12-21 13:43:10     |
2024-12-21 13:43:10  30 | end
2024-12-21 13:43:10     |    ^
2024-12-21 13:43:10     (elixir 1.14.3) lib/code.ex:424: Code.validated_eval_string/3
2024-12-21 13:44:11 ** (SyntaxError) nofile:30:4: unexpected token: carriage return (column 4, code point U+000D)
2024-12-21 13:44:11     |
2024-12-21 13:44:11  30 | end
```

Note: I tried the solution provided at https://github.com/supabase/supabase/issues/30210, but it did not work.

**Comment by suvrat29** [comment]
I also tried this with updating to the latest docker image, same issue.

**Comment by NagaiKaminoke** [comment]
Same issue for me running the latest docker image

**Comment by wim-gdwi** [comment]
Got same issue but #30210 solved the issue for me

**Comment by Hallidayo** [comment]
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.

**Comment by RahulSahooKoyma** [comment]
@suvrat29 I too was facing issue despite having followed https://github.com/supabase/supabase/issues/30210 ... What finally solved the issue for me was when I assigned the VAULT_ENC_KEY to a valid value in the .env file.
