### ISSUE TITLE
Supabase realtime throws cast type error

### ISSUE THREAD

**Issue by iansama** [supabase/supabase#4203]
NOTE: Flutter/Dart

I am new to supabase and I am getting two different issues. 

Issue 1: I am getting **a cast type error with RLS disabled**
Issue 2: I am getting **no response with RLS enabled**

First I started with RLS disabled & no policies to test supabase then manually edited the rows in supabase. This returned the error:
`Unhandled Exception: type 'Null' is not a subtype of type 'List<dynamic>' in type cast  `

Then I asked for help on Reddit, someone showed me that sb has a new bug with the RLS. Since I had RLS disabled, I enabled it, set the policy to 'everyone', and individually turned on real-time for specific tables. **The error went away however now, I am not getting any response back from supabase.**

Is this a supabase issue or is this a coding mistake on my part?

This is how I coded the subscription
```
  startProfileSubscriptions() {
       RealtimeSubscription mySubscription =
        supabaseClient.from('profiles').on(SupabaseEventTypes.all, (payload) {
      print("payload");
    }).subscribe();
  }
```

This was the error report while RLS is not enabled
```
Reloaded 0 libraries in 1,931ms.
I/flutter (24101):  ===== START SUBSCRIPTION =====
E/flutter (24101): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'List<dynamic>' in type cast  

E/flutter (24101): #0      new SupabaseRealtimePayload.fromJson.<anonymous closure>
E/flutter (24101): #1      WhereIterator.moveNext (dart:_internal/iterable.dart:439:13)
E/flutter (24101): #2      MappedIterator.moveNext (dart:_internal/iterable.dart:390:19)
E/flutter (24101): #3      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:198:26)
E/flutter (24101): #4      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
E/flutter (24101): #5      new List.of (dart:core-patch/array_patch.dart:50:28)
E/flutter (24101): #6      Iterable.toList (dart:core/iterable.dart:388:12)
E/flutter (24101): #7      new SupabaseRealtimePayload.fromJson
E/flutter (24101): #8      SupabaseRealtimeClient.on.<anonymous closure>
E/flutter (24101): #9      RealtimeSubscription.trigger
E/flutter (24101): #10     RealtimeClient.onConnMessage.<anonymous closure>.<anonymous closure>
E/flutter (24101): #11     Iterable.forEach (dart:core/iterable.dart:279:35)
E/flutter (24101): #12     RealtimeClient.onConnMessage.<anonymous closure>
E/flutter (24101): #13     new RealtimeClient.<anonymous closure>
E/flutter (24101): #14     RealtimeClient.onConnMessage
E/flutter (24101): #15     RealtimeClient.connect.<anonymous closure>
E/flutter (24101): #16     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (24101): #17     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (24101): #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (24101): #19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (24101): #20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (24101): #21     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (24101): #22     _HandleErrorStream._handleData (dart:async/stream_pipe.dart:253:10)
E/flutter (24101): #23     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (24101): #24     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (24101): #25     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (24101): #26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (24101): #27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (24101): #28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (24101): #29     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
E/flutter (24101): #30     _StreamController._add (dart:async/stream_controller.dart:607:7)
E/flutter (24101): #31     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (24101): #32     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (24101): #33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (24101): #34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (24101): #35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (24101): #36     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
E/flutter (24101): #37     _StreamController._add (dart:async/stream_controller.dart:607:7)
E/flutter (24101): #38     _StreamController.add (dart:async/stream_controller.dart:554:5)
E/flutter (24101): #39     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1150:21)
E/flutter (24101): #40     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (24101): #41     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (24101): #42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (24101): #43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (24101): #44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (24101): #45     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
E/flutter (24101): #46     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
E/flutter (24101): #47     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
E/flutter (24101): #48     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
```

**Comment by w3b6x9** [comment]
@iansama please follow this [issue](https://github.com/supabase/supabase-dart/pull/66) to know about the next release as it addresses the cast type error.

**Comment by w3b6x9** [comment]
@iansama version bump to the latest supabase-dart client version to address your first issue.

> set the policy to 'everyone'

how did you exactly set policy to 'everyone'? do you mean your policy returns `true`? can you share your full policy if possible?

**Comment by w3b6x9** [comment]
@iansama closing this issue but feel free to reopen if you continue to experience issues.

**Comment by iansama** [comment]
It is working now after the update
