### ISSUE TITLE
Current Deno version is not compatible with Stripe in Edge Functions

### ISSUE THREAD

**Issue by RedChops** [supabase/supabase#6515]
# Bug report

## Describe the bug

Sorry, not sure if this is a bug or a chore really. The current version of Deno used, at least as created by supabase cli, is not compatible with Stripe. When attempting to serve a function that imports the Stripe library, the check stage throws an error:

```
Check file:///home/deno/functions/payment-sheet/index.ts
error: TS2339 [ERROR]: Property 'ref' does not exist on type 'Listener'.
    this.#listener?.ref();
                    ~~~
    at https://deno.land/std@0.135.0/node/internal_binding/tcp_wrap.ts:240:21

TS2339 [ERROR]: Property 'unref' does not exist on type 'Listener'.
    this.#listener?.unref();
                    ~~~~~
    at https://deno.land/std@0.135.0/node/internal_binding/tcp_wrap.ts:243:21

Found 2 errors.
Watcher Process finished. Restarting on file change...
```

The Deno team have released a new version to address this: https://github.com/denoland/deno/releases/tag/v1.20.5 (note, 1.20.6 appears to be the current version)

## To Reproduce

1. Clone and set up the "Flutter/Stripe Payments" sample repository https://github.com/supabase-community/flutter-stripe-payments-with-supabase-functions
2. Attempt to serve the payment-sheet function

## Expected behavior

The function should begin serving as normal

**Comment by woodstock13** [comment]
Work well for me with Deno v.`1.21.1` without --unstable

**Comment by riderx** [comment]
Same issue on my side, i fixed it by using stripe rest API
https://github.com/Cap-go/capgo/blob/main/supabase/functions/_utils/stripe.ts
And for webhook parsing that was way harder :
https://github.com/Cap-go/capgo/blob/main/supabase/functions/_utils/stripe_event.ts
