### ISSUE TITLE
'Invalid authentication credentials' message when reading data on Node JS app hosted on Digital Ocean.

### ISSUE THREAD

**Issue by tscans** [supabase/supabase#6535]
## Describe the bug

I have been working on a Node JS app locally building with Supabase. When I recently uploaded to Digital Ocean, I've been getting an error 'Invalid authentication credentials' any time I make a request to the service which makes a subabase.select() call. It works perfectly fine locally, but fails on the live link. I verified the service_role secret key is the same on local and dev. I have no users currently. I just want to use supabase as a table to read from for now only exposed by the service. RLS being on or off seems to have no effect either.

**Comment by tscans** [comment]
Solved the issue. The env variable was being injected with quotations. I had to remove them with .replace before passing it to `createClient`.

**Comment by CarlosIVI** [comment]
``I'm facing the same issue, this happen with resumable upload code and only when the file is big enough to call /upload/resumable within the server:

I'm getting 401 Unauthorized

I'm using the right credentials, otherwise I wouldn't be able to upload small images, the upload reach the around 8% and breaks with the following message.

```
Uncaught (in promise) Error: tus: unexpected response while uploading chunk, originated from request (method: PATCH, url: http://t2-fhe-test.site/upload/resumable/dGVzdC8xMjBtYi8yMTUwZmY0OC0xZjRmLTRlMjUtODYwNS1kNjQ3OGRkMTM0N2Q, response code: 401, response text: {
  "message":"Invalid authentication credentials"
}, request id: n/a)
    at Upload._emitHttpError (upload.js:420:1)
    at upload.js:675:1
```

Snippet of the code already tried and failing:

```
console.log("session:", session.access_token)
      var upload = new tus.Upload(file, {
        endpoint: process.env.REACT_APP_SUPABASE_URL+ "/storage/v1/upload/resumable",
        retryDelays: [0, 3000, 5000, 10000, 20000],
        headers: {
          authorization: `Bearer ${process.env.REACT_APP_ANON_KEY}`,
          apikey: process.env.REACT_APP_ANON_KEY,
          'x-upsert': 'false', // optionally set upsert to true to overwrite existing files
        },
```
I also try instead with the session.access_token.

```
....
  headers: {
        authorization: `Bearer ${session.access_token}`,
        'x-upsert': 'true', // optionally set upsert to true to overwrite existing files
      },
```

**Comment by btouchard** [comment]
I have exactly the same problem as [CarlosIVI](https://github.com/CarlosIVI)

As in the documentation [documentation](https://supabase.com/docs/guides/storage/uploads/resumable-uploads), I set the authorization from the auth session.
But TUS answers 401 unauthorized, the only difference with the documentation is that I am on a self-hosted solution.
Behind a Traefik reverse proxy, which works like a charm. None of the other features are a problem

```javascript
import {client} from "@/lib/superbase.ts";
import * as tus from 'tus-js-client';
import {getEnv} from "@/lib/env.ts";
import {lookup} from "mime-types";

export async function uploadFile(bucketName: string, fileName: string, file: File) {
    const { data: { session } } = await client.auth.getSession();
    if (!session) throw 'No such session';

    return new Promise((resolve:(value: unknown) => void, reject) => {
        const mimeType = lookup(file.name) || 'binary/octet-stream';
        const upload = new tus.Upload(file, {
            endpoint: `${getEnv('API_URL')}/storage/v1/upload/resumable`,
            retryDelays: [0, 3000, 5000, 10000, 20000],
            headers: {
                authorization: `Bearer ${session.access_token}`,
                'x-upsert': 'true', // optionally set upsert to true to overwrite existing files
            },
            uploadDataDuringCreation: true,
            removeFingerprintOnSuccess: true,
            metadata: {
                bucketName: bucketName,
                objectName: fileName,
                contentType: mimeType,
                cacheControl: '3600',
            },
            chunkSize: 6 * 1024 * 1024, // NOTE: it must be set to 6MB (for now) do not change it
            onError: function (error) {
                console.log('Failed because: ' + error);
                reject(error);
            },
            onProgress: function (bytesUploaded, bytesTotal) {
                const percentage = ((bytesUploaded / bytesTotal) * 100).toFixed(2)
                console.log(bytesUploaded, bytesTotal, percentage + '%');
            },
            onSuccess: function () {
                console.log('Download %s from %s', upload.file, upload.url)
                resolve(upload.file);
            },
        })

        // Check if there are any previous uploads to continue.
        return upload.findPreviousUploads().then(function (previousUploads) {
            // Found previous uploads so we select the first one.
            if (previousUploads.length) {
                upload.resumeFromPreviousUpload(previousUploads[0])
            }

            // Start the upload
            upload.start()
        })
    })
}
```

**Comment by tsensei** [comment]
@btouchard  Is it working correctly now for you? I'm getting this error on the second call to the /upload/resumable endpoint everytime when the file is over 12 mbs

**Comment by btouchard** [comment]
@tsensei no is not

**Comment by vidikn** [comment]
Any solution to this issue? Also on self-hosted
