### ISSUE TITLE
Storybook fails to run in studio.

### ISSUE THREAD

**Issue by nnaemekaibe** [supabase/supabase#7349]
# Bug report

## Describe the bug

When i run `yarn storybook` i get the error:
```
ERROR in ./.storybook/preview.css (./node_modules/css-loader/dist/cjs.js??ref--11-1!./node_modules/@storybook/builder-webpack4/node_modules/postcss-loader/dist/cjs.js??ref--11-2!./.storybook/preview.css)
Module build failed (from ./node_modules/@storybook/builder-webpack4/node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS plugin tailwindcss requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/Users/mac/Documents/GitHub/client-supabase/studio/node_modules/@storybook/builder-webpack4/node_modules/postcss/lib/processor.js:153:15)
    at new Processor (/Users/mac/Documents/GitHub/client-supabase/studio/node_modules/@storybook/builder-webpack4/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/Users/mac/Documents/GitHub/client-supabase/studio/node_modules/@storybook/builder-webpack4/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/Users/mac/Documents/GitHub/client-supabase/studio/node_modules/@storybook/builder-webpack4/node_modules/postcss-loader/dist/index.js:95:20)
 @ ./.storybook/preview.css 2:26-197 53:4-74:5 56:18-189
 @ ./.storybook/preview.js
 @ ./.storybook/preview.js-generated-config-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/react/dist/esm/client/docs/config-generated-config-entry.js ./node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-links/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-docs/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-measure/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-outline/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-interactions/preview.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js
```
## To Reproduce

1. Go to /studio.
2. Run `yarn storybook`.

## Expected behavior

Storybook should start successfully.

## System information

- OS: macOS, Windows
- Version of supabase-js:  1.35.3
- Version of Node.js: 14.19.3]

**Comment by saltcod** [comment]
Hey @nnaemekaibe that's strange. Have you pulled the latest from master and run `npm install` in /studio?

**Comment by nnaemekaibe** [comment]
Yes I've done this. Managed to resolve it by updating postcss.config.js with the path to tailwind.config.js. Does it run without issues on your end?

**Comment by saltcod** [comment]
Aah interesting. Thanks @nnaemekaibe.   What did you update it from → to, in case it helps others?
