### ISSUE TITLE
Error running db migrations from scratch (no schema has been selected to create in)

### ISSUE THREAD

**Issue by joepa37** [supabase/supabase#7969]
# Bug report

## Describe the bug

Error running db migrations from scratch at Auth Service (supabase/gotrue) all other containers seems to be running smooth except Realtime Service (supabase/realtime) that still waiting for migration table creation

## System information

- OS: Ubuntu 20.04
- Postgres 14.4 (I have tried on postgres 12.11 too)

## Additional context

I am actually using an external postgres cluster using this connection strings:
- Auth-Service: `GOTRUE_DB_DATABASE_URL: postgres://postgres:my-strong-password@postgres-14-postgresql-ha-pgpool.postgres.svc.cluster.local:5432/postgres?search_path=auth`
- Rest-Service: `PGRST_DB_URI: postgres://postgres:my-string-password@postgres-14-postgresql-ha-pgpool.postgres.svc.cluster.local:5432/postgres`
- Storage-Service: `DATABASE_URL: postgres://postgres:my-strong-password@postgres-14-postgresql-ha-pgpool.postgres.svc.cluster.local:5432/postgres`

I have tried giving permissions but nothing happened
```sql
grant usage on schema public to public;
grant create on schema public to public;
```
Migration table actually seems to be created
![image](https://user-images.githubusercontent.com/15274305/182015633-6974466a-5635-4c86-9563-7e31ca36597f.png)

supabase-auth logs
```
Sun, Jul 31 2022 1:46:26 am | [POP] 2022/07/31 07:46:26 info - 0.0582 seconds
Sun, Jul 31 2022 1:46:26 am | time="2022-07-31T07:46:26Z" level=fatal msg="running db migrations: Migrator: problem creating schema migrations: CREATE TABLE \"schema_migrations\" (\n\"version\" VARCHAR (14) NOT NULL\n);\nCREATE UNIQUE INDEX \"schema_migrations_version_idx\" ON \"schema_migrations\" (version);: ERROR: no schema has been selected to create in (SQLSTATE 3F000)"
```

supabase-realtime logs
```
Sun, Jul 31 2022 1:50:40 am | * The database does not exist
Sun, Jul 31 2022 1:50:40 am | * The "schema_migrations" table, which Ecto uses for managing
Sun, Jul 31 2022 1:50:40 am | migrations, was defined by another library
Sun, Jul 31 2022 1:50:40 am | * There is a deadlock while migrating (such as using concurrent
Sun, Jul 31 2022 1:50:40 am | indexes with a migration_lock)
Sun, Jul 31 2022 1:50:40 am |  
Sun, Jul 31 2022 1:50:40 am | To fix the first issue, run "mix ecto.create".
Sun, Jul 31 2022 1:50:40 am |  
Sun, Jul 31 2022 1:50:40 am | To address the second, you can run "mix ecto.drop" followed by
Sun, Jul 31 2022 1:50:40 am | "mix ecto.create". Alternatively you may configure Ecto to use
Sun, Jul 31 2022 1:50:40 am | another table and/or repository for managing migrations:
Sun, Jul 31 2022 1:50:40 am |  
Sun, Jul 31 2022 1:50:40 am | config :realtime, Realtime.RLS.Repo,
Sun, Jul 31 2022 1:50:40 am | migration_source: "some_other_table_for_schema_migrations",
Sun, Jul 31 2022 1:50:40 am | migration_repo: AnotherRepoForSchemaMigrations
Sun, Jul 31 2022 1:50:40 am |  
Sun, Jul 31 2022 1:50:40 am | The full error report is shown below.
Sun, Jul 31 2022 1:50:40 am |  
Sun, Jul 31 2022 1:50:40 am | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 10989ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
Sun, Jul 31 2022 1:50:40 am |  
Sun, Jul 31 2022 1:50:40 am | 1. Ensuring your database is available and that you can connect to it
Sun, Jul 31 2022 1:50:40 am | 2. Tracking down slow queries and making sure they are running fast enough
Sun, Jul 31 2022 1:50:40 am | 3. Increasing the pool_size (although this increases resource consumption)
Sun, Jul 31 2022 1:50:40 am | 4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
Sun, Jul 31 2022 1:50:40 am |  
Sun, Jul 31 2022 1:50:40 am | See DBConnection.start_link/2 for more information
Sun, Jul 31 2022 1:50:40 am |  
Sun, Jul 31 2022 1:50:40 am | (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
Sun, Jul 31 2022 1:50:40 am | (elixir 1.11.4) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
Sun, Jul 31 2022 1:50:40 am | (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:852: Ecto.Adapters.SQL.execute_ddl/4
Sun, Jul 31 2022 1:50:40 am | (ecto_sql 3.7.1) lib/ecto/migrator.ex:678: Ecto.Migrator.verbose_schema_migration/3
Sun, Jul 31 2022 1:50:40 am | (ecto_sql 3.7.1) lib/ecto/migrator.ex:504: Ecto.Migrator.lock_for_migrations/4
Sun, Jul 31 2022 1:50:40 am | (ecto_sql 3.7.1) lib/ecto/migrator.ex:419: Ecto.Migrator.run/4
Sun, Jul 31 2022 1:50:40 am | (ecto_sql 3.7.1) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
Sun, Jul 31 2022 1:50:40 am | (realtime 0.0.0-automated) lib/realtime/release.ex:9: anonymous fn/2 in Realtime.Release.migrate/0
```

supabase/storage logs
```
2022-07-31T07:43:57: PM2 log: Launching in no daemon mode
Sun, Jul 31 2022 1:43:57 am | 2022-07-31T07:43:57: PM2 log: App [server:0] starting in -fork mode-
Sun, Jul 31 2022 1:43:57 am | 2022-07-31T07:43:57: PM2 log: App [server:0] online
Sun, Jul 31 2022 1:43:58 am | running migrations
Sun, Jul 31 2022 1:43:58 am | Error: Migration failed. Reason: An error occurred running 'pathtoken-column'. Rolled back this migration. No further migrations were run. Reason: schema "storage" does not exist
Sun, Jul 31 2022 1:43:58 am | at /app/node_modules/postgres-migrations/dist/migrate.js:100:27
Sun, Jul 31 2022 1:43:58 am | at processTicksAndRejections (node:internal/process/task_queues:95:5)
Sun, Jul 31 2022 1:43:58 am | at /app/node_modules/postgres-migrations/dist/with-lock.js:25:28 {
Sun, Jul 31 2022 1:43:58 am | cause: Error: An error occurred running 'pathtoken-column'. Rolled back this migration. No further migrations were run. Reason: schema "storage" does not exist
Sun, Jul 31 2022 1:43:58 am | at /app/node_modules/postgres-migrations/dist/run-migration.js:36:15
Sun, Jul 31 2022 1:43:58 am | at processTicksAndRejections (node:internal/process/task_queues:95:5)
Sun, Jul 31 2022 1:43:58 am | at /app/node_modules/postgres-migrations/dist/migrate.js:91:32
Sun, Jul 31 2022 1:43:58 am | at /app/node_modules/postgres-migrations/dist/with-lock.js:25:28
Sun, Jul 31 2022 1:43:58 am | }
```
supabase-rest logs
```
31/Jul/2022:07:43:35 +0000: Attempting to connect to the database...
31/Jul/2022:07:43:35 +0000: Connection successful
31/Jul/2022:07:43:35 +0000: Listening on port 3000
31/Jul/2022:07:43:35 +0000: Config re-loaded
31/Jul/2022:07:43:35 +0000: Listening for notifications on the pgrst channel
31/Jul/2022:07:43:35 +0000: Schema cache loaded
```
postgres-database logs
```
2022-07-31 18:26:42.537: gotrue_migrations pid 681: LOG: pool_send_and_wait: Error or notice message from backend: : DB node id: 0 backend pid: 147579 statement: "CREATE TABLE "schema_migrations" (
Sun, Jul 31 2022 12:26:42 pm | "version" VARCHAR (14) NOT NULL
Sun, Jul 31 2022 12:26:42 pm | );
Sun, Jul 31 2022 12:26:42 pm | CREATE UNIQUE INDEX "schema_migrations_version_idx" ON "schema_migrations" (version);" message: "no schema has been selected to create in"
Sun, Jul 31 2022 12:26:42 pm | 2022-07-31 18:26:42.548: gotrue_migrations pid 681: ERROR: unable to read data from frontend
Sun, Jul 31 2022 12:26:42 pm | 2022-07-31 18:26:42.548: gotrue_migrations pid 681: DETAIL: EOF encountered with frontend
Sun, Jul 31 2022 12:26:43 pm | 2022-07-31 18:26:43.132: gotrue_migrations pid 681: LOG: pool_send_and_wait: Error or notice message from backend: : DB node id: 1 backend pid: 103981 statement: "select * from schema_migrations" message: "relation "schema_migrations" does not exist"
Sun, Jul 31 2022 12:26:43 pm | 2022-07-31 18:26:43.141: gotrue_migrations pid 681: LOG: pool_send_and_wait: Error or notice message from backend: : DB node id: 0 backend pid: 147586 statement: "CREATE TABLE "schema_migrations" (
Sun, Jul 31 2022 12:26:43 pm | "version" VARCHAR (14) NOT NULL
Sun, Jul 31 2022 12:26:43 pm | );
Sun, Jul 31 2022 12:26:43 pm | CREATE UNIQUE INDEX "schema_migrations_version_idx" ON "schema_migrations" (version);" message: "no schema has been selected to create in"
Sun, Jul 31 2022 12:26:43 pm | 2022-07-31 18:26:43.163: gotrue_migrations pid 681: ERROR: unable to read data from frontend
Sun, Jul 31 2022 12:26:43 pm | 2022-07-31 18:26:43.163: gotrue_migrations pid 681: DETAIL: EOF encountered with frontend
Sun, Jul 31 2022 12:26:56 pm | 2022-07-31 18:26:56.162: gotrue_migrations pid 509: LOG: pool_send_and_wait: Error or notice message from backend: : DB node id: 0 backend pid: 147638 statement: "select * from schema_migrations" message: "relation "schema_migrations" does not exist"
Sun, Jul 31 2022 12:26:56 pm | 2022-07-31 18:26:56.165: gotrue_migrations pid 509: LOG: pool_send_and_wait: Error or notice message from backend: : DB node id: 0 backend pid: 147638 statement: "CREATE TABLE "schema_migrations" (
Sun, Jul 31 2022 12:26:56 pm | "version" VARCHAR (14) NOT NULL
Sun, Jul 31 2022 12:26:56 pm | );
Sun, Jul 31 2022 12:26:56 pm | CREATE UNIQUE INDEX "schema_migrations_version_idx" ON "schema_migrations" (version);" message: "no schema has been selected to create in"
Sun, Jul 31 2022 12:26:56 pm | 2022-07-31 18:26:56.187: gotrue_migrations pid 509: ERROR: unable to read data from frontend
Sun, Jul 31 2022 12:26:56 pm | 2022-07-31 18:26:56.187: gotrue_migrations pid 509: DETAIL: EOF encountered with frontend
Sun, Jul 31 2022 12:27:00 pm | 2022-07-31 18:27:00.067: [unknown] pid 532: LOG: pool_send_and_wait: Error or notice message from backend: : DB node id: 0 backend pid: 147650 statement: "alter table storage.objects add column path_tokens text[] generated always as (string_to_array("name", '/')) stored;
Sun, Jul 31 2022 12:27:00 pm |  
Sun, Jul 31 2022 12:27:00 pm | CREATE OR REPLACE FUNCTION storage.search(prefix text, bucketname text, limits int DEFAULT 100, levels int DEFAULT 1, offsets int DEFAULT 0)
Sun, Jul 31 2022 12:27:00 pm | RETURNS TABLE (
Sun, Jul 31 2022 12:27:00 pm | name text,
Sun, Jul 31 2022 12:27:00 pm | id uuid,
Sun, Jul 31 2022 12:27:00 pm | updated_at TIMESTAMPTZ,
Sun, Jul 31 2022 12:27:00 pm | created_at TIMESTAMPTZ,
Sun, Jul 31 2022 12:27:00 pm | last_accessed_at TIMESTAMPTZ,
Sun, Jul 31 2022 12:27:00 pm | metadata jsonb
Sun, Jul 31 2022 12:27:00 pm | )
Sun, Jul 31 2022 12:27:00 pm | LANGUAGE plpgsql
Sun, Jul 31 2022 12:27:00 pm | AS $function$
Sun, Jul 31 2022 12:27:00 pm | BEGIN
Sun, Jul 31 2022 12:27:00 pm | return query
Sun, Jul 31 2022 12:27:00 pm | with files_folders as (
Sun, Jul 31 2022 12:27:00 pm | select path_tokens[levels] as folder
Sun, Jul 31 2022 12:27:00 pm | from storage.objects
Sun, Jul 31 2022 12:27:00 pm | where objects.name ilike prefix \|\| '%'
Sun, Jul 31 2022 12:27:00 pm | and bucket_id = bucketname
Sun, Jul 31 2022 12:27:00 pm | GROUP by folder
Sun, Jul 31 2022 12:27:00 pm | limit limits
Sun, Jul 31 2022 12:27:00 pm | offset offsets
Sun, Jul 31 2022 12:27:00 pm | )
Sun, Jul 31 2022 12:27:00 pm | select files_folders.folder as name, objects.id, objects.updated_at, objects.created_at, objects.last_accessed_at, objects.metadata from files_folders
Sun, Jul 31 2022 12:27:00 pm | left join storage.objects
Sun, Jul 31 2022 12:27:00 pm | on prefix \|\| files_folders.folder = objects.name
Sun, Jul 31 2022 12:27:00 pm | where objects.id is null or objects.bucket_id=bucketname;
Sun, Jul 31 2022 12:27:00 pm | END
Sun, Jul 31 2022 12:27:00 pm | $function$;
Sun, Jul 31 2022 12:27:00 pm | " message: "schema "storage" does not exist"
Sun, Jul 31 2022 12:27:26 pm | 2022-07-31 18:27:26.077: gotrue_migrations pid 480: LOG: pool_send_and_wait: Error or notice message from backend: : DB node id: 2 backend pid: 104269 statement: "select * from schema_migrations" message: "relation "schema_migrations" does not exist"
Sun, Jul 31 2022 12:27:26 pm | 2022-07-31 18:27:26.080: gotrue_migrations pid 480: LOG: pool_send_and_wait: Error or notice message from backend: : DB node id: 0 backend pid: 147747 statement: "CREATE TABLE "schema_migrations" (
Sun, Jul 31 2022 12:27:26 pm | "version" VARCHAR (14) NOT NULL
Sun, Jul 31 2022 12:27:26 pm | );
Sun, Jul 31 2022 12:27:26 pm | CREATE UNIQUE INDEX "schema_migrations_version_idx" ON "schema_migrations" (version);" message: "no schema has been selected to create in"
Sun, Jul 31 2022 12:27:26 pm | 2022-07-31 18:27:26.087: gotrue_migrations pid 480: ERROR: unable to read data from frontend
Sun, Jul 31 2022 12:27:26 pm | 2022-07-31 18:27:26.087: gotrue_migrations pid 480: DETAIL: EOF encountered with frontend
Sun, Jul 31 2022 12:28:18 pm | 2022-07-31 18:28:18.050: gotrue_migrations pid 598: LOG: pool_send_and_wait: Error or notice message from backend: : DB node id: 1 backend pid: 104231 statement: "select * from schema_migrations" message: "relation "schema_migrations" does not exist"
Sun, Jul 31 2022 12:28:18 pm | 2022-07-31 18:28:18.053: gotrue_migrations pid 598: LOG: pool_send_and_wait: Error or notice message from backend: : DB node id: 0 backend pid: 147935 statement: "CREATE TABLE "schema_migrations" (
Sun, Jul 31 2022 12:28:18 pm | "version" VARCHAR (14) NOT NULL
Sun, Jul 31 2022 12:28:18 pm | );
Sun, Jul 31 2022 12:28:18 pm | CREATE UNIQUE INDEX "schema_migrations_version_idx" ON "schema_migrations" (version);" message: "no schema has been selected to create in"
Sun, Jul 31 2022 12:28:18 pm | 2022-07-31 18:28:18.058: gotrue_migrations pid 598: ERROR: unable to read data from frontend
Sun, Jul 31 2022 12:28:18 pm | 2022-07-31 18:28:18.058: gotrue_migrations pid 598: DETAIL: EOF encountered with frontend
```

**Comment by joepa37** [comment]
I was able to solve this issue manually creating [the initial database structure](https://github.com/supabase/supabase/tree/master/docker/volumes/db/init).

**Comment by stubclan** [comment]
@joepa37  I am running into same issue as above trying to setup postgres with supabase-kubernetes https://github.com/supabase-community/supabase-kubernetes

The file you linked is empty, any idea what it looked like or where it's moved ?
