### ISSUE TITLE
react-data-grid emitting key console errors for Row and HeaderRow renders

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#8635]
Getting these errors on pages that render the table editor:

```
console.error
  Warning: Each child in a list should have a unique "key" prop.

  Check the render method of `HeaderRow`. See <https://reactjs.org/link/warning-keys> for more information.
      at HeaderCell (/Users/tzeyiing/supabase/supabase/studio/node_modules/@supabase/react-data-grid/src/HeaderCell.tsx:42:3)
      at HeaderRow (/Users/tzeyiing/supabase/supabase/studio/node_modules/@supabase/react-data-grid/src/HeaderRow.tsx:50:3)
      at div
      at DataGrid (/Users/tzeyiing/supabase/supabase/studio/node_modules/@supabase/react-data-grid/src/DataGrid.tsx:179:14)
      at div
      at section
      at LogTable (/Users/tzeyiing/supabase/supabase/studio/components/interfaces/Settings/Logs/LogTable.tsx:52:3)
      at div
      at LoadingOpacity (/Users/tzeyiing/supabase/supabase/studio/components/ui/LoadingOpacity.tsx:3:27)
      at div
      at div
      at LogsPreviewer (/Users/tzeyiing/supabase/supabase/studio/components/interfaces/Settings/Logs/LogsPreviewer.tsx:42:3)
      at SWRConfig$1 (/Users/tzeyiing/supabase/supabase/studio/node_modules/swr/dist/index.js:486:23)
      at LogsPreviewer

  at printWarning (node_modules/react/cjs/react-jsx-runtime.development.js:117:30)
  at error (node_modules/react/cjs/react-jsx-runtime.development.js:93:5)
  at validateExplicitKey (node_modules/react/cjs/react-jsx-runtime.development.js:986:5)
  at validateChildKeys (node_modules/react/cjs/react-jsx-runtime.development.js:1013:11)
  at jsxWithValidation (node_modules/react/cjs/react-jsx-runtime.development.js:1184:11)
  at Object._jsx [as jsx] (node_modules/react/cjs/react-jsx-runtime.development.js:1209:12)
  at HeaderRow (node_modules/@supabase/react-data-grid/src/HeaderRow.tsx:89:5)
  at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14985:18)

console.error
  Warning: Each child in a list should have a unique "key" prop.

  Check the render method of `Row`. See <https://reactjs.org/link/warning-keys> for more information.
      at Cell (/Users/tzeyiing/supabase/supabase/studio/node_modules/@supabase/react-data-grid/src/Cell.tsx:25:3)
      at Row (/Users/tzeyiing/supabase/supabase/studio/node_modules/@supabase/react-data-grid/src/Row.tsx:13:5)
      at div
      at DataGrid (/Users/tzeyiing/supabase/supabase/studio/node_modules/@supabase/react-data-grid/src/DataGrid.tsx:179:14)
      at div
      at section
      at LogTable (/Users/tzeyiing/supabase/supabase/studio/components/interfaces/Settings/Logs/LogTable.tsx:52:3)
      at div
      at LoadingOpacity (/Users/tzeyiing/supabase/supabase/studio/components/ui/LoadingOpacity.tsx:3:27)
      at div
      at div
      at LogsPreviewer (/Users/tzeyiing/supabase/supabase/studio/components/interfaces/Settings/Logs/LogsPreviewer.tsx:42:3)
      at SWRConfig$1 (/Users/tzeyiing/supabase/supabase/studio/node_modules/swr/dist/index.js:486:23)
      at LogsPreviewer

  at console.error (node_modules/@testing-library/react/dist/act-compat.js:55:34)
  at printWarning (node_modules/react/cjs/react-jsx-runtime.development.js:117:30)
  at error (node_modules/react/cjs/react-jsx-runtime.development.js:93:5)
  at validateExplicitKey (node_modules/react/cjs/react-jsx-runtime.development.js:986:5)
  at validateChildKeys (node_modules/react/cjs/react-jsx-runtime.development.js:1013:11)
  at jsxWithValidation (node_modules/react/cjs/react-jsx-runtime.development.js:1184:11)
  at Object._jsx [as jsx] (node_modules/react/cjs/react-jsx-runtime.development.js:1209:12)
  at Row (node_modules/@supabase/react-data-grid/src/Row.tsx:92:7)
```

**Comment by Nike682631** [comment]
@saltcod Is this issue available to work on?

**Comment by timagixe** [comment]
I would also like to help. I have no previous experience with `react-data-grid` but I am willing to to try. Just let me know if you need my help. Thanks.

**Comment by saltcod** [comment]
Hey @Nike682631 and @timagixe,  Yep this is definitely free to work on!
