### ISSUE TITLE
FATAL 42501 (insufficient_privilege) permission denied to set parameter pg_stat_statements.track

### ISSUE THREAD

**Issue by itisnajim** [supabase/supabase#9833]
# Bug report
FATAL 42501 (insufficient_privilege) permission denied to set parameter pg_stat_statements.track

## Describe the bug
after a time of running a self-hosted Supabase (docker)
i got the error:
```
[error] Postgrex.Protocol (#PID<0.235.0>) failed to connect: ** (Postgrex.Error) FATAL 42501 (insufficient_privilege) permission denied to set parameter "pg_stat_statements.track"
```

## To Reproduce
This always happens around 4-5 days after`docker-compose up -d` command is run.

## System information

Ubuntu 18.04 (LTS) x64
2 GB Memory
60 GB Disk
2 vCPUs

## Additional context

Full error message:
```
supabase-realtime | 2022-10-25 12:56:14.232 [error] Could not create schema migrations table. This error usually happens due to the following:
supabase-realtime | 
supabase-realtime |   * The database does not exist
supabase-realtime |   * The "schema_migrations" table, which Ecto uses for managing
supabase-realtime |     migrations, was defined by another library
supabase-realtime |   * There is a deadlock while migrating (such as using concurrent
supabase-realtime |     indexes with a migration_lock)
supabase-realtime | 
supabase-realtime | To fix the first issue, run "mix ecto.create".
supabase-realtime | 
supabase-realtime | To address the second, you can run "mix ecto.drop" followed by
supabase-realtime | "mix ecto.create". Alternatively you may configure Ecto to use
supabase-realtime | another table and/or repository for managing migrations:
supabase-realtime | 
supabase-realtime |     config :realtime, Realtime.RLS.Repo,
supabase-realtime |       migration_source: "some_other_table_for_schema_migrations",
supabase-realtime |       migration_repo: AnotherRepoForSchemaMigrations
supabase-realtime | 
supabase-realtime | The full error report is shown below.
supabase-realtime | 
supabase-realtime | 2022-10-25 12:56:14.237 [error] Postgrex.Protocol (#PID<0.234.0>) failed to connect: ** (Postgrex.Error) FATAL 42501 (insufficient_privilege) permission denied to set parameter "pg_stat_statements.track"
supabase-realtime | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 10948ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
supabase-realtime | 
supabase-realtime |   1. Ensuring your database is available and that you can connect to it
supabase-realtime |   2. Tracking down slow queries and making sure they are running fast enough
supabase-realtime |   3. Increasing the pool_size (although this increases resource consumption)
supabase-realtime |   4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
supabase-realtime | 
supabase-realtime | See DBConnection.start_link/2 for more information
supabase-realtime | 
supabase-realtime |     (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
supabase-realtime |     (elixir 1.11.4) lib/enum.ex:1411: Enum."-map/2-lists^map/1-0-"/2
supabase-realtime |     (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:852: Ecto.Adapters.SQL.execute_ddl/4
supabase-realtime |     (ecto_sql 3.7.1) lib/ecto/migrator.ex:678: Ecto.Migrator.verbose_schema_migration/3
supabase-realtime |     (ecto_sql 3.7.1) lib/ecto/migrator.ex:504: Ecto.Migrator.lock_for_migrations/4
supabase-realtime |     (ecto_sql 3.7.1) lib/ecto/migrator.ex:419: Ecto.Migrator.run/4
supabase-realtime |     (ecto_sql 3.7.1) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
supabase-realtime |     (realtime 0.0.0-automated) lib/realtime/release.ex:9: anonymous fn/2 in Realtime.Release.migrate/0
```

**Comment by kiwicopple** [comment]
is it possible that the database is failing here @itisnajim ? Perhaps the disk is full?

Can you connect to the database directly? (using something like psql)

**Comment by itisnajim** [comment]
Yes maybe, i'm trying limiting logs now using the steps:
https://github.com/supabase/supabase/issues/7736#issuecomment-1291347636

**Comment by itisnajim** [comment]
The error occurs even if the used disk space is less than 60%
